// Code generated by ent, DO NOT EDIT.

package buildversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the buildversion type in the database.
	Label = "build_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServiceName holds the string denoting the service_name field in the database.
	FieldServiceName = "service_name"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldLastBuild holds the string denoting the last_build field in the database.
	FieldLastBuild = "last_build"
	// Table holds the table name of the buildversion in the database.
	Table = "build_versions"
)

// Columns holds all SQL columns for buildversion fields.
var Columns = []string{
	FieldID,
	FieldServiceName,
	FieldVersion,
	FieldLastBuild,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ServiceNameValidator is a validator for the "service_name" field. It is called by the builders before save.
	ServiceNameValidator func(string) error
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// DefaultLastBuild holds the default value on creation for the "last_build" field.
	DefaultLastBuild func() time.Time
)

// OrderOption defines the ordering options for the BuildVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByServiceName orders the results by the service_name field.
func ByServiceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceName, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByLastBuild orders the results by the last_build field.
func ByLastBuild(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastBuild, opts...).ToFunc()
}
