apiVersion: v1
kind: Namespace
metadata:
  name: build-pipeline
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: build-pipeline-bucket
  namespace: build-pipeline
spec:
  generateBucketName: build-pipeline
  storageClassName: rook-ceph-bucket
