// Code generated by ent, DO NOT EDIT.

package inferencenode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the inferencenode type in the database.
	Label = "inference_node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "node_id"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldIPAddress holds the string denoting the ip_address field in the database.
	FieldIPAddress = "ip_address"
	// FieldGpuModel holds the string denoting the gpu_model field in the database.
	FieldGpuModel = "gpu_model"
	// FieldTotalVramMB holds the string denoting the total_vram_mb field in the database.
	FieldTotalVramMB = "total_vram_mb"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeMetrics holds the string denoting the metrics edge name in mutations.
	EdgeMetrics = "metrics"
	// ModelExecutionMetricFieldID holds the string denoting the ID field of the ModelExecutionMetric.
	ModelExecutionMetricFieldID = "metric_id"
	// Table holds the table name of the inferencenode in the database.
	Table = "inference_nodes"
	// MetricsTable is the table that holds the metrics relation/edge.
	MetricsTable = "model_execution_metrics"
	// MetricsInverseTable is the table name for the ModelExecutionMetric entity.
	// It exists in this package in order to avoid circular dependency with the "modelexecutionmetric" package.
	MetricsInverseTable = "model_execution_metrics"
	// MetricsColumn is the table column denoting the metrics relation/edge.
	MetricsColumn = "node_id"
)

// Columns holds all SQL columns for inferencenode fields.
var Columns = []string{
	FieldID,
	FieldHostname,
	FieldIPAddress,
	FieldGpuModel,
	FieldTotalVramMB,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the InferenceNode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHostname orders the results by the hostname field.
func ByHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostname, opts...).ToFunc()
}

// ByIPAddress orders the results by the ip_address field.
func ByIPAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPAddress, opts...).ToFunc()
}

// ByGpuModel orders the results by the gpu_model field.
func ByGpuModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGpuModel, opts...).ToFunc()
}

// ByTotalVramMB orders the results by the total_vram_mb field.
func ByTotalVramMB(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalVramMB, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByMetricsCount orders the results by metrics count.
func ByMetricsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMetricsStep(), opts...)
	}
}

// ByMetrics orders the results by metrics terms.
func ByMetrics(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMetricsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMetricsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MetricsInverseTable, ModelExecutionMetricFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MetricsTable, MetricsColumn),
	)
}
