// Code generated by ent, DO NOT EDIT.

package modelexecutionmetric

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the modelexecutionmetric type in the database.
	Label = "model_execution_metric"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "metric_id"
	// FieldResponseID holds the string denoting the response_id field in the database.
	FieldResponseID = "response_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldPromptTokens holds the string denoting the prompt_tokens field in the database.
	FieldPromptTokens = "prompt_tokens"
	// FieldCompletionTokens holds the string denoting the completion_tokens field in the database.
	FieldCompletionTokens = "completion_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldTotalDurationUsec holds the string denoting the total_duration_usec field in the database.
	FieldTotalDurationUsec = "total_duration_usec"
	// FieldLoadDurationUsec holds the string denoting the load_duration_usec field in the database.
	FieldLoadDurationUsec = "load_duration_usec"
	// FieldPromptEvalDurationUsec holds the string denoting the prompt_eval_duration_usec field in the database.
	FieldPromptEvalDurationUsec = "prompt_eval_duration_usec"
	// FieldEvalDurationUsec holds the string denoting the eval_duration_usec field in the database.
	FieldEvalDurationUsec = "eval_duration_usec"
	// FieldTokensPerSecond holds the string denoting the tokens_per_second field in the database.
	FieldTokensPerSecond = "tokens_per_second"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// EdgeNode holds the string denoting the node edge name in mutations.
	EdgeNode = "node"
	// EdgeModel holds the string denoting the model edge name in mutations.
	EdgeModel = "model"
	// SessionFieldID holds the string denoting the ID field of the Session.
	SessionFieldID = "session_id"
	// InferenceNodeFieldID holds the string denoting the ID field of the InferenceNode.
	InferenceNodeFieldID = "node_id"
	// ModelDefinitionFieldID holds the string denoting the ID field of the ModelDefinition.
	ModelDefinitionFieldID = "model_id"
	// Table holds the table name of the modelexecutionmetric in the database.
	Table = "model_execution_metrics"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "model_execution_metrics"
	// SessionInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionInverseTable = "sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "session_id"
	// NodeTable is the table that holds the node relation/edge.
	NodeTable = "model_execution_metrics"
	// NodeInverseTable is the table name for the InferenceNode entity.
	// It exists in this package in order to avoid circular dependency with the "inferencenode" package.
	NodeInverseTable = "inference_nodes"
	// NodeColumn is the table column denoting the node relation/edge.
	NodeColumn = "node_id"
	// ModelTable is the table that holds the model relation/edge.
	ModelTable = "model_execution_metrics"
	// ModelInverseTable is the table name for the ModelDefinition entity.
	// It exists in this package in order to avoid circular dependency with the "modeldefinition" package.
	ModelInverseTable = "model_definitions"
	// ModelColumn is the table column denoting the model relation/edge.
	ModelColumn = "model_id"
)

// Columns holds all SQL columns for modelexecutionmetric fields.
var Columns = []string{
	FieldID,
	FieldResponseID,
	FieldSessionID,
	FieldNodeID,
	FieldModelID,
	FieldPromptTokens,
	FieldCompletionTokens,
	FieldTotalTokens,
	FieldTotalDurationUsec,
	FieldLoadDurationUsec,
	FieldPromptEvalDurationUsec,
	FieldEvalDurationUsec,
	FieldTokensPerSecond,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ModelExecutionMetric queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResponseID orders the results by the response_id field.
func ByResponseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByPromptTokens orders the results by the prompt_tokens field.
func ByPromptTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptTokens, opts...).ToFunc()
}

// ByCompletionTokens orders the results by the completion_tokens field.
func ByCompletionTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByTotalDurationUsec orders the results by the total_duration_usec field.
func ByTotalDurationUsec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalDurationUsec, opts...).ToFunc()
}

// ByLoadDurationUsec orders the results by the load_duration_usec field.
func ByLoadDurationUsec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoadDurationUsec, opts...).ToFunc()
}

// ByPromptEvalDurationUsec orders the results by the prompt_eval_duration_usec field.
func ByPromptEvalDurationUsec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptEvalDurationUsec, opts...).ToFunc()
}

// ByEvalDurationUsec orders the results by the eval_duration_usec field.
func ByEvalDurationUsec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvalDurationUsec, opts...).ToFunc()
}

// ByTokensPerSecond orders the results by the tokens_per_second field.
func ByTokensPerSecond(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokensPerSecond, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}

// ByNodeField orders the results by node field.
func ByNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByModelField orders the results by model field.
func ByModelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelStep(), sql.OrderByField(field, opts...))
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, SessionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
	)
}
func newNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NodeInverseTable, InferenceNodeFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
	)
}
func newModelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelInverseTable, ModelDefinitionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModelTable, ModelColumn),
	)
}
