apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  secretName: grafana-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Hierocracy
  commonName: grafana.rag.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - grafana
    - grafana.monitoring
    - grafana.monitoring.svc
    - grafana.monitoring.svc.cluster.local
    - grafana.rag.local
    - grafana.hierocracy.home
  issuerRef:
    name: hierocracy-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
