// Code generated by ent, DO NOT EDIT.

package prompt

import (
	"app-builds/common/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Prompt {
	return predicate.Prompt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Prompt {
	return predicate.Prompt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Prompt {
	return predicate.Prompt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Prompt {
	return predicate.Prompt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Prompt {
	return predicate.Prompt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Prompt {
	return predicate.Prompt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Prompt {
	return predicate.Prompt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Prompt {
	return predicate.Prompt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Prompt {
	return predicate.Prompt(sql.FieldLTE(FieldID, id))
}

// PromptID applies equality check predicate on the "prompt_id" field. It's identical to PromptIDEQ.
func PromptID(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldEQ(FieldPromptID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldEQ(FieldSessionID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Prompt {
	return predicate.Prompt(sql.FieldEQ(FieldCreatedAt, v))
}

// PromptIDEQ applies the EQ predicate on the "prompt_id" field.
func PromptIDEQ(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldEQ(FieldPromptID, v))
}

// PromptIDNEQ applies the NEQ predicate on the "prompt_id" field.
func PromptIDNEQ(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldNEQ(FieldPromptID, v))
}

// PromptIDIn applies the In predicate on the "prompt_id" field.
func PromptIDIn(vs ...uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldIn(FieldPromptID, vs...))
}

// PromptIDNotIn applies the NotIn predicate on the "prompt_id" field.
func PromptIDNotIn(vs ...uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldNotIn(FieldPromptID, vs...))
}

// PromptIDGT applies the GT predicate on the "prompt_id" field.
func PromptIDGT(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldGT(FieldPromptID, v))
}

// PromptIDGTE applies the GTE predicate on the "prompt_id" field.
func PromptIDGTE(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldGTE(FieldPromptID, v))
}

// PromptIDLT applies the LT predicate on the "prompt_id" field.
func PromptIDLT(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldLT(FieldPromptID, v))
}

// PromptIDLTE applies the LTE predicate on the "prompt_id" field.
func PromptIDLTE(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldLTE(FieldPromptID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v uuid.UUID) predicate.Prompt {
	return predicate.Prompt(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDIsNil applies the IsNil predicate on the "session_id" field.
func SessionIDIsNil() predicate.Prompt {
	return predicate.Prompt(sql.FieldIsNull(FieldSessionID))
}

// SessionIDNotNil applies the NotNil predicate on the "session_id" field.
func SessionIDNotNil() predicate.Prompt {
	return predicate.Prompt(sql.FieldNotNull(FieldSessionID))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Prompt {
	return predicate.Prompt(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Prompt {
	return predicate.Prompt(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Prompt {
	return predicate.Prompt(sql.FieldContainsFold(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Prompt {
	return predicate.Prompt(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Prompt {
	return predicate.Prompt(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Prompt {
	return predicate.Prompt(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Prompt {
	return predicate.Prompt(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Prompt {
	return predicate.Prompt(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Prompt {
	return predicate.Prompt(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Prompt {
	return predicate.Prompt(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Prompt {
	return predicate.Prompt(sql.FieldLTE(FieldCreatedAt, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Prompt {
	return predicate.Prompt(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Prompt {
	return predicate.Prompt(sql.FieldNotNull(FieldMetadata))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Prompt) predicate.Prompt {
	return predicate.Prompt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Prompt) predicate.Prompt {
	return predicate.Prompt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Prompt) predicate.Prompt {
	return predicate.Prompt(sql.NotPredicates(p))
}
