apiVersion: v1
kind: Namespace
metadata:
  name: container-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: container-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: container-registry
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeSelector:
        role: storage-node
      containers:
      - name: registry
        image: hierophant.hierocracy.home:5000/registry:2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: storage
          mountPath: /var/lib/registry
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: container-registry
  annotations:
    purelb.io/addresspool: default
spec:
  type: LoadBalancer
  loadBalancerIP: 172.20.1.26
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: registry
