machine:
  registries:
    mirrors:
      docker.io:
        endpoints:
          - http://hierophant.hierocracy.home:5000
          - https://registry-1.docker.io
      quay.io:
        endpoints:
          - http://hierophant.hierocracy.home:5000
          - https://quay.io
      registry.k8s.io:
        endpoints:
          - http://hierophant.hierocracy.home:5000
          - https://registry.k8s.io
      ghcr.io:
        endpoints:
          - http://hierophant.hierocracy.home:5000
          - https://ghcr.io
      hierophant.hierocracy.home:5000:
        endpoints:
          - http://hierophant.hierocracy.home:5000
      registry.hierocracy.home:5000:
        endpoints:
          - http://hierophant.hierocracy.home:5000
          - http://172.20.1.26:5000
    config:
      hierophant.hierocracy.home:5000:
        tls:
          insecure: true
      registry.hierocracy.home:5000:
        tls:
          insecure: true
