machine:
  install:
    extraCerts:
      - |
        -----BEGIN CERTIFICATE-----
        MIIFnTCCA4WgAwIBAgIUH8pCxaY1Be1pEtpXX1/iYuSdYHAwDQYJKoZIhvcNAQEL
        BQAwXjELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQHDARDaXR5
        MRMwEQYDVQQKDApIaWVyb2NyYWN5MRswGQYDVQQDDBJIaWVyb2NyYWN5IFJvb3Qg
        Q0EwHhcNMjYwMzEyMjEwNzM3WhcNMzYwMzA5MjEwNzM3WjBeMQswCQYDVQQGEwJV
        UzEOMAwGA1UECAwFU3RhdGUxDTALBgNVBAcMBENpdHkxEzARBgNVBAoMCkhpZXJv
        Y3JhY3kxGzAZBgNVBAMMEkhpZXJvY3JhY3kgUm9vdCBDQTCCAiIwDQYJKoZIhvcN
        AQEBBQADggIPADCCAgoCggIBAJjBhKWmOKQxqunjOPuVcN6QtU/G7FZHCbpY+8Pi
        a7UjuhTCs321V1Ar9OqrAtXx5D+QzR/S7uKMggRm+WdfIGzHLL/7dcHxJQgFDy3D
        qOR0GR4wTD8jrs3Q8w6KgXXhDlHCQaoQyFZn/G1IMOGeL7znqRUMZ6PtaGDBbZJV
        DZM67QpyBNMUeo7eFvQE6L68UuNhtlMptS/XIIQdouQaWX0hRmxZi/eyE32uBQpY
        YZuyud13W5DIsAs1dssMIyIeLCtzGnw+Mq6V/GrDBsE8YmgrFzF+G/dr4oxv5WtM
        3za63eeb7c/hEfroL+iETwjUbPsfDJgEvfa6SXHsRtMCkNe3gwf2bZ4FQ0wB56Gu
        7sk5VJmBoIZ+eLRIF3L6UbFrdzqFcoQPMmVZZ+W5hQpg3qaGIGlrHtf2Sls5xk5s
        htXhT69I97zecrTulgFPajq4crYnrEU1Q1LhJCJ+HAngfQ8FsZyAQ4aCkXEGs2e/
        2yDbbUUNS/XIV5739/SaGVFbJJrAVRi2ceDoQSgt1tVtlUTg48O68UN/0BYgJfLj
        +GCLx9FNX65KlcRV6J5DSyvdeA81uXorz8t/Mcz0AZwThmJd9JUKRKDklbU6ounF
        YUXPjK7r9QWA/tSxgQf5rdSDy4aBVHZx+l2RxS0S8wbdadWWNMY4JMojlNJ1CIQ+
        rQaDAgMBAAGjUzBRMB0GA1UdDgQWBBQEfEg/zxdWbAink0k8Ia2EaHyeuDAfBgNV
        HSMEGDAWgBQEfEg/zxdWbAink0k8Ia2EaHyeuDAPBgNVHRMBAf8EBTADAQH/MA0G
        CSqGSIb3DQEBCwUAA4ICAQBqWGkyP0Uvrx5tqo45xpbSIthoDO7AEb4DE+ganGrr
        AD5ZD0e0T7N4KVvxF+vXE4y79lhJcG4+WTu4D4h64hD+uoYMd+IlIbk5V5mZ+DOL
        Iy45v5yRHrm32rOU5AZYT0zZTlBxyPqcU6KgWjjlg7ljKicDyT8XsPjwJiU/5D4q
        1w9TR/JxOM6ZBs2B8bcVD/xdjNQ7yq3lfbG6Vk4N3FCEkIZCtKcqffha1fu3Annu
        6udtmFZEG3BYBi1s9WkkUtVTlyq3z0xFfHJhMNOg6U9Tc5fciKqtMwYLkSKFsfmd
        y5pCvN3ptdZxYI/6nI0i+kNNliO6DHg3JTg+zlX32ASL09AuQ1kB8W7Jmz9R6aTx
        IVZ4Z1NHHA68AO5c232IlgJ1yxsqMZXyk37ld+2+yXxN0rbU+330L/nCkZPaiboV
        kWdvHCPG37ZZbYVzBuP3XdR59CaALge3L2riTva3KtsUAQWYscPXj/R1Qu6tPJjS
        qn1pPZ4M5GUHCJ5ttJa9HVCh2MdkXACHMlaLSVjMuqQTbOdyRHXMxOTPF4CgJGc7
        u4VIf/TOYOHRdomxiVH0LRnZp5ifRW+0tYHmmQwx6/4reLK/s7tC333odTi8arJD
        h/SOHSXEGPgzBdCTj9H21YGEagTfnurjrUDuzPlg+QrGruY+fP9/i09Lpc2j/ohD
        Fg==
        -----END CERTIFICATE-----
  network:
    extraHostEntries:
      - ip: 10.0.0.1
        aliases:
          - hierophant.hierocracy.home
          - registry.hierocracy.home
          - hierophant
  registries:
    mirrors:
      docker.io:
        endpoints:
          - https://10.0.0.1:5000
          - https://registry-1.docker.io
      quay.io:
        endpoints:
          - https://10.0.0.1:5000
          - https://quay.io
      registry.k8s.io:
        endpoints:
          - https://10.0.0.1:5000
          - https://registry.k8s.io
      ghcr.io:
        endpoints:
          - https://10.0.0.1:5000
          - https://ghcr.io
      10.0.0.1:5000:
        endpoints:
          - https://10.0.0.1:5000
      hierophant.hierocracy.home:5000:
        endpoints:
          - https://10.0.0.1:5000
      registry.hierocracy.home:5000:
        endpoints:
          - https://10.0.0.1:5000
    config:
      10.0.0.1:5000:
        tls:
          ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZuVENDQTRXZ0F3SUJBZ0lVSDhwQ3hhWTFCZTFwRXRwWFgxL2lZdVNkWUhBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hqRUxNQWtHQTFVRUBoTUNWVk14RGpBTUJnTlZCQWdNQlZOMFlYUmxNUTB3Q3dZRFZRUUhEQVJEYVhSNQpNUk13RVFZRFZRUUtEQXBJYVdcelluekVVTDFRMUxoSkpDK0hBbmdmUThGc1p5QVE0YUNrWEVHczJlLwoyeURiYlVVTlMvWElWNTczOS9TYUdWRmJKSnJBVlJpMmNlRG9RU2d0MXRWdGxVVGc0OE82OFVOLzBCWWdKZkxqCitHQ0x4OUZOWDY1S2xjUlY2SjVEU3l2ZGVBODF1WG9yejh0L01jejBBWndUaG1KZDlKVUtSS0RrbGJVNm91bkYKWVVYUGpLN3I5UVdBL3RTeGdRZjVyZFNEeTRhQlZIWngrbDJSeFMwUzh3YmRhZFdXTk1ZNEpNb2psTkoxQ0lRKwpyUWFEQWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJRRWZFZy96eGRXYkFpbmswazhJYTJFYUh5ZXVEQWZCZ05WCkhTTUVHREFXZ0JRRWZFZy96eGRXYkFpbmswazhJYTJFYUh5ZXVEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUJxV0dreVAwVXZyeDV0cW80NXhwYlNJdGhvRE83QUViNERFK2dhbkdycgpBRDVaRDBlMFQ3TjRLVnZ4Rit2WEU0eTc5bGhKY0c0K1dUdTRENGg2NGhEK3VvWU1kK0lsSWJrNVY1bVorRE9MCkl5NDV2NXlSSHJtMzJyT1U1QVpZVDB6WlRsQnh5UHFjVTZLZ1dqamxnN2xqS2ljRHlUOFhzUGp3SmlVLzVENHEKMXc5VFIvSnhPTTZaQnMyQjhiY1ZEL3hkak5RN3lxM2xmYkc2Vms0TjNGQ0VrSVpDdEtjcWZmaGExZnUzQW5udQo2dWR0bUZaRUczQllCaTFzOVdra1V0VlRseXEzejB4RmZISmhNTk9nNlU5VGM1ZmNpS3F0TXdZTGtTS0ZzZm1kCnk1cEN2TjNwdGRaeFlJLzZuSTBpK2tOTmxpTzZESGczSlRnK3psWDMyQVNMMDlBdVExa0I4VzdKbXo5UjZhVHgKSVZaNFoxTkhIQTY4QU81YzIzMklsZ0oxeXhzcU1aWHlrMzdsZCsyK3lYeE4wcmJVKzMzMEwvbkNrWlBhaWJvVgprV2R2SENQRzM3WlpiWVZ6QnVQM1hkUjU5Q2FBTGdlM0wycmlUdmEzS3RzVUFRV1lzY1BYai9SMVF1NnRQSmpTCnFuMXBQWjRNNUdVSENKNXR0SmE5SFZDaDJNZGtYQUNITWxhTFNWak11cVFUYk9keVJIWE14T1RQRjRDZ0pHYzcKdTRWSWYvVE9ZT0hSZG9teGlWSDBMUm5acDVpZlJWKzB0WUhtbVF3eDYvNHJlTEsvczd0QzMzM29kVGk4YXJKRApoL1NPSFNYRUdQZ3pCZENUajlIMjFZR0VhZ1RmbnVyanJVRHV6UGxnK1FyR3J1WStmUDkvaTA5THBjMmovb2hECkZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      hierophant.hierocracy.home:5000:
        tls:
          ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZuVENDQTRXZ0F3SUJBZ0lVSDhwQ3hhWTFCZTFwRXRwWFgxL2lZdVNkWUhBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hqRUxNQWtHQTFVRUBoTUNWVk14RGpBTUJnTlZCQWdNQlZOMFlYUmxNUTB3Q3dZRFZRUUhEQVJEYVhSNQpNUk13RVFZRFZRUUtEQXBJYVdcelluekVVTDFRMUxoSkpDK0hBbmdmUThGc1p5QVE0YUNrWEVHczJlLwoyeURiYlVVTlMvWElWNTczOS9TYUdWRmJKSnJBVlJpMmNlRG9RU2d0MXRWdGxVVGc0OE82OFVOLzBCWWdKZkxqCitHQ0x4OUZOWDY1S2xjUlY2SjVEU3l2ZGVBODF1WG9yejh0L01jejBBWndUaG1KZDlKVUtSS0RrbGJVNm91bkYKWVVYUGpLN3I5UVdBL3RTeGdRZjVyZFNEeTRhQlZIWngrbDJSeFMwUzh3YmRhZFdXTk1ZNEpNb2psTkoxQ0lRKwpyUWFEQWdNQkFBR2pVekJSTMB0L01jejBBWndUaG1KZDlKVUtSS0RrbGJVNm91bkYKWVVYUGpLN3I5UVdBL3RTeGdRZjVyZFNEeTRhQlZIWngrbDJSeFMwUzh3YmRhZFdXTk1ZNEpNb2psTkoxQ0lRKwpyUWFEQWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJRRWZFZy96eGRXYkFpbmswazhJYTJFYUh5ZXVEQWZCZ05WCkhTTUVHREFXZ0JRRWZFZy96eGRXYkFpbmswazhJYTJFYUh5ZXVEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUJxV0dreVAwVXZyeDV0cW80NXhwYlNJdGhvRE83QUViNERFK2dhbkdycgpBRDVaRDBlMFQ3TjRLVnZ4Rit2WEU0eTc5bGhKY0c0K1dUdTRENGg2NGhEK3VvWU1kK0lsSWJrNVY1bWorRE9MCkl5NDV2NXlSSHJtMzJyT1U1QVpZVDB6WlRsQnh5UHFjVTZLZ1dqamxnN2xqS2ljRHlUOFhzUGp3SmlVLzVENHEKMXc5VFIvSnhPTTZaQnMyQjhiY1ZEL3hkak5RN3lxM2xmYkc2Vms0TjNGQ0VrSVpDdEtjcWZmaGExZnUzQW5udQo2dWR0bUZaRUczQllCaTFzOVdra1V0VlRseXEzejB4RmZISmhNTk9nNlU5VGM1ZmNpS3F0TXdZTGtTS0ZzZm1kCnk1cEN2TjNwdGRaeFlJLzZuSTBpK2tOTmxpTzZESGczSlRnK3psWDMyQVNMMDlBdVExa0I4VzdKbXo5UjZhVHgKSVZaNFoxTkhIQTY4QU81YzIzMklsZ0oxeXhzcU1aWHlrMzdsZCsyK3lYeE4wcmJVKzMzMEwvbkNrWlBhaWJvVgprV2R2SENQRzM3WlpiWVZ6QnVQM1hkUjU5Q2FBTGdlM0wycmlUdmEzS3RzVUFRV1lzY1BYai9SMVF1NnRQSmpTCnFuMXBQWjRNNUdVSENKNXR0SmE5SFZDaDJNZGtYQUNITWxhTFNWak11cVFUYk9keVJIWE14T1RQRjRDZ0pHYzcKdTRWSWYvVE9ZT0hSZG9teGlWSDBMUm5acDVpZlJWKzB0WUhtbVF3eDYvNHJlTEsvczd0QzMzM29kVGk4YXJKRApoL1NPSFNYRUdQZ3pCZENUajlIMjFZR0VhZ1RmbnVyanJVRHV6UGxnK1FyR3J1WStmUDkvaTA5THBjMmovb2hECkZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      registry.hierocracy.home:5000:
        tls:
          ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZuVENDQTRXZ0F3SUJBZ0lVSDhwR3pCZENUajlIMjFZR0VhZ1RmbnVyanJVRHV6UGxnK1FyR3J1WStmUDkvaTA5THBjMmovb2hECkZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
