machine:
  registries:
    mirrors:
      "*":
        endpoints:
          - http://172.20.1.26:5000
          - http://172.20.0.1:5000
      172.20.1.26:5000:
        endpoints:
          - http://172.20.1.26:5000
      registry.container-registry.svc.cluster.local:5000:
        endpoints:
          - http://172.20.1.26:5000
          - http://172.20.0.1:5000
      registry.hierocracy.home:5000:
        endpoints:
          - http://172.20.1.26:5000
          - http://172.20.0.1:5000
    config:
      172.20.1.26:5000:
        tls:
          insecureSkipVerify: true
      172.20.0.1:5000:
        tls:
          insecureSkipVerify: true
      registry.container-registry.svc.cluster.local:5000:
        tls:
          insecureSkipVerify: true
      registry.hierocracy.home:5000:
        tls:
          insecureSkipVerify: true
