// Code generated by ent, DO NOT EDIT.

package actionidentifier

import (
	"app-builds/common/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldLTE(FieldID, id))
}

// Identifier applies equality check predicate on the "identifier" field. It's identical to IdentifierEQ.
func Identifier(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldEQ(FieldIdentifier, v))
}

// IdentifierEQ applies the EQ predicate on the "identifier" field.
func IdentifierEQ(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldEQ(FieldIdentifier, v))
}

// IdentifierNEQ applies the NEQ predicate on the "identifier" field.
func IdentifierNEQ(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldNEQ(FieldIdentifier, v))
}

// IdentifierIn applies the In predicate on the "identifier" field.
func IdentifierIn(vs ...string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldIn(FieldIdentifier, vs...))
}

// IdentifierNotIn applies the NotIn predicate on the "identifier" field.
func IdentifierNotIn(vs ...string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldNotIn(FieldIdentifier, vs...))
}

// IdentifierGT applies the GT predicate on the "identifier" field.
func IdentifierGT(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldGT(FieldIdentifier, v))
}

// IdentifierGTE applies the GTE predicate on the "identifier" field.
func IdentifierGTE(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldGTE(FieldIdentifier, v))
}

// IdentifierLT applies the LT predicate on the "identifier" field.
func IdentifierLT(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldLT(FieldIdentifier, v))
}

// IdentifierLTE applies the LTE predicate on the "identifier" field.
func IdentifierLTE(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldLTE(FieldIdentifier, v))
}

// IdentifierContains applies the Contains predicate on the "identifier" field.
func IdentifierContains(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldContains(FieldIdentifier, v))
}

// IdentifierHasPrefix applies the HasPrefix predicate on the "identifier" field.
func IdentifierHasPrefix(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldHasPrefix(FieldIdentifier, v))
}

// IdentifierHasSuffix applies the HasSuffix predicate on the "identifier" field.
func IdentifierHasSuffix(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldHasSuffix(FieldIdentifier, v))
}

// IdentifierEqualFold applies the EqualFold predicate on the "identifier" field.
func IdentifierEqualFold(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldEqualFold(FieldIdentifier, v))
}

// IdentifierContainsFold applies the ContainsFold predicate on the "identifier" field.
func IdentifierContainsFold(v string) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.FieldContainsFold(FieldIdentifier, v))
}

// HasActionType applies the HasEdge predicate on the "action_type" edge.
func HasActionType() predicate.ActionIdentifier {
	return predicate.ActionIdentifier(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActionTypeTable, ActionTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActionTypeWith applies the HasEdge predicate on the "action_type" edge with a given conditions (other predicates).
func HasActionTypeWith(preds ...predicate.ActionType) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(func(s *sql.Selector) {
		step := newActionTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ActionIdentifier) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ActionIdentifier) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ActionIdentifier) predicate.ActionIdentifier {
	return predicate.ActionIdentifier(sql.NotPredicates(p))
}
