-- DEPRECATED: This file is superseded by infrastructure/timescaledb/schema.sql (unified DDL)
-- Intentionally left minimal to avoid accidental application.
-- Please use the unified schema:
--   /rag-stack/infrastructure/timescaledb/schema.sql
