-- Iteration 4: Enhanced Chat History and Session Management
-- This schema supports multiple responses per prompt and robust searching.

-- Drop old chat_messages if it exists to avoid confusion with the new split structure
-- (In a real production environment we would migrate, but here we align with the new spec)
DROP TABLE IF EXISTS chat_messages CASCADE;

-- 1. Prompts table
CREATE TABLE IF NOT EXISTS prompts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prompt_id UUID DEFAULT gen_random_uuid(),
    session_id UUID REFERENCES sessions(session_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB,
    PRIMARY KEY (id, created_at)
);

-- 1a. Standard Indexes
CREATE INDEX IF NOT EXISTS idx_prompts_session ON prompts(session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_prompts_prompt ON prompts(prompt_id, created_at DESC);

-- 2. Responses table
CREATE TABLE IF NOT EXISTS responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    response_id UUID DEFAULT gen_random_uuid(),
    prompt_id BIGINT,
    session_id UUID REFERENCES sessions(session_id) ON DELETE CASCADE, -- Denormalized for easier querying
    content TEXT NOT NULL,
    sequence_number INTEGER NOT NULL,
    model_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB,
    PRIMARY KEY (id, created_at)
);

-- 2a. Standard Indexes
CREATE INDEX IF NOT EXISTS idx_responses_prompt ON responses(prompt_id, sequence_number);
CREATE INDEX IF NOT EXISTS idx_responses_response ON responses(response_id, sequence_number);
CREATE INDEX IF NOT EXISTS idx_responses_session ON responses(session_id, created_at DESC);

-- 4. Convert to Hypertables for Time-Series performance
SELECT create_hypertable('prompts', 'created_at', if_not_exists => TRUE);
SELECT create_hypertable('responses', 'created_at', if_not_exists => TRUE);

-- 5. Keyword Search Indexes (GIN)
-- Add GIN index for full-text search on content
CREATE INDEX IF NOT EXISTS idx_prompts_content_gin ON prompts USING GIN (to_tsvector('english', content));
CREATE INDEX IF NOT EXISTS idx_responses_content_gin ON responses USING GIN (to_tsvector('english', content));

-- 6. Enhance sessions table if needed (name/description already exist in schema.sql)
-- Adding description to sessions if not already there (it was in schema.sql but let's be sure)
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS description TEXT;
