-- Iteration 6b: Model Execution Metrics (3NF)
-- This migration adds a normalized structure for tracking model performance.

-- 1. Inference Nodes (Dimension)
CREATE TABLE IF NOT EXISTS inference_nodes (
    node_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hostname TEXT UNIQUE NOT NULL,
    ip_address TEXT,
    gpu_model TEXT,
    total_vram_mb INTEGER,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Model Definitions (Dimension)
CREATE TABLE IF NOT EXISTS model_definitions (
    model_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    model_name TEXT UNIQUE NOT NULL, -- e.g. "llama3.1:8b"
    family TEXT, -- llama, granite, etc.
    parameters_billions REAL,
    quantization TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Model Execution Metrics (Fact Table)
CREATE TABLE IF NOT EXISTS model_execution_metrics (
    metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    response_id UUID,
    session_id UUID REFERENCES sessions(session_id) ON DELETE CASCADE,
    node_id UUID REFERENCES inference_nodes(node_id),
    model_id UUID REFERENCES model_definitions(model_id),
    
    -- Token counts
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER GENERATED ALWAYS AS (prompt_tokens + completion_tokens) STORED,
    
    -- Durations (microseconds for precision, converted to ms in views)
    total_duration_usec BIGINT,
    load_duration_usec BIGINT,
    prompt_eval_duration_usec BIGINT,
    eval_duration_usec BIGINT,
    
    -- Derived Metrics
    tokens_per_second REAL,
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (metric_id, created_at)
);

-- We omit the FK to responses(response_id) because responses is a hypertable partitioned by created_at,
-- and referencing a non-unique column (response_id) from another hypertable is complex in PostgreSQL/TimescaleDB.
-- We will maintain referential integrity at the application level.

-- Convert to hypertable for time-series analysis
SELECT create_hypertable('model_execution_metrics', 'created_at', if_not_exists => TRUE);

-- Indexes for performance comparison
CREATE INDEX IF NOT EXISTS idx_metrics_model ON model_execution_metrics(model_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_metrics_session ON model_execution_metrics(session_id);
CREATE INDEX IF NOT EXISTS idx_metrics_node ON model_execution_metrics(node_id);

-- View for easy performance comparison (Efficiency Score)
CREATE OR REPLACE VIEW model_performance_comparison AS
SELECT 
    m.model_name,
    n.hostname as node,
    AVG(mem.tokens_per_second) as avg_tokens_per_sec,
    AVG(mem.total_duration_usec / 1000.0) as avg_latency_ms,
    COUNT(*) as total_executions
FROM model_execution_metrics mem
JOIN model_definitions m ON mem.model_id = m.model_id
JOIN inference_nodes n ON mem.node_id = n.node_id
GROUP BY m.model_name, n.hostname;
