-- RAG Session Management Schema (Unified)
-- Using TimescaleDB for time-series chat history
-- NOTE: This unified schema supersedes prior iteration-specific DDLs.

CREATE TABLE IF NOT EXISTS projects (
    project_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES projects(project_id) ON DELETE CASCADE,
    name TEXT UNIQUE,
    description TEXT,
    metadata JSONB, -- For any extra info
    user_id UUID,
    created_at TIMESTAMPTZ DEFAULT now(),
    last_active_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Prompts (hypertable)
CREATE TABLE IF NOT EXISTS prompts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prompt_id UUID DEFAULT gen_random_uuid(),
    session_id UUID REFERENCES sessions(session_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB,
    PRIMARY KEY (id, created_at)
);
SELECT create_hypertable('prompts', 'created_at', if_not_exists => TRUE);

-- 3a. Prompt indexes
CREATE INDEX IF NOT EXISTS idx_prompts_session ON prompts(session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_prompts_prompt ON prompts(prompt_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_prompts_content_gin ON prompts USING GIN (to_tsvector('english', content));

-- Retention policy example; adjust as needed per hypertable
-- SELECT add_retention_policy('prompts', INTERVAL '90 days', if_not_exists => TRUE);

CREATE TABLE IF NOT EXISTS retrieval_logs (
    log_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    message_id UUID, -- Optional linkage to message/prompt
    retrieved_chunks JSONB, -- List of paths and chunks
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Iteration 2: Ingestion and Tagging Support

-- 6. Code Ingestion Tracking
CREATE TABLE IF NOT EXISTS code_ingestion (
    ingestion_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    s3_bucket_id TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. Tag Definition
CREATE TABLE IF NOT EXISTS tag (
  tag_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tag_name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 8. Ingestion to Tag Mapping
CREATE TABLE IF NOT EXISTS code_ingestion_tag (
    ingestion_id UUID REFERENCES code_ingestion(ingestion_id) ON DELETE CASCADE,
    tag_id UUID REFERENCES tag(tag_id) ON DELETE CASCADE,
    PRIMARY KEY (ingestion_id, tag_id)
);

-- 9. Code Embedding Index (Metadata backup)
CREATE TABLE IF NOT EXISTS code_embedding (
    embedding_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ingestion_id UUID REFERENCES code_ingestion(ingestion_id) ON DELETE CASCADE,
    embedding_vector JSONB, -- Changed from REAL[] for Ent compatibility
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 10. Embedding to Tag Mapping
CREATE TABLE IF NOT EXISTS code_embedding_tag (
    embedding_id UUID REFERENCES code_embedding(embedding_id) ON DELETE CASCADE,
    tag_id UUID REFERENCES tag(tag_id) ON DELETE CASCADE,
    PRIMARY KEY (embedding_id, tag_id)
);

-- 11. Session to Tag Association
CREATE TABLE IF NOT EXISTS session_tag (
    session_id UUID REFERENCES sessions(session_id) ON DELETE CASCADE,
    tag_id UUID REFERENCES tag(tag_id) ON DELETE CASCADE,
    PRIMARY KEY (session_id, tag_id)
);

-- 12. Responses (hypertable)
CREATE TABLE IF NOT EXISTS responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    response_id UUID DEFAULT gen_random_uuid(),
    prompt_id BIGINT, -- references prompts(id) logically
    session_id UUID REFERENCES sessions(session_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    sequence_number INTEGER NOT NULL,
    model_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB,
    PRIMARY KEY (id, created_at)
);
SELECT create_hypertable('responses', 'created_at', if_not_exists => TRUE);

-- 12a. Response indexes
CREATE INDEX IF NOT EXISTS idx_responses_prompt ON responses(prompt_id, sequence_number);
CREATE INDEX IF NOT EXISTS idx_responses_response ON responses(response_id, sequence_number);
CREATE INDEX IF NOT EXISTS idx_responses_session ON responses(session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_responses_content_gin ON responses USING GIN (to_tsvector('english', content));

CREATE OR REPLACE PROCEDURE expire_old_sessions(job_id int, config jsonb)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM sessions
    WHERE last_active_at < now() - INTERVAL '24 hours';
END
$$;

-- Register cleanup job (every 1 hour)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM timescaledb_information.jobs WHERE proc_name = 'expire_old_sessions') THEN
        PERFORM add_job('expire_old_sessions', '1 hour');
    END IF;
END
$$;

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_sessions_project ON sessions(project_id);
CREATE INDEX IF NOT EXISTS idx_tag_name ON tag(tag_name);
CREATE INDEX IF NOT EXISTS idx_code_ingestion_bucket ON code_ingestion(s3_bucket_id);

-- Iteration 7: Long-term Memory Support

-- 1) memory_items (Main memory storage)
CREATE TABLE IF NOT EXISTS memory_items (
    memory_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID REFERENCES sessions(session_id) ON DELETE SET NULL,
    summary TEXT NOT NULL,
    content TEXT,
    salience DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    retention_score DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    decay_state JSONB DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'active', -- active, pruned, archived
    pinning BOOLEAN NOT NULL DEFAULT FALSE,
    ttl BIGINT, -- TTL in seconds
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2) memory_links (Provenance and association)
CREATE TABLE IF NOT EXISTS memory_links (
    link_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_memory_id UUID REFERENCES memory_items(memory_id) ON DELETE CASCADE,
    target_memory_id UUID REFERENCES memory_items(memory_id) ON DELETE CASCADE,
    link_type TEXT NOT NULL, -- sequential, causal, topical
    strength DOUBLE PRECISION DEFAULT 1.0,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_memory_items_session ON memory_items(session_id);
CREATE INDEX IF NOT EXISTS idx_memory_items_status ON memory_items(status);
CREATE INDEX IF NOT EXISTS idx_memory_links_source ON memory_links(source_memory_id);
CREATE INDEX IF NOT EXISTS idx_memory_links_target ON memory_links(target_memory_id);
