apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-secret
  namespace: rag-system
type: Opaque
stringData:
  url: "postgres://app:OpduDLozLwSGzGgnisFUeLyuSt4Q59alo5AtH0V7pdjGOtul9zu5c4waC3hhuCeZ@timescaledb-rw.timescaledb.svc.cluster.local:5432/app?sslmode=verify-full&sslrootcert=/etc/ssl/certs/ca-certificates.crt"
