// Code generated by ent, DO NOT EDIT.

package memoryitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the memoryitem type in the database.
	Label = "memory_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldSalience holds the string denoting the salience field in the database.
	FieldSalience = "salience"
	// FieldRetentionScore holds the string denoting the retention_score field in the database.
	FieldRetentionScore = "retention_score"
	// FieldDecayState holds the string denoting the decay_state field in the database.
	FieldDecayState = "decay_state"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPinning holds the string denoting the pinning field in the database.
	FieldPinning = "pinning"
	// FieldTTL holds the string denoting the ttl field in the database.
	FieldTTL = "ttl"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the memoryitem in the database.
	Table = "memory_items"
)

// Columns holds all SQL columns for memoryitem fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldSessionID,
	FieldUserID,
	FieldType,
	FieldSummary,
	FieldContent,
	FieldSalience,
	FieldRetentionScore,
	FieldDecayState,
	FieldStatus,
	FieldPinning,
	FieldTTL,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSalience holds the default value on creation for the "salience" field.
	DefaultSalience float64
	// DefaultRetentionScore holds the default value on creation for the "retention_score" field.
	DefaultRetentionScore float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultPinning holds the default value on creation for the "pinning" field.
	DefaultPinning bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the MemoryItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// BySalience orders the results by the salience field.
func BySalience(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSalience, opts...).ToFunc()
}

// ByRetentionScore orders the results by the retention_score field.
func ByRetentionScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetentionScore, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPinning orders the results by the pinning field.
func ByPinning(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPinning, opts...).ToFunc()
}

// ByTTL orders the results by the ttl field.
func ByTTL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTTL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
