// Code generated by ent, DO NOT EDIT.

package memoryitem

import (
	"app-builds/common/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldProjectID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldSessionID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldUserID, v))
}

// MemoryType applies equality check predicate on the "memory_type" field. It's identical to MemoryTypeEQ.
func MemoryType(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldMemoryType, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldSummary, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldContent, v))
}

// Salience applies equality check predicate on the "salience" field. It's identical to SalienceEQ.
func Salience(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldSalience, v))
}

// RetentionScore applies equality check predicate on the "retention_score" field. It's identical to RetentionScoreEQ.
func RetentionScore(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldRetentionScore, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldStatus, v))
}

// Pinned applies equality check predicate on the "pinned" field. It's identical to PinnedEQ.
func Pinned(v bool) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldPinned, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDIsNil applies the IsNil predicate on the "project_id" field.
func ProjectIDIsNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIsNull(FieldProjectID))
}

// ProjectIDNotNil applies the NotNil predicate on the "project_id" field.
func ProjectIDNotNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotNull(FieldProjectID))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...int64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDIsNil applies the IsNil predicate on the "session_id" field.
func SessionIDIsNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIsNull(FieldSessionID))
}

// SessionIDNotNil applies the NotNil predicate on the "session_id" field.
func SessionIDNotNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotNull(FieldSessionID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotNull(FieldUserID))
}

// MemoryTypeEQ applies the EQ predicate on the "memory_type" field.
func MemoryTypeEQ(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldMemoryType, v))
}

// MemoryTypeNEQ applies the NEQ predicate on the "memory_type" field.
func MemoryTypeNEQ(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldMemoryType, v))
}

// MemoryTypeIn applies the In predicate on the "memory_type" field.
func MemoryTypeIn(vs ...string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldMemoryType, vs...))
}

// MemoryTypeNotIn applies the NotIn predicate on the "memory_type" field.
func MemoryTypeNotIn(vs ...string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldMemoryType, vs...))
}

// MemoryTypeGT applies the GT predicate on the "memory_type" field.
func MemoryTypeGT(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldMemoryType, v))
}

// MemoryTypeGTE applies the GTE predicate on the "memory_type" field.
func MemoryTypeGTE(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldMemoryType, v))
}

// MemoryTypeLT applies the LT predicate on the "memory_type" field.
func MemoryTypeLT(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldMemoryType, v))
}

// MemoryTypeLTE applies the LTE predicate on the "memory_type" field.
func MemoryTypeLTE(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldMemoryType, v))
}

// MemoryTypeContains applies the Contains predicate on the "memory_type" field.
func MemoryTypeContains(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldContains(FieldMemoryType, v))
}

// MemoryTypeHasPrefix applies the HasPrefix predicate on the "memory_type" field.
func MemoryTypeHasPrefix(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldHasPrefix(FieldMemoryType, v))
}

// MemoryTypeHasSuffix applies the HasSuffix predicate on the "memory_type" field.
func MemoryTypeHasSuffix(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldHasSuffix(FieldMemoryType, v))
}

// MemoryTypeEqualFold applies the EqualFold predicate on the "memory_type" field.
func MemoryTypeEqualFold(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEqualFold(FieldMemoryType, v))
}

// MemoryTypeContainsFold applies the ContainsFold predicate on the "memory_type" field.
func MemoryTypeContainsFold(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldContainsFold(FieldMemoryType, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldContainsFold(FieldSummary, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldContainsFold(FieldContent, v))
}

// SalienceEQ applies the EQ predicate on the "salience" field.
func SalienceEQ(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldSalience, v))
}

// SalienceNEQ applies the NEQ predicate on the "salience" field.
func SalienceNEQ(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldSalience, v))
}

// SalienceIn applies the In predicate on the "salience" field.
func SalienceIn(vs ...float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldSalience, vs...))
}

// SalienceNotIn applies the NotIn predicate on the "salience" field.
func SalienceNotIn(vs ...float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldSalience, vs...))
}

// SalienceGT applies the GT predicate on the "salience" field.
func SalienceGT(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldSalience, v))
}

// SalienceGTE applies the GTE predicate on the "salience" field.
func SalienceGTE(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldSalience, v))
}

// SalienceLT applies the LT predicate on the "salience" field.
func SalienceLT(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldSalience, v))
}

// SalienceLTE applies the LTE predicate on the "salience" field.
func SalienceLTE(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldSalience, v))
}

// RetentionScoreEQ applies the EQ predicate on the "retention_score" field.
func RetentionScoreEQ(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldRetentionScore, v))
}

// RetentionScoreNEQ applies the NEQ predicate on the "retention_score" field.
func RetentionScoreNEQ(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldRetentionScore, v))
}

// RetentionScoreIn applies the In predicate on the "retention_score" field.
func RetentionScoreIn(vs ...float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldRetentionScore, vs...))
}

// RetentionScoreNotIn applies the NotIn predicate on the "retention_score" field.
func RetentionScoreNotIn(vs ...float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldRetentionScore, vs...))
}

// RetentionScoreGT applies the GT predicate on the "retention_score" field.
func RetentionScoreGT(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldRetentionScore, v))
}

// RetentionScoreGTE applies the GTE predicate on the "retention_score" field.
func RetentionScoreGTE(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldRetentionScore, v))
}

// RetentionScoreLT applies the LT predicate on the "retention_score" field.
func RetentionScoreLT(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldRetentionScore, v))
}

// RetentionScoreLTE applies the LTE predicate on the "retention_score" field.
func RetentionScoreLTE(v float64) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldRetentionScore, v))
}

// DecayStateIsNil applies the IsNil predicate on the "decay_state" field.
func DecayStateIsNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIsNull(FieldDecayState))
}

// DecayStateNotNil applies the NotNil predicate on the "decay_state" field.
func DecayStateNotNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotNull(FieldDecayState))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldContainsFold(FieldStatus, v))
}

// PinnedEQ applies the EQ predicate on the "pinned" field.
func PinnedEQ(v bool) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldPinned, v))
}

// PinnedNEQ applies the NEQ predicate on the "pinned" field.
func PinnedNEQ(v bool) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldPinned, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotNull(FieldExpiresAt))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MemoryItem {
	return predicate.MemoryItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.MemoryItem {
	return predicate.MemoryItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.Session) predicate.MemoryItem {
	return predicate.MemoryItem(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLinks applies the HasEdge predicate on the "links" edge.
func HasLinks() predicate.MemoryItem {
	return predicate.MemoryItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LinksTable, LinksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLinksWith applies the HasEdge predicate on the "links" edge with a given conditions (other predicates).
func HasLinksWith(preds ...predicate.MemoryLink) predicate.MemoryItem {
	return predicate.MemoryItem(func(s *sql.Selector) {
		step := newLinksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.MemoryItem {
	return predicate.MemoryItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.MemoryEvent) predicate.MemoryItem {
	return predicate.MemoryItem(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemoryItem) predicate.MemoryItem {
	return predicate.MemoryItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemoryItem) predicate.MemoryItem {
	return predicate.MemoryItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemoryItem) predicate.MemoryItem {
	return predicate.MemoryItem(sql.NotPredicates(p))
}
