apiVersion: batch/v1
kind: Job
metadata:
  name: object-store-list
  namespace: rag-system
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: OnFailure
      enableServiceLinks: false
      containers:
      - name: manager
        image: registry.container-registry.svc.cluster.local:5000/object-store-mgr:2.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: rag-codebase-bucket
              key: BUCKET_HOST
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: rag-codebase-bucket
              key: BUCKET_NAME
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: rag-codebase-bucket
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rag-codebase-bucket
              key: AWS_SECRET_ACCESS_KEY
        - name: SSL_CERT_FILE
          value: "/etc/ssl/certs/ca-certificates.crt"
        volumeMounts:
        - name: registry-ca
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca.crt
      volumes:
      - name: registry-ca
        configMap:
          name: registry-ca-cm
