apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-store-mgr
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-store-mgr
  template:
    metadata:
      labels:
        app: object-store-mgr
    spec:
      nodeSelector:
        role: storage-node
      enableServiceLinks: false
      containers:
      - name: manager
        image: registry.container-registry.svc.cluster.local:5000/object-store-mgr:__VERSION__
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: rag-codebase-bucket
              key: BUCKET_HOST
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: rag-codebase-bucket
              key: BUCKET_NAME
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: rag-codebase-bucket
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rag-codebase-bucket
              key: AWS_SECRET_ACCESS_KEY
        - name: TLS_CERT
          value: "/etc/ssl/certs/tls.crt"
        - name: TLS_KEY
          value: "/etc/ssl/certs/tls.key"
        - name: SSL_CERT_FILE
          value: "/etc/ssl/certs/ca-certificates.crt"
        volumeMounts:
        - name: registry-ca
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca.crt
        - name: service-tls
          mountPath: /etc/ssl/certs/tls.crt
          subPath: tls.crt
        - name: service-tls
          mountPath: /etc/ssl/certs/tls.key
          subPath: tls.key
      volumes:
      - name: registry-ca
        configMap:
          name: registry-ca-cm
      - name: service-tls
        secret:
          secretName: object-store-mgr-tls
