apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-store-mgr
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-store-mgr
  template:
    metadata:
      labels:
        app: object-store-mgr
    spec:
      nodeSelector:
        role: storage-node
      enableServiceLinks: false
      containers:
      - name: manager
        image: registry.container-registry.svc.cluster.local:5000/object-store-mgr:1.5.10
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: rag-codebase-bucket
              key: BUCKET_HOST
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: rag-codebase-bucket
              key: BUCKET_NAME
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: rag-codebase-bucket
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rag-codebase-bucket
              key: AWS_SECRET_ACCESS_KEY
