// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/actionidentifier"
	"app-builds/common/ent/actiontype"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ActionIdentifier is the model entity for the ActionIdentifier schema.
type ActionIdentifier struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Identifier holds the value of the "identifier" field.
	Identifier string `json:"identifier,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActionIdentifierQuery when eager-loading is set.
	Edges                   ActionIdentifierEdges `json:"edges"`
	action_type_identifiers *int64
	selectValues            sql.SelectValues
}

// ActionIdentifierEdges holds the relations/edges for other nodes in the graph.
type ActionIdentifierEdges struct {
	// ActionType holds the value of the action_type edge.
	ActionType *ActionType `json:"action_type,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ActionTypeOrErr returns the ActionType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActionIdentifierEdges) ActionTypeOrErr() (*ActionType, error) {
	if e.ActionType != nil {
		return e.ActionType, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: actiontype.Label}
	}
	return nil, &NotLoadedError{edge: "action_type"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ActionIdentifier) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case actionidentifier.FieldID:
			values[i] = new(sql.NullInt64)
		case actionidentifier.FieldIdentifier:
			values[i] = new(sql.NullString)
		case actionidentifier.ForeignKeys[0]: // action_type_identifiers
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ActionIdentifier fields.
func (_m *ActionIdentifier) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case actionidentifier.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case actionidentifier.FieldIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identifier", values[i])
			} else if value.Valid {
				_m.Identifier = value.String
			}
		case actionidentifier.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field action_type_identifiers", value)
			} else if value.Valid {
				_m.action_type_identifiers = new(int64)
				*_m.action_type_identifiers = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ActionIdentifier.
// This includes values selected through modifiers, order, etc.
func (_m *ActionIdentifier) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryActionType queries the "action_type" edge of the ActionIdentifier entity.
func (_m *ActionIdentifier) QueryActionType() *ActionTypeQuery {
	return NewActionIdentifierClient(_m.config).QueryActionType(_m)
}

// Update returns a builder for updating this ActionIdentifier.
// Note that you need to call ActionIdentifier.Unwrap() before calling this method if this ActionIdentifier
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ActionIdentifier) Update() *ActionIdentifierUpdateOne {
	return NewActionIdentifierClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ActionIdentifier entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ActionIdentifier) Unwrap() *ActionIdentifier {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ActionIdentifier is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ActionIdentifier) String() string {
	var builder strings.Builder
	builder.WriteString("ActionIdentifier(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("identifier=")
	builder.WriteString(_m.Identifier)
	builder.WriteByte(')')
	return builder.String()
}

// ActionIdentifiers is a parsable slice of ActionIdentifier.
type ActionIdentifiers []*ActionIdentifier
