// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/actionidentifier"
	"app-builds/common/ent/actiontype"
	"app-builds/common/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ActionTypeUpdate is the builder for updating ActionType entities.
type ActionTypeUpdate struct {
	config
	hooks    []Hook
	mutation *ActionTypeMutation
}

// Where appends a list predicates to the ActionTypeUpdate builder.
func (_u *ActionTypeUpdate) Where(ps ...predicate.ActionType) *ActionTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ActionTypeUpdate) SetName(v string) *ActionTypeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActionTypeUpdate) SetNillableName(v *string) *ActionTypeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ActionTypeUpdate) SetDescription(v string) *ActionTypeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ActionTypeUpdate) SetNillableDescription(v *string) *ActionTypeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ActionTypeUpdate) ClearDescription() *ActionTypeUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// AddIdentifierIDs adds the "identifiers" edge to the ActionIdentifier entity by IDs.
func (_u *ActionTypeUpdate) AddIdentifierIDs(ids ...int64) *ActionTypeUpdate {
	_u.mutation.AddIdentifierIDs(ids...)
	return _u
}

// AddIdentifiers adds the "identifiers" edges to the ActionIdentifier entity.
func (_u *ActionTypeUpdate) AddIdentifiers(v ...*ActionIdentifier) *ActionTypeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIdentifierIDs(ids...)
}

// Mutation returns the ActionTypeMutation object of the builder.
func (_u *ActionTypeUpdate) Mutation() *ActionTypeMutation {
	return _u.mutation
}

// ClearIdentifiers clears all "identifiers" edges to the ActionIdentifier entity.
func (_u *ActionTypeUpdate) ClearIdentifiers() *ActionTypeUpdate {
	_u.mutation.ClearIdentifiers()
	return _u
}

// RemoveIdentifierIDs removes the "identifiers" edge to ActionIdentifier entities by IDs.
func (_u *ActionTypeUpdate) RemoveIdentifierIDs(ids ...int64) *ActionTypeUpdate {
	_u.mutation.RemoveIdentifierIDs(ids...)
	return _u
}

// RemoveIdentifiers removes "identifiers" edges to ActionIdentifier entities.
func (_u *ActionTypeUpdate) RemoveIdentifiers(v ...*ActionIdentifier) *ActionTypeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIdentifierIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActionTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActionTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ActionTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(actiontype.Table, actiontype.Columns, sqlgraph.NewFieldSpec(actiontype.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(actiontype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(actiontype.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(actiontype.FieldDescription, field.TypeString)
	}
	if _u.mutation.IdentifiersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   actiontype.IdentifiersTable,
			Columns: []string{actiontype.IdentifiersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionidentifier.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIdentifiersIDs(); len(nodes) > 0 && !_u.mutation.IdentifiersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   actiontype.IdentifiersTable,
			Columns: []string{actiontype.IdentifiersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionidentifier.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IdentifiersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   actiontype.IdentifiersTable,
			Columns: []string{actiontype.IdentifiersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionidentifier.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actiontype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActionTypeUpdateOne is the builder for updating a single ActionType entity.
type ActionTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActionTypeMutation
}

// SetName sets the "name" field.
func (_u *ActionTypeUpdateOne) SetName(v string) *ActionTypeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActionTypeUpdateOne) SetNillableName(v *string) *ActionTypeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ActionTypeUpdateOne) SetDescription(v string) *ActionTypeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ActionTypeUpdateOne) SetNillableDescription(v *string) *ActionTypeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ActionTypeUpdateOne) ClearDescription() *ActionTypeUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// AddIdentifierIDs adds the "identifiers" edge to the ActionIdentifier entity by IDs.
func (_u *ActionTypeUpdateOne) AddIdentifierIDs(ids ...int64) *ActionTypeUpdateOne {
	_u.mutation.AddIdentifierIDs(ids...)
	return _u
}

// AddIdentifiers adds the "identifiers" edges to the ActionIdentifier entity.
func (_u *ActionTypeUpdateOne) AddIdentifiers(v ...*ActionIdentifier) *ActionTypeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIdentifierIDs(ids...)
}

// Mutation returns the ActionTypeMutation object of the builder.
func (_u *ActionTypeUpdateOne) Mutation() *ActionTypeMutation {
	return _u.mutation
}

// ClearIdentifiers clears all "identifiers" edges to the ActionIdentifier entity.
func (_u *ActionTypeUpdateOne) ClearIdentifiers() *ActionTypeUpdateOne {
	_u.mutation.ClearIdentifiers()
	return _u
}

// RemoveIdentifierIDs removes the "identifiers" edge to ActionIdentifier entities by IDs.
func (_u *ActionTypeUpdateOne) RemoveIdentifierIDs(ids ...int64) *ActionTypeUpdateOne {
	_u.mutation.RemoveIdentifierIDs(ids...)
	return _u
}

// RemoveIdentifiers removes "identifiers" edges to ActionIdentifier entities.
func (_u *ActionTypeUpdateOne) RemoveIdentifiers(v ...*ActionIdentifier) *ActionTypeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIdentifierIDs(ids...)
}

// Where appends a list predicates to the ActionTypeUpdate builder.
func (_u *ActionTypeUpdateOne) Where(ps ...predicate.ActionType) *ActionTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActionTypeUpdateOne) Select(field string, fields ...string) *ActionTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ActionType entity.
func (_u *ActionTypeUpdateOne) Save(ctx context.Context) (*ActionType, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionTypeUpdateOne) SaveX(ctx context.Context) *ActionType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActionTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ActionTypeUpdateOne) sqlSave(ctx context.Context) (_node *ActionType, err error) {
	_spec := sqlgraph.NewUpdateSpec(actiontype.Table, actiontype.Columns, sqlgraph.NewFieldSpec(actiontype.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActionType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, actiontype.FieldID)
		for _, f := range fields {
			if !actiontype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != actiontype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(actiontype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(actiontype.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(actiontype.FieldDescription, field.TypeString)
	}
	if _u.mutation.IdentifiersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   actiontype.IdentifiersTable,
			Columns: []string{actiontype.IdentifiersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionidentifier.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIdentifiersIDs(); len(nodes) > 0 && !_u.mutation.IdentifiersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   actiontype.IdentifiersTable,
			Columns: []string{actiontype.IdentifiersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionidentifier.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IdentifiersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   actiontype.IdentifiersTable,
			Columns: []string{actiontype.IdentifiersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionidentifier.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ActionType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actiontype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
