// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/behavioralrule"
	"app-builds/common/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BehavioralRuleDelete is the builder for deleting a BehavioralRule entity.
type BehavioralRuleDelete struct {
	config
	hooks    []Hook
	mutation *BehavioralRuleMutation
}

// Where appends a list predicates to the BehavioralRuleDelete builder.
func (_d *BehavioralRuleDelete) Where(ps ...predicate.BehavioralRule) *BehavioralRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BehavioralRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BehavioralRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BehavioralRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(behavioralrule.Table, sqlgraph.NewFieldSpec(behavioralrule.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BehavioralRuleDeleteOne is the builder for deleting a single BehavioralRule entity.
type BehavioralRuleDeleteOne struct {
	_d *BehavioralRuleDelete
}

// Where appends a list predicates to the BehavioralRuleDelete builder.
func (_d *BehavioralRuleDeleteOne) Where(ps ...predicate.BehavioralRule) *BehavioralRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BehavioralRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{behavioralrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BehavioralRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
