// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/behaviorallog"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BehavioralLog is the model entity for the BehavioralLog schema.
type BehavioralLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// PromptID holds the value of the "prompt_id" field.
	PromptID string `json:"prompt_id,omitempty"`
	// RuleID holds the value of the "rule_id" field.
	RuleID int64 `json:"rule_id,omitempty"`
	// ActionType holds the value of the "action_type" field.
	ActionType behaviorallog.ActionType `json:"action_type,omitempty"`
	// AppliedAt holds the value of the "applied_at" field.
	AppliedAt time.Time `json:"applied_at,omitempty"`
	// Context holds the value of the "context" field.
	Context      map[string]interface{} `json:"context,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BehavioralLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case behaviorallog.FieldContext:
			values[i] = new([]byte)
		case behaviorallog.FieldID, behaviorallog.FieldRuleID:
			values[i] = new(sql.NullInt64)
		case behaviorallog.FieldPromptID, behaviorallog.FieldActionType:
			values[i] = new(sql.NullString)
		case behaviorallog.FieldAppliedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BehavioralLog fields.
func (_m *BehavioralLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case behaviorallog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case behaviorallog.FieldPromptID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_id", values[i])
			} else if value.Valid {
				_m.PromptID = value.String
			}
		case behaviorallog.FieldRuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value.Valid {
				_m.RuleID = value.Int64
			}
		case behaviorallog.FieldActionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_type", values[i])
			} else if value.Valid {
				_m.ActionType = behaviorallog.ActionType(value.String)
			}
		case behaviorallog.FieldAppliedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field applied_at", values[i])
			} else if value.Valid {
				_m.AppliedAt = value.Time
			}
		case behaviorallog.FieldContext:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field context", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Context); err != nil {
					return fmt.Errorf("unmarshal field context: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BehavioralLog.
// This includes values selected through modifiers, order, etc.
func (_m *BehavioralLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BehavioralLog.
// Note that you need to call BehavioralLog.Unwrap() before calling this method if this BehavioralLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BehavioralLog) Update() *BehavioralLogUpdateOne {
	return NewBehavioralLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BehavioralLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BehavioralLog) Unwrap() *BehavioralLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BehavioralLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BehavioralLog) String() string {
	var builder strings.Builder
	builder.WriteString("BehavioralLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("prompt_id=")
	builder.WriteString(_m.PromptID)
	builder.WriteString(", ")
	builder.WriteString("rule_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RuleID))
	builder.WriteString(", ")
	builder.WriteString("action_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionType))
	builder.WriteString(", ")
	builder.WriteString("applied_at=")
	builder.WriteString(_m.AppliedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("context=")
	builder.WriteString(fmt.Sprintf("%v", _m.Context))
	builder.WriteByte(')')
	return builder.String()
}

// BehavioralLogs is a parsable slice of BehavioralLog.
type BehavioralLogs []*BehavioralLog
