// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/buildjournal"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BuildJournalCreate is the builder for creating a BuildJournal entity.
type BuildJournalCreate struct {
	config
	mutation *BuildJournalMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetServiceName sets the "service_name" field.
func (_c *BuildJournalCreate) SetServiceName(v string) *BuildJournalCreate {
	_c.mutation.SetServiceName(v)
	return _c
}

// SetLastHash sets the "last_hash" field.
func (_c *BuildJournalCreate) SetLastHash(v string) *BuildJournalCreate {
	_c.mutation.SetLastHash(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BuildJournalCreate) SetUpdatedAt(v time.Time) *BuildJournalCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BuildJournalCreate) SetNillableUpdatedAt(v *time.Time) *BuildJournalCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the BuildJournalMutation object of the builder.
func (_c *BuildJournalCreate) Mutation() *BuildJournalMutation {
	return _c.mutation
}

// Save creates the BuildJournal in the database.
func (_c *BuildJournalCreate) Save(ctx context.Context) (*BuildJournal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BuildJournalCreate) SaveX(ctx context.Context) *BuildJournal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BuildJournalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BuildJournalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BuildJournalCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := buildjournal.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BuildJournalCreate) check() error {
	if _, ok := _c.mutation.ServiceName(); !ok {
		return &ValidationError{Name: "service_name", err: errors.New(`ent: missing required field "BuildJournal.service_name"`)}
	}
	if v, ok := _c.mutation.ServiceName(); ok {
		if err := buildjournal.ServiceNameValidator(v); err != nil {
			return &ValidationError{Name: "service_name", err: fmt.Errorf(`ent: validator failed for field "BuildJournal.service_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastHash(); !ok {
		return &ValidationError{Name: "last_hash", err: errors.New(`ent: missing required field "BuildJournal.last_hash"`)}
	}
	if v, ok := _c.mutation.LastHash(); ok {
		if err := buildjournal.LastHashValidator(v); err != nil {
			return &ValidationError{Name: "last_hash", err: fmt.Errorf(`ent: validator failed for field "BuildJournal.last_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BuildJournal.updated_at"`)}
	}
	return nil
}

func (_c *BuildJournalCreate) sqlSave(ctx context.Context) (*BuildJournal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BuildJournalCreate) createSpec() (*BuildJournal, *sqlgraph.CreateSpec) {
	var (
		_node = &BuildJournal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(buildjournal.Table, sqlgraph.NewFieldSpec(buildjournal.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ServiceName(); ok {
		_spec.SetField(buildjournal.FieldServiceName, field.TypeString, value)
		_node.ServiceName = value
	}
	if value, ok := _c.mutation.LastHash(); ok {
		_spec.SetField(buildjournal.FieldLastHash, field.TypeString, value)
		_node.LastHash = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(buildjournal.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BuildJournal.Create().
//		SetServiceName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BuildJournalUpsert) {
//			SetServiceName(v+v).
//		}).
//		Exec(ctx)
func (_c *BuildJournalCreate) OnConflict(opts ...sql.ConflictOption) *BuildJournalUpsertOne {
	_c.conflict = opts
	return &BuildJournalUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BuildJournal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BuildJournalCreate) OnConflictColumns(columns ...string) *BuildJournalUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BuildJournalUpsertOne{
		create: _c,
	}
}

type (
	// BuildJournalUpsertOne is the builder for "upsert"-ing
	//  one BuildJournal node.
	BuildJournalUpsertOne struct {
		create *BuildJournalCreate
	}

	// BuildJournalUpsert is the "OnConflict" setter.
	BuildJournalUpsert struct {
		*sql.UpdateSet
	}
)

// SetServiceName sets the "service_name" field.
func (u *BuildJournalUpsert) SetServiceName(v string) *BuildJournalUpsert {
	u.Set(buildjournal.FieldServiceName, v)
	return u
}

// UpdateServiceName sets the "service_name" field to the value that was provided on create.
func (u *BuildJournalUpsert) UpdateServiceName() *BuildJournalUpsert {
	u.SetExcluded(buildjournal.FieldServiceName)
	return u
}

// SetLastHash sets the "last_hash" field.
func (u *BuildJournalUpsert) SetLastHash(v string) *BuildJournalUpsert {
	u.Set(buildjournal.FieldLastHash, v)
	return u
}

// UpdateLastHash sets the "last_hash" field to the value that was provided on create.
func (u *BuildJournalUpsert) UpdateLastHash() *BuildJournalUpsert {
	u.SetExcluded(buildjournal.FieldLastHash)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BuildJournalUpsert) SetUpdatedAt(v time.Time) *BuildJournalUpsert {
	u.Set(buildjournal.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BuildJournalUpsert) UpdateUpdatedAt() *BuildJournalUpsert {
	u.SetExcluded(buildjournal.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BuildJournal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BuildJournalUpsertOne) UpdateNewValues() *BuildJournalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BuildJournal.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BuildJournalUpsertOne) Ignore() *BuildJournalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BuildJournalUpsertOne) DoNothing() *BuildJournalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BuildJournalCreate.OnConflict
// documentation for more info.
func (u *BuildJournalUpsertOne) Update(set func(*BuildJournalUpsert)) *BuildJournalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BuildJournalUpsert{UpdateSet: update})
	}))
	return u
}

// SetServiceName sets the "service_name" field.
func (u *BuildJournalUpsertOne) SetServiceName(v string) *BuildJournalUpsertOne {
	return u.Update(func(s *BuildJournalUpsert) {
		s.SetServiceName(v)
	})
}

// UpdateServiceName sets the "service_name" field to the value that was provided on create.
func (u *BuildJournalUpsertOne) UpdateServiceName() *BuildJournalUpsertOne {
	return u.Update(func(s *BuildJournalUpsert) {
		s.UpdateServiceName()
	})
}

// SetLastHash sets the "last_hash" field.
func (u *BuildJournalUpsertOne) SetLastHash(v string) *BuildJournalUpsertOne {
	return u.Update(func(s *BuildJournalUpsert) {
		s.SetLastHash(v)
	})
}

// UpdateLastHash sets the "last_hash" field to the value that was provided on create.
func (u *BuildJournalUpsertOne) UpdateLastHash() *BuildJournalUpsertOne {
	return u.Update(func(s *BuildJournalUpsert) {
		s.UpdateLastHash()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BuildJournalUpsertOne) SetUpdatedAt(v time.Time) *BuildJournalUpsertOne {
	return u.Update(func(s *BuildJournalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BuildJournalUpsertOne) UpdateUpdatedAt() *BuildJournalUpsertOne {
	return u.Update(func(s *BuildJournalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BuildJournalUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BuildJournalCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BuildJournalUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BuildJournalUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BuildJournalUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BuildJournalCreateBulk is the builder for creating many BuildJournal entities in bulk.
type BuildJournalCreateBulk struct {
	config
	err      error
	builders []*BuildJournalCreate
	conflict []sql.ConflictOption
}

// Save creates the BuildJournal entities in the database.
func (_c *BuildJournalCreateBulk) Save(ctx context.Context) ([]*BuildJournal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BuildJournal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BuildJournalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BuildJournalCreateBulk) SaveX(ctx context.Context) []*BuildJournal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BuildJournalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BuildJournalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BuildJournal.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BuildJournalUpsert) {
//			SetServiceName(v+v).
//		}).
//		Exec(ctx)
func (_c *BuildJournalCreateBulk) OnConflict(opts ...sql.ConflictOption) *BuildJournalUpsertBulk {
	_c.conflict = opts
	return &BuildJournalUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BuildJournal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BuildJournalCreateBulk) OnConflictColumns(columns ...string) *BuildJournalUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BuildJournalUpsertBulk{
		create: _c,
	}
}

// BuildJournalUpsertBulk is the builder for "upsert"-ing
// a bulk of BuildJournal nodes.
type BuildJournalUpsertBulk struct {
	create *BuildJournalCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BuildJournal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BuildJournalUpsertBulk) UpdateNewValues() *BuildJournalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BuildJournal.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BuildJournalUpsertBulk) Ignore() *BuildJournalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BuildJournalUpsertBulk) DoNothing() *BuildJournalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BuildJournalCreateBulk.OnConflict
// documentation for more info.
func (u *BuildJournalUpsertBulk) Update(set func(*BuildJournalUpsert)) *BuildJournalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BuildJournalUpsert{UpdateSet: update})
	}))
	return u
}

// SetServiceName sets the "service_name" field.
func (u *BuildJournalUpsertBulk) SetServiceName(v string) *BuildJournalUpsertBulk {
	return u.Update(func(s *BuildJournalUpsert) {
		s.SetServiceName(v)
	})
}

// UpdateServiceName sets the "service_name" field to the value that was provided on create.
func (u *BuildJournalUpsertBulk) UpdateServiceName() *BuildJournalUpsertBulk {
	return u.Update(func(s *BuildJournalUpsert) {
		s.UpdateServiceName()
	})
}

// SetLastHash sets the "last_hash" field.
func (u *BuildJournalUpsertBulk) SetLastHash(v string) *BuildJournalUpsertBulk {
	return u.Update(func(s *BuildJournalUpsert) {
		s.SetLastHash(v)
	})
}

// UpdateLastHash sets the "last_hash" field to the value that was provided on create.
func (u *BuildJournalUpsertBulk) UpdateLastHash() *BuildJournalUpsertBulk {
	return u.Update(func(s *BuildJournalUpsert) {
		s.UpdateLastHash()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BuildJournalUpsertBulk) SetUpdatedAt(v time.Time) *BuildJournalUpsertBulk {
	return u.Update(func(s *BuildJournalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BuildJournalUpsertBulk) UpdateUpdatedAt() *BuildJournalUpsertBulk {
	return u.Update(func(s *BuildJournalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BuildJournalUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BuildJournalCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BuildJournalCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BuildJournalUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
