// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/buildversion"
	"app-builds/common/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BuildVersionDelete is the builder for deleting a BuildVersion entity.
type BuildVersionDelete struct {
	config
	hooks    []Hook
	mutation *BuildVersionMutation
}

// Where appends a list predicates to the BuildVersionDelete builder.
func (_d *BuildVersionDelete) Where(ps ...predicate.BuildVersion) *BuildVersionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BuildVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BuildVersionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BuildVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(buildversion.Table, sqlgraph.NewFieldSpec(buildversion.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BuildVersionDeleteOne is the builder for deleting a single BuildVersion entity.
type BuildVersionDeleteOne struct {
	_d *BuildVersionDelete
}

// Where appends a list predicates to the BuildVersionDelete builder.
func (_d *BuildVersionDeleteOne) Where(ps ...predicate.BuildVersion) *BuildVersionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BuildVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{buildversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BuildVersionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
