// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/buildlock"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BuildLockCreate is the builder for creating a BuildLock entity.
type BuildLockCreate struct {
	config
	mutation *BuildLockMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetServiceName sets the "service_name" field.
func (_c *BuildLockCreate) SetServiceName(v string) *BuildLockCreate {
	_c.mutation.SetServiceName(v)
	return _c
}

// SetLockOwner sets the "lock_owner" field.
func (_c *BuildLockCreate) SetLockOwner(v string) *BuildLockCreate {
	_c.mutation.SetLockOwner(v)
	return _c
}

// SetLockPid sets the "lock_pid" field.
func (_c *BuildLockCreate) SetLockPid(v int) *BuildLockCreate {
	_c.mutation.SetLockPid(v)
	return _c
}

// SetLockHost sets the "lock_host" field.
func (_c *BuildLockCreate) SetLockHost(v string) *BuildLockCreate {
	_c.mutation.SetLockHost(v)
	return _c
}

// SetAcquiredAt sets the "acquired_at" field.
func (_c *BuildLockCreate) SetAcquiredAt(v time.Time) *BuildLockCreate {
	_c.mutation.SetAcquiredAt(v)
	return _c
}

// SetNillableAcquiredAt sets the "acquired_at" field if the given value is not nil.
func (_c *BuildLockCreate) SetNillableAcquiredAt(v *time.Time) *BuildLockCreate {
	if v != nil {
		_c.SetAcquiredAt(*v)
	}
	return _c
}

// SetHeartbeat sets the "heartbeat" field.
func (_c *BuildLockCreate) SetHeartbeat(v time.Time) *BuildLockCreate {
	_c.mutation.SetHeartbeat(v)
	return _c
}

// SetNillableHeartbeat sets the "heartbeat" field if the given value is not nil.
func (_c *BuildLockCreate) SetNillableHeartbeat(v *time.Time) *BuildLockCreate {
	if v != nil {
		_c.SetHeartbeat(*v)
	}
	return _c
}

// Mutation returns the BuildLockMutation object of the builder.
func (_c *BuildLockCreate) Mutation() *BuildLockMutation {
	return _c.mutation
}

// Save creates the BuildLock in the database.
func (_c *BuildLockCreate) Save(ctx context.Context) (*BuildLock, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BuildLockCreate) SaveX(ctx context.Context) *BuildLock {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BuildLockCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BuildLockCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BuildLockCreate) defaults() {
	if _, ok := _c.mutation.AcquiredAt(); !ok {
		v := buildlock.DefaultAcquiredAt()
		_c.mutation.SetAcquiredAt(v)
	}
	if _, ok := _c.mutation.Heartbeat(); !ok {
		v := buildlock.DefaultHeartbeat()
		_c.mutation.SetHeartbeat(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BuildLockCreate) check() error {
	if _, ok := _c.mutation.ServiceName(); !ok {
		return &ValidationError{Name: "service_name", err: errors.New(`ent: missing required field "BuildLock.service_name"`)}
	}
	if v, ok := _c.mutation.ServiceName(); ok {
		if err := buildlock.ServiceNameValidator(v); err != nil {
			return &ValidationError{Name: "service_name", err: fmt.Errorf(`ent: validator failed for field "BuildLock.service_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LockOwner(); !ok {
		return &ValidationError{Name: "lock_owner", err: errors.New(`ent: missing required field "BuildLock.lock_owner"`)}
	}
	if v, ok := _c.mutation.LockOwner(); ok {
		if err := buildlock.LockOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lock_owner", err: fmt.Errorf(`ent: validator failed for field "BuildLock.lock_owner": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LockPid(); !ok {
		return &ValidationError{Name: "lock_pid", err: errors.New(`ent: missing required field "BuildLock.lock_pid"`)}
	}
	if _, ok := _c.mutation.LockHost(); !ok {
		return &ValidationError{Name: "lock_host", err: errors.New(`ent: missing required field "BuildLock.lock_host"`)}
	}
	if _, ok := _c.mutation.AcquiredAt(); !ok {
		return &ValidationError{Name: "acquired_at", err: errors.New(`ent: missing required field "BuildLock.acquired_at"`)}
	}
	if _, ok := _c.mutation.Heartbeat(); !ok {
		return &ValidationError{Name: "heartbeat", err: errors.New(`ent: missing required field "BuildLock.heartbeat"`)}
	}
	return nil
}

func (_c *BuildLockCreate) sqlSave(ctx context.Context) (*BuildLock, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BuildLockCreate) createSpec() (*BuildLock, *sqlgraph.CreateSpec) {
	var (
		_node = &BuildLock{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(buildlock.Table, sqlgraph.NewFieldSpec(buildlock.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ServiceName(); ok {
		_spec.SetField(buildlock.FieldServiceName, field.TypeString, value)
		_node.ServiceName = value
	}
	if value, ok := _c.mutation.LockOwner(); ok {
		_spec.SetField(buildlock.FieldLockOwner, field.TypeString, value)
		_node.LockOwner = value
	}
	if value, ok := _c.mutation.LockPid(); ok {
		_spec.SetField(buildlock.FieldLockPid, field.TypeInt, value)
		_node.LockPid = value
	}
	if value, ok := _c.mutation.LockHost(); ok {
		_spec.SetField(buildlock.FieldLockHost, field.TypeString, value)
		_node.LockHost = value
	}
	if value, ok := _c.mutation.AcquiredAt(); ok {
		_spec.SetField(buildlock.FieldAcquiredAt, field.TypeTime, value)
		_node.AcquiredAt = value
	}
	if value, ok := _c.mutation.Heartbeat(); ok {
		_spec.SetField(buildlock.FieldHeartbeat, field.TypeTime, value)
		_node.Heartbeat = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BuildLock.Create().
//		SetServiceName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BuildLockUpsert) {
//			SetServiceName(v+v).
//		}).
//		Exec(ctx)
func (_c *BuildLockCreate) OnConflict(opts ...sql.ConflictOption) *BuildLockUpsertOne {
	_c.conflict = opts
	return &BuildLockUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BuildLock.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BuildLockCreate) OnConflictColumns(columns ...string) *BuildLockUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BuildLockUpsertOne{
		create: _c,
	}
}

type (
	// BuildLockUpsertOne is the builder for "upsert"-ing
	//  one BuildLock node.
	BuildLockUpsertOne struct {
		create *BuildLockCreate
	}

	// BuildLockUpsert is the "OnConflict" setter.
	BuildLockUpsert struct {
		*sql.UpdateSet
	}
)

// SetServiceName sets the "service_name" field.
func (u *BuildLockUpsert) SetServiceName(v string) *BuildLockUpsert {
	u.Set(buildlock.FieldServiceName, v)
	return u
}

// UpdateServiceName sets the "service_name" field to the value that was provided on create.
func (u *BuildLockUpsert) UpdateServiceName() *BuildLockUpsert {
	u.SetExcluded(buildlock.FieldServiceName)
	return u
}

// SetLockOwner sets the "lock_owner" field.
func (u *BuildLockUpsert) SetLockOwner(v string) *BuildLockUpsert {
	u.Set(buildlock.FieldLockOwner, v)
	return u
}

// UpdateLockOwner sets the "lock_owner" field to the value that was provided on create.
func (u *BuildLockUpsert) UpdateLockOwner() *BuildLockUpsert {
	u.SetExcluded(buildlock.FieldLockOwner)
	return u
}

// SetLockPid sets the "lock_pid" field.
func (u *BuildLockUpsert) SetLockPid(v int) *BuildLockUpsert {
	u.Set(buildlock.FieldLockPid, v)
	return u
}

// UpdateLockPid sets the "lock_pid" field to the value that was provided on create.
func (u *BuildLockUpsert) UpdateLockPid() *BuildLockUpsert {
	u.SetExcluded(buildlock.FieldLockPid)
	return u
}

// AddLockPid adds v to the "lock_pid" field.
func (u *BuildLockUpsert) AddLockPid(v int) *BuildLockUpsert {
	u.Add(buildlock.FieldLockPid, v)
	return u
}

// SetLockHost sets the "lock_host" field.
func (u *BuildLockUpsert) SetLockHost(v string) *BuildLockUpsert {
	u.Set(buildlock.FieldLockHost, v)
	return u
}

// UpdateLockHost sets the "lock_host" field to the value that was provided on create.
func (u *BuildLockUpsert) UpdateLockHost() *BuildLockUpsert {
	u.SetExcluded(buildlock.FieldLockHost)
	return u
}

// SetAcquiredAt sets the "acquired_at" field.
func (u *BuildLockUpsert) SetAcquiredAt(v time.Time) *BuildLockUpsert {
	u.Set(buildlock.FieldAcquiredAt, v)
	return u
}

// UpdateAcquiredAt sets the "acquired_at" field to the value that was provided on create.
func (u *BuildLockUpsert) UpdateAcquiredAt() *BuildLockUpsert {
	u.SetExcluded(buildlock.FieldAcquiredAt)
	return u
}

// SetHeartbeat sets the "heartbeat" field.
func (u *BuildLockUpsert) SetHeartbeat(v time.Time) *BuildLockUpsert {
	u.Set(buildlock.FieldHeartbeat, v)
	return u
}

// UpdateHeartbeat sets the "heartbeat" field to the value that was provided on create.
func (u *BuildLockUpsert) UpdateHeartbeat() *BuildLockUpsert {
	u.SetExcluded(buildlock.FieldHeartbeat)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BuildLock.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BuildLockUpsertOne) UpdateNewValues() *BuildLockUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BuildLock.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BuildLockUpsertOne) Ignore() *BuildLockUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BuildLockUpsertOne) DoNothing() *BuildLockUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BuildLockCreate.OnConflict
// documentation for more info.
func (u *BuildLockUpsertOne) Update(set func(*BuildLockUpsert)) *BuildLockUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BuildLockUpsert{UpdateSet: update})
	}))
	return u
}

// SetServiceName sets the "service_name" field.
func (u *BuildLockUpsertOne) SetServiceName(v string) *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetServiceName(v)
	})
}

// UpdateServiceName sets the "service_name" field to the value that was provided on create.
func (u *BuildLockUpsertOne) UpdateServiceName() *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateServiceName()
	})
}

// SetLockOwner sets the "lock_owner" field.
func (u *BuildLockUpsertOne) SetLockOwner(v string) *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetLockOwner(v)
	})
}

// UpdateLockOwner sets the "lock_owner" field to the value that was provided on create.
func (u *BuildLockUpsertOne) UpdateLockOwner() *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateLockOwner()
	})
}

// SetLockPid sets the "lock_pid" field.
func (u *BuildLockUpsertOne) SetLockPid(v int) *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetLockPid(v)
	})
}

// AddLockPid adds v to the "lock_pid" field.
func (u *BuildLockUpsertOne) AddLockPid(v int) *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.AddLockPid(v)
	})
}

// UpdateLockPid sets the "lock_pid" field to the value that was provided on create.
func (u *BuildLockUpsertOne) UpdateLockPid() *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateLockPid()
	})
}

// SetLockHost sets the "lock_host" field.
func (u *BuildLockUpsertOne) SetLockHost(v string) *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetLockHost(v)
	})
}

// UpdateLockHost sets the "lock_host" field to the value that was provided on create.
func (u *BuildLockUpsertOne) UpdateLockHost() *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateLockHost()
	})
}

// SetAcquiredAt sets the "acquired_at" field.
func (u *BuildLockUpsertOne) SetAcquiredAt(v time.Time) *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetAcquiredAt(v)
	})
}

// UpdateAcquiredAt sets the "acquired_at" field to the value that was provided on create.
func (u *BuildLockUpsertOne) UpdateAcquiredAt() *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateAcquiredAt()
	})
}

// SetHeartbeat sets the "heartbeat" field.
func (u *BuildLockUpsertOne) SetHeartbeat(v time.Time) *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetHeartbeat(v)
	})
}

// UpdateHeartbeat sets the "heartbeat" field to the value that was provided on create.
func (u *BuildLockUpsertOne) UpdateHeartbeat() *BuildLockUpsertOne {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateHeartbeat()
	})
}

// Exec executes the query.
func (u *BuildLockUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BuildLockCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BuildLockUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BuildLockUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BuildLockUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BuildLockCreateBulk is the builder for creating many BuildLock entities in bulk.
type BuildLockCreateBulk struct {
	config
	err      error
	builders []*BuildLockCreate
	conflict []sql.ConflictOption
}

// Save creates the BuildLock entities in the database.
func (_c *BuildLockCreateBulk) Save(ctx context.Context) ([]*BuildLock, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BuildLock, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BuildLockMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BuildLockCreateBulk) SaveX(ctx context.Context) []*BuildLock {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BuildLockCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BuildLockCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BuildLock.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BuildLockUpsert) {
//			SetServiceName(v+v).
//		}).
//		Exec(ctx)
func (_c *BuildLockCreateBulk) OnConflict(opts ...sql.ConflictOption) *BuildLockUpsertBulk {
	_c.conflict = opts
	return &BuildLockUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BuildLock.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BuildLockCreateBulk) OnConflictColumns(columns ...string) *BuildLockUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BuildLockUpsertBulk{
		create: _c,
	}
}

// BuildLockUpsertBulk is the builder for "upsert"-ing
// a bulk of BuildLock nodes.
type BuildLockUpsertBulk struct {
	create *BuildLockCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BuildLock.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BuildLockUpsertBulk) UpdateNewValues() *BuildLockUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BuildLock.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BuildLockUpsertBulk) Ignore() *BuildLockUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BuildLockUpsertBulk) DoNothing() *BuildLockUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BuildLockCreateBulk.OnConflict
// documentation for more info.
func (u *BuildLockUpsertBulk) Update(set func(*BuildLockUpsert)) *BuildLockUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BuildLockUpsert{UpdateSet: update})
	}))
	return u
}

// SetServiceName sets the "service_name" field.
func (u *BuildLockUpsertBulk) SetServiceName(v string) *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetServiceName(v)
	})
}

// UpdateServiceName sets the "service_name" field to the value that was provided on create.
func (u *BuildLockUpsertBulk) UpdateServiceName() *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateServiceName()
	})
}

// SetLockOwner sets the "lock_owner" field.
func (u *BuildLockUpsertBulk) SetLockOwner(v string) *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetLockOwner(v)
	})
}

// UpdateLockOwner sets the "lock_owner" field to the value that was provided on create.
func (u *BuildLockUpsertBulk) UpdateLockOwner() *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateLockOwner()
	})
}

// SetLockPid sets the "lock_pid" field.
func (u *BuildLockUpsertBulk) SetLockPid(v int) *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetLockPid(v)
	})
}

// AddLockPid adds v to the "lock_pid" field.
func (u *BuildLockUpsertBulk) AddLockPid(v int) *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.AddLockPid(v)
	})
}

// UpdateLockPid sets the "lock_pid" field to the value that was provided on create.
func (u *BuildLockUpsertBulk) UpdateLockPid() *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateLockPid()
	})
}

// SetLockHost sets the "lock_host" field.
func (u *BuildLockUpsertBulk) SetLockHost(v string) *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetLockHost(v)
	})
}

// UpdateLockHost sets the "lock_host" field to the value that was provided on create.
func (u *BuildLockUpsertBulk) UpdateLockHost() *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateLockHost()
	})
}

// SetAcquiredAt sets the "acquired_at" field.
func (u *BuildLockUpsertBulk) SetAcquiredAt(v time.Time) *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetAcquiredAt(v)
	})
}

// UpdateAcquiredAt sets the "acquired_at" field to the value that was provided on create.
func (u *BuildLockUpsertBulk) UpdateAcquiredAt() *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateAcquiredAt()
	})
}

// SetHeartbeat sets the "heartbeat" field.
func (u *BuildLockUpsertBulk) SetHeartbeat(v time.Time) *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.SetHeartbeat(v)
	})
}

// UpdateHeartbeat sets the "heartbeat" field to the value that was provided on create.
func (u *BuildLockUpsertBulk) UpdateHeartbeat() *BuildLockUpsertBulk {
	return u.Update(func(s *BuildLockUpsert) {
		s.UpdateHeartbeat()
	})
}

// Exec executes the query.
func (u *BuildLockUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BuildLockCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BuildLockCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BuildLockUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
