// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"app-builds/common/ent/migrate"

	"app-builds/common/ent/codeembedding"
	"app-builds/common/ent/codeingestion"
	"app-builds/common/ent/inferencenode"
	"app-builds/common/ent/memoryevent"
	"app-builds/common/ent/memoryitem"
	"app-builds/common/ent/memorylink"
	"app-builds/common/ent/modeldefinition"
	"app-builds/common/ent/modelexecutionmetric"
	"app-builds/common/ent/prompt"
	"app-builds/common/ent/response"
	"app-builds/common/ent/retrievallog"
	"app-builds/common/ent/session"
	"app-builds/common/ent/tag"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CodeEmbedding is the client for interacting with the CodeEmbedding builders.
	CodeEmbedding *CodeEmbeddingClient
	// CodeIngestion is the client for interacting with the CodeIngestion builders.
	CodeIngestion *CodeIngestionClient
	// InferenceNode is the client for interacting with the InferenceNode builders.
	InferenceNode *InferenceNodeClient
	// MemoryEvent is the client for interacting with the MemoryEvent builders.
	MemoryEvent *MemoryEventClient
	// MemoryItem is the client for interacting with the MemoryItem builders.
	MemoryItem *MemoryItemClient
	// MemoryLink is the client for interacting with the MemoryLink builders.
	MemoryLink *MemoryLinkClient
	// ModelDefinition is the client for interacting with the ModelDefinition builders.
	ModelDefinition *ModelDefinitionClient
	// ModelExecutionMetric is the client for interacting with the ModelExecutionMetric builders.
	ModelExecutionMetric *ModelExecutionMetricClient
	// Prompt is the client for interacting with the Prompt builders.
	Prompt *PromptClient
	// Response is the client for interacting with the Response builders.
	Response *ResponseClient
	// RetrievalLog is the client for interacting with the RetrievalLog builders.
	RetrievalLog *RetrievalLogClient
	// Session is the client for interacting with the Session builders.
	Session *SessionClient
	// Tag is the client for interacting with the Tag builders.
	Tag *TagClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CodeEmbedding = NewCodeEmbeddingClient(c.config)
	c.CodeIngestion = NewCodeIngestionClient(c.config)
	c.InferenceNode = NewInferenceNodeClient(c.config)
	c.MemoryEvent = NewMemoryEventClient(c.config)
	c.MemoryItem = NewMemoryItemClient(c.config)
	c.MemoryLink = NewMemoryLinkClient(c.config)
	c.ModelDefinition = NewModelDefinitionClient(c.config)
	c.ModelExecutionMetric = NewModelExecutionMetricClient(c.config)
	c.Prompt = NewPromptClient(c.config)
	c.Response = NewResponseClient(c.config)
	c.RetrievalLog = NewRetrievalLogClient(c.config)
	c.Session = NewSessionClient(c.config)
	c.Tag = NewTagClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		CodeEmbedding:        NewCodeEmbeddingClient(cfg),
		CodeIngestion:        NewCodeIngestionClient(cfg),
		InferenceNode:        NewInferenceNodeClient(cfg),
		MemoryEvent:          NewMemoryEventClient(cfg),
		MemoryItem:           NewMemoryItemClient(cfg),
		MemoryLink:           NewMemoryLinkClient(cfg),
		ModelDefinition:      NewModelDefinitionClient(cfg),
		ModelExecutionMetric: NewModelExecutionMetricClient(cfg),
		Prompt:               NewPromptClient(cfg),
		Response:             NewResponseClient(cfg),
		RetrievalLog:         NewRetrievalLogClient(cfg),
		Session:              NewSessionClient(cfg),
		Tag:                  NewTagClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		CodeEmbedding:        NewCodeEmbeddingClient(cfg),
		CodeIngestion:        NewCodeIngestionClient(cfg),
		InferenceNode:        NewInferenceNodeClient(cfg),
		MemoryEvent:          NewMemoryEventClient(cfg),
		MemoryItem:           NewMemoryItemClient(cfg),
		MemoryLink:           NewMemoryLinkClient(cfg),
		ModelDefinition:      NewModelDefinitionClient(cfg),
		ModelExecutionMetric: NewModelExecutionMetricClient(cfg),
		Prompt:               NewPromptClient(cfg),
		Response:             NewResponseClient(cfg),
		RetrievalLog:         NewRetrievalLogClient(cfg),
		Session:              NewSessionClient(cfg),
		Tag:                  NewTagClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CodeEmbedding.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.CodeEmbedding, c.CodeIngestion, c.InferenceNode, c.MemoryEvent, c.MemoryItem,
		c.MemoryLink, c.ModelDefinition, c.ModelExecutionMetric, c.Prompt, c.Response,
		c.RetrievalLog, c.Session, c.Tag,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.CodeEmbedding, c.CodeIngestion, c.InferenceNode, c.MemoryEvent, c.MemoryItem,
		c.MemoryLink, c.ModelDefinition, c.ModelExecutionMetric, c.Prompt, c.Response,
		c.RetrievalLog, c.Session, c.Tag,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CodeEmbeddingMutation:
		return c.CodeEmbedding.mutate(ctx, m)
	case *CodeIngestionMutation:
		return c.CodeIngestion.mutate(ctx, m)
	case *InferenceNodeMutation:
		return c.InferenceNode.mutate(ctx, m)
	case *MemoryEventMutation:
		return c.MemoryEvent.mutate(ctx, m)
	case *MemoryItemMutation:
		return c.MemoryItem.mutate(ctx, m)
	case *MemoryLinkMutation:
		return c.MemoryLink.mutate(ctx, m)
	case *ModelDefinitionMutation:
		return c.ModelDefinition.mutate(ctx, m)
	case *ModelExecutionMetricMutation:
		return c.ModelExecutionMetric.mutate(ctx, m)
	case *PromptMutation:
		return c.Prompt.mutate(ctx, m)
	case *ResponseMutation:
		return c.Response.mutate(ctx, m)
	case *RetrievalLogMutation:
		return c.RetrievalLog.mutate(ctx, m)
	case *SessionMutation:
		return c.Session.mutate(ctx, m)
	case *TagMutation:
		return c.Tag.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CodeEmbeddingClient is a client for the CodeEmbedding schema.
type CodeEmbeddingClient struct {
	config
}

// NewCodeEmbeddingClient returns a client for the CodeEmbedding from the given config.
func NewCodeEmbeddingClient(c config) *CodeEmbeddingClient {
	return &CodeEmbeddingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `codeembedding.Hooks(f(g(h())))`.
func (c *CodeEmbeddingClient) Use(hooks ...Hook) {
	c.hooks.CodeEmbedding = append(c.hooks.CodeEmbedding, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `codeembedding.Intercept(f(g(h())))`.
func (c *CodeEmbeddingClient) Intercept(interceptors ...Interceptor) {
	c.inters.CodeEmbedding = append(c.inters.CodeEmbedding, interceptors...)
}

// Create returns a builder for creating a CodeEmbedding entity.
func (c *CodeEmbeddingClient) Create() *CodeEmbeddingCreate {
	mutation := newCodeEmbeddingMutation(c.config, OpCreate)
	return &CodeEmbeddingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CodeEmbedding entities.
func (c *CodeEmbeddingClient) CreateBulk(builders ...*CodeEmbeddingCreate) *CodeEmbeddingCreateBulk {
	return &CodeEmbeddingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CodeEmbeddingClient) MapCreateBulk(slice any, setFunc func(*CodeEmbeddingCreate, int)) *CodeEmbeddingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CodeEmbeddingCreateBulk{err: fmt.Errorf("calling to CodeEmbeddingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CodeEmbeddingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CodeEmbeddingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CodeEmbedding.
func (c *CodeEmbeddingClient) Update() *CodeEmbeddingUpdate {
	mutation := newCodeEmbeddingMutation(c.config, OpUpdate)
	return &CodeEmbeddingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CodeEmbeddingClient) UpdateOne(_m *CodeEmbedding) *CodeEmbeddingUpdateOne {
	mutation := newCodeEmbeddingMutation(c.config, OpUpdateOne, withCodeEmbedding(_m))
	return &CodeEmbeddingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CodeEmbeddingClient) UpdateOneID(id int64) *CodeEmbeddingUpdateOne {
	mutation := newCodeEmbeddingMutation(c.config, OpUpdateOne, withCodeEmbeddingID(id))
	return &CodeEmbeddingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CodeEmbedding.
func (c *CodeEmbeddingClient) Delete() *CodeEmbeddingDelete {
	mutation := newCodeEmbeddingMutation(c.config, OpDelete)
	return &CodeEmbeddingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CodeEmbeddingClient) DeleteOne(_m *CodeEmbedding) *CodeEmbeddingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CodeEmbeddingClient) DeleteOneID(id int64) *CodeEmbeddingDeleteOne {
	builder := c.Delete().Where(codeembedding.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CodeEmbeddingDeleteOne{builder}
}

// Query returns a query builder for CodeEmbedding.
func (c *CodeEmbeddingClient) Query() *CodeEmbeddingQuery {
	return &CodeEmbeddingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCodeEmbedding},
		inters: c.Interceptors(),
	}
}

// Get returns a CodeEmbedding entity by its id.
func (c *CodeEmbeddingClient) Get(ctx context.Context, id int64) (*CodeEmbedding, error) {
	return c.Query().Where(codeembedding.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CodeEmbeddingClient) GetX(ctx context.Context, id int64) *CodeEmbedding {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryIngestion queries the ingestion edge of a CodeEmbedding.
func (c *CodeEmbeddingClient) QueryIngestion(_m *CodeEmbedding) *CodeIngestionQuery {
	query := (&CodeIngestionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(codeembedding.Table, codeembedding.FieldID, id),
			sqlgraph.To(codeingestion.Table, codeingestion.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, codeembedding.IngestionTable, codeembedding.IngestionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTags queries the tags edge of a CodeEmbedding.
func (c *CodeEmbeddingClient) QueryTags(_m *CodeEmbedding) *TagQuery {
	query := (&TagClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(codeembedding.Table, codeembedding.FieldID, id),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, codeembedding.TagsTable, codeembedding.TagsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CodeEmbeddingClient) Hooks() []Hook {
	return c.hooks.CodeEmbedding
}

// Interceptors returns the client interceptors.
func (c *CodeEmbeddingClient) Interceptors() []Interceptor {
	return c.inters.CodeEmbedding
}

func (c *CodeEmbeddingClient) mutate(ctx context.Context, m *CodeEmbeddingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CodeEmbeddingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CodeEmbeddingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CodeEmbeddingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CodeEmbeddingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CodeEmbedding mutation op: %q", m.Op())
	}
}

// CodeIngestionClient is a client for the CodeIngestion schema.
type CodeIngestionClient struct {
	config
}

// NewCodeIngestionClient returns a client for the CodeIngestion from the given config.
func NewCodeIngestionClient(c config) *CodeIngestionClient {
	return &CodeIngestionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `codeingestion.Hooks(f(g(h())))`.
func (c *CodeIngestionClient) Use(hooks ...Hook) {
	c.hooks.CodeIngestion = append(c.hooks.CodeIngestion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `codeingestion.Intercept(f(g(h())))`.
func (c *CodeIngestionClient) Intercept(interceptors ...Interceptor) {
	c.inters.CodeIngestion = append(c.inters.CodeIngestion, interceptors...)
}

// Create returns a builder for creating a CodeIngestion entity.
func (c *CodeIngestionClient) Create() *CodeIngestionCreate {
	mutation := newCodeIngestionMutation(c.config, OpCreate)
	return &CodeIngestionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CodeIngestion entities.
func (c *CodeIngestionClient) CreateBulk(builders ...*CodeIngestionCreate) *CodeIngestionCreateBulk {
	return &CodeIngestionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CodeIngestionClient) MapCreateBulk(slice any, setFunc func(*CodeIngestionCreate, int)) *CodeIngestionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CodeIngestionCreateBulk{err: fmt.Errorf("calling to CodeIngestionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CodeIngestionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CodeIngestionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CodeIngestion.
func (c *CodeIngestionClient) Update() *CodeIngestionUpdate {
	mutation := newCodeIngestionMutation(c.config, OpUpdate)
	return &CodeIngestionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CodeIngestionClient) UpdateOne(_m *CodeIngestion) *CodeIngestionUpdateOne {
	mutation := newCodeIngestionMutation(c.config, OpUpdateOne, withCodeIngestion(_m))
	return &CodeIngestionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CodeIngestionClient) UpdateOneID(id int64) *CodeIngestionUpdateOne {
	mutation := newCodeIngestionMutation(c.config, OpUpdateOne, withCodeIngestionID(id))
	return &CodeIngestionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CodeIngestion.
func (c *CodeIngestionClient) Delete() *CodeIngestionDelete {
	mutation := newCodeIngestionMutation(c.config, OpDelete)
	return &CodeIngestionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CodeIngestionClient) DeleteOne(_m *CodeIngestion) *CodeIngestionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CodeIngestionClient) DeleteOneID(id int64) *CodeIngestionDeleteOne {
	builder := c.Delete().Where(codeingestion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CodeIngestionDeleteOne{builder}
}

// Query returns a query builder for CodeIngestion.
func (c *CodeIngestionClient) Query() *CodeIngestionQuery {
	return &CodeIngestionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCodeIngestion},
		inters: c.Interceptors(),
	}
}

// Get returns a CodeIngestion entity by its id.
func (c *CodeIngestionClient) Get(ctx context.Context, id int64) (*CodeIngestion, error) {
	return c.Query().Where(codeingestion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CodeIngestionClient) GetX(ctx context.Context, id int64) *CodeIngestion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEmbeddings queries the embeddings edge of a CodeIngestion.
func (c *CodeIngestionClient) QueryEmbeddings(_m *CodeIngestion) *CodeEmbeddingQuery {
	query := (&CodeEmbeddingClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(codeingestion.Table, codeingestion.FieldID, id),
			sqlgraph.To(codeembedding.Table, codeembedding.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, codeingestion.EmbeddingsTable, codeingestion.EmbeddingsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTags queries the tags edge of a CodeIngestion.
func (c *CodeIngestionClient) QueryTags(_m *CodeIngestion) *TagQuery {
	query := (&TagClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(codeingestion.Table, codeingestion.FieldID, id),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, codeingestion.TagsTable, codeingestion.TagsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CodeIngestionClient) Hooks() []Hook {
	return c.hooks.CodeIngestion
}

// Interceptors returns the client interceptors.
func (c *CodeIngestionClient) Interceptors() []Interceptor {
	return c.inters.CodeIngestion
}

func (c *CodeIngestionClient) mutate(ctx context.Context, m *CodeIngestionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CodeIngestionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CodeIngestionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CodeIngestionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CodeIngestionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CodeIngestion mutation op: %q", m.Op())
	}
}

// InferenceNodeClient is a client for the InferenceNode schema.
type InferenceNodeClient struct {
	config
}

// NewInferenceNodeClient returns a client for the InferenceNode from the given config.
func NewInferenceNodeClient(c config) *InferenceNodeClient {
	return &InferenceNodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `inferencenode.Hooks(f(g(h())))`.
func (c *InferenceNodeClient) Use(hooks ...Hook) {
	c.hooks.InferenceNode = append(c.hooks.InferenceNode, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `inferencenode.Intercept(f(g(h())))`.
func (c *InferenceNodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.InferenceNode = append(c.inters.InferenceNode, interceptors...)
}

// Create returns a builder for creating a InferenceNode entity.
func (c *InferenceNodeClient) Create() *InferenceNodeCreate {
	mutation := newInferenceNodeMutation(c.config, OpCreate)
	return &InferenceNodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InferenceNode entities.
func (c *InferenceNodeClient) CreateBulk(builders ...*InferenceNodeCreate) *InferenceNodeCreateBulk {
	return &InferenceNodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InferenceNodeClient) MapCreateBulk(slice any, setFunc func(*InferenceNodeCreate, int)) *InferenceNodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InferenceNodeCreateBulk{err: fmt.Errorf("calling to InferenceNodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InferenceNodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InferenceNodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InferenceNode.
func (c *InferenceNodeClient) Update() *InferenceNodeUpdate {
	mutation := newInferenceNodeMutation(c.config, OpUpdate)
	return &InferenceNodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InferenceNodeClient) UpdateOne(_m *InferenceNode) *InferenceNodeUpdateOne {
	mutation := newInferenceNodeMutation(c.config, OpUpdateOne, withInferenceNode(_m))
	return &InferenceNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InferenceNodeClient) UpdateOneID(id int64) *InferenceNodeUpdateOne {
	mutation := newInferenceNodeMutation(c.config, OpUpdateOne, withInferenceNodeID(id))
	return &InferenceNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InferenceNode.
func (c *InferenceNodeClient) Delete() *InferenceNodeDelete {
	mutation := newInferenceNodeMutation(c.config, OpDelete)
	return &InferenceNodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InferenceNodeClient) DeleteOne(_m *InferenceNode) *InferenceNodeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InferenceNodeClient) DeleteOneID(id int64) *InferenceNodeDeleteOne {
	builder := c.Delete().Where(inferencenode.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InferenceNodeDeleteOne{builder}
}

// Query returns a query builder for InferenceNode.
func (c *InferenceNodeClient) Query() *InferenceNodeQuery {
	return &InferenceNodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInferenceNode},
		inters: c.Interceptors(),
	}
}

// Get returns a InferenceNode entity by its id.
func (c *InferenceNodeClient) Get(ctx context.Context, id int64) (*InferenceNode, error) {
	return c.Query().Where(inferencenode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InferenceNodeClient) GetX(ctx context.Context, id int64) *InferenceNode {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMetrics queries the metrics edge of a InferenceNode.
func (c *InferenceNodeClient) QueryMetrics(_m *InferenceNode) *ModelExecutionMetricQuery {
	query := (&ModelExecutionMetricClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(inferencenode.Table, inferencenode.FieldID, id),
			sqlgraph.To(modelexecutionmetric.Table, modelexecutionmetric.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, inferencenode.MetricsTable, inferencenode.MetricsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *InferenceNodeClient) Hooks() []Hook {
	return c.hooks.InferenceNode
}

// Interceptors returns the client interceptors.
func (c *InferenceNodeClient) Interceptors() []Interceptor {
	return c.inters.InferenceNode
}

func (c *InferenceNodeClient) mutate(ctx context.Context, m *InferenceNodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InferenceNodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InferenceNodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InferenceNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InferenceNodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InferenceNode mutation op: %q", m.Op())
	}
}

// MemoryEventClient is a client for the MemoryEvent schema.
type MemoryEventClient struct {
	config
}

// NewMemoryEventClient returns a client for the MemoryEvent from the given config.
func NewMemoryEventClient(c config) *MemoryEventClient {
	return &MemoryEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `memoryevent.Hooks(f(g(h())))`.
func (c *MemoryEventClient) Use(hooks ...Hook) {
	c.hooks.MemoryEvent = append(c.hooks.MemoryEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `memoryevent.Intercept(f(g(h())))`.
func (c *MemoryEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.MemoryEvent = append(c.inters.MemoryEvent, interceptors...)
}

// Create returns a builder for creating a MemoryEvent entity.
func (c *MemoryEventClient) Create() *MemoryEventCreate {
	mutation := newMemoryEventMutation(c.config, OpCreate)
	return &MemoryEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MemoryEvent entities.
func (c *MemoryEventClient) CreateBulk(builders ...*MemoryEventCreate) *MemoryEventCreateBulk {
	return &MemoryEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MemoryEventClient) MapCreateBulk(slice any, setFunc func(*MemoryEventCreate, int)) *MemoryEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MemoryEventCreateBulk{err: fmt.Errorf("calling to MemoryEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MemoryEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MemoryEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MemoryEvent.
func (c *MemoryEventClient) Update() *MemoryEventUpdate {
	mutation := newMemoryEventMutation(c.config, OpUpdate)
	return &MemoryEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MemoryEventClient) UpdateOne(_m *MemoryEvent) *MemoryEventUpdateOne {
	mutation := newMemoryEventMutation(c.config, OpUpdateOne, withMemoryEvent(_m))
	return &MemoryEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MemoryEventClient) UpdateOneID(id int64) *MemoryEventUpdateOne {
	mutation := newMemoryEventMutation(c.config, OpUpdateOne, withMemoryEventID(id))
	return &MemoryEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MemoryEvent.
func (c *MemoryEventClient) Delete() *MemoryEventDelete {
	mutation := newMemoryEventMutation(c.config, OpDelete)
	return &MemoryEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MemoryEventClient) DeleteOne(_m *MemoryEvent) *MemoryEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MemoryEventClient) DeleteOneID(id int64) *MemoryEventDeleteOne {
	builder := c.Delete().Where(memoryevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MemoryEventDeleteOne{builder}
}

// Query returns a query builder for MemoryEvent.
func (c *MemoryEventClient) Query() *MemoryEventQuery {
	return &MemoryEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMemoryEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a MemoryEvent entity by its id.
func (c *MemoryEventClient) Get(ctx context.Context, id int64) (*MemoryEvent, error) {
	return c.Query().Where(memoryevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MemoryEventClient) GetX(ctx context.Context, id int64) *MemoryEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a MemoryEvent.
func (c *MemoryEventClient) QuerySession(_m *MemoryEvent) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(memoryevent.Table, memoryevent.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, memoryevent.SessionTable, memoryevent.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMemoryItem queries the memory_item edge of a MemoryEvent.
func (c *MemoryEventClient) QueryMemoryItem(_m *MemoryEvent) *MemoryItemQuery {
	query := (&MemoryItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(memoryevent.Table, memoryevent.FieldID, id),
			sqlgraph.To(memoryitem.Table, memoryitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, memoryevent.MemoryItemTable, memoryevent.MemoryItemColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MemoryEventClient) Hooks() []Hook {
	return c.hooks.MemoryEvent
}

// Interceptors returns the client interceptors.
func (c *MemoryEventClient) Interceptors() []Interceptor {
	return c.inters.MemoryEvent
}

func (c *MemoryEventClient) mutate(ctx context.Context, m *MemoryEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MemoryEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MemoryEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MemoryEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MemoryEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MemoryEvent mutation op: %q", m.Op())
	}
}

// MemoryItemClient is a client for the MemoryItem schema.
type MemoryItemClient struct {
	config
}

// NewMemoryItemClient returns a client for the MemoryItem from the given config.
func NewMemoryItemClient(c config) *MemoryItemClient {
	return &MemoryItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `memoryitem.Hooks(f(g(h())))`.
func (c *MemoryItemClient) Use(hooks ...Hook) {
	c.hooks.MemoryItem = append(c.hooks.MemoryItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `memoryitem.Intercept(f(g(h())))`.
func (c *MemoryItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.MemoryItem = append(c.inters.MemoryItem, interceptors...)
}

// Create returns a builder for creating a MemoryItem entity.
func (c *MemoryItemClient) Create() *MemoryItemCreate {
	mutation := newMemoryItemMutation(c.config, OpCreate)
	return &MemoryItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MemoryItem entities.
func (c *MemoryItemClient) CreateBulk(builders ...*MemoryItemCreate) *MemoryItemCreateBulk {
	return &MemoryItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MemoryItemClient) MapCreateBulk(slice any, setFunc func(*MemoryItemCreate, int)) *MemoryItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MemoryItemCreateBulk{err: fmt.Errorf("calling to MemoryItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MemoryItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MemoryItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MemoryItem.
func (c *MemoryItemClient) Update() *MemoryItemUpdate {
	mutation := newMemoryItemMutation(c.config, OpUpdate)
	return &MemoryItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MemoryItemClient) UpdateOne(_m *MemoryItem) *MemoryItemUpdateOne {
	mutation := newMemoryItemMutation(c.config, OpUpdateOne, withMemoryItem(_m))
	return &MemoryItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MemoryItemClient) UpdateOneID(id int64) *MemoryItemUpdateOne {
	mutation := newMemoryItemMutation(c.config, OpUpdateOne, withMemoryItemID(id))
	return &MemoryItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MemoryItem.
func (c *MemoryItemClient) Delete() *MemoryItemDelete {
	mutation := newMemoryItemMutation(c.config, OpDelete)
	return &MemoryItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MemoryItemClient) DeleteOne(_m *MemoryItem) *MemoryItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MemoryItemClient) DeleteOneID(id int64) *MemoryItemDeleteOne {
	builder := c.Delete().Where(memoryitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MemoryItemDeleteOne{builder}
}

// Query returns a query builder for MemoryItem.
func (c *MemoryItemClient) Query() *MemoryItemQuery {
	return &MemoryItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMemoryItem},
		inters: c.Interceptors(),
	}
}

// Get returns a MemoryItem entity by its id.
func (c *MemoryItemClient) Get(ctx context.Context, id int64) (*MemoryItem, error) {
	return c.Query().Where(memoryitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MemoryItemClient) GetX(ctx context.Context, id int64) *MemoryItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a MemoryItem.
func (c *MemoryItemClient) QuerySession(_m *MemoryItem) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(memoryitem.Table, memoryitem.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, memoryitem.SessionTable, memoryitem.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLinks queries the links edge of a MemoryItem.
func (c *MemoryItemClient) QueryLinks(_m *MemoryItem) *MemoryLinkQuery {
	query := (&MemoryLinkClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(memoryitem.Table, memoryitem.FieldID, id),
			sqlgraph.To(memorylink.Table, memorylink.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, memoryitem.LinksTable, memoryitem.LinksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvents queries the events edge of a MemoryItem.
func (c *MemoryItemClient) QueryEvents(_m *MemoryItem) *MemoryEventQuery {
	query := (&MemoryEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(memoryitem.Table, memoryitem.FieldID, id),
			sqlgraph.To(memoryevent.Table, memoryevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, memoryitem.EventsTable, memoryitem.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MemoryItemClient) Hooks() []Hook {
	return c.hooks.MemoryItem
}

// Interceptors returns the client interceptors.
func (c *MemoryItemClient) Interceptors() []Interceptor {
	return c.inters.MemoryItem
}

func (c *MemoryItemClient) mutate(ctx context.Context, m *MemoryItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MemoryItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MemoryItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MemoryItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MemoryItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MemoryItem mutation op: %q", m.Op())
	}
}

// MemoryLinkClient is a client for the MemoryLink schema.
type MemoryLinkClient struct {
	config
}

// NewMemoryLinkClient returns a client for the MemoryLink from the given config.
func NewMemoryLinkClient(c config) *MemoryLinkClient {
	return &MemoryLinkClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `memorylink.Hooks(f(g(h())))`.
func (c *MemoryLinkClient) Use(hooks ...Hook) {
	c.hooks.MemoryLink = append(c.hooks.MemoryLink, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `memorylink.Intercept(f(g(h())))`.
func (c *MemoryLinkClient) Intercept(interceptors ...Interceptor) {
	c.inters.MemoryLink = append(c.inters.MemoryLink, interceptors...)
}

// Create returns a builder for creating a MemoryLink entity.
func (c *MemoryLinkClient) Create() *MemoryLinkCreate {
	mutation := newMemoryLinkMutation(c.config, OpCreate)
	return &MemoryLinkCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MemoryLink entities.
func (c *MemoryLinkClient) CreateBulk(builders ...*MemoryLinkCreate) *MemoryLinkCreateBulk {
	return &MemoryLinkCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MemoryLinkClient) MapCreateBulk(slice any, setFunc func(*MemoryLinkCreate, int)) *MemoryLinkCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MemoryLinkCreateBulk{err: fmt.Errorf("calling to MemoryLinkClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MemoryLinkCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MemoryLinkCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MemoryLink.
func (c *MemoryLinkClient) Update() *MemoryLinkUpdate {
	mutation := newMemoryLinkMutation(c.config, OpUpdate)
	return &MemoryLinkUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MemoryLinkClient) UpdateOne(_m *MemoryLink) *MemoryLinkUpdateOne {
	mutation := newMemoryLinkMutation(c.config, OpUpdateOne, withMemoryLink(_m))
	return &MemoryLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MemoryLinkClient) UpdateOneID(id int64) *MemoryLinkUpdateOne {
	mutation := newMemoryLinkMutation(c.config, OpUpdateOne, withMemoryLinkID(id))
	return &MemoryLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MemoryLink.
func (c *MemoryLinkClient) Delete() *MemoryLinkDelete {
	mutation := newMemoryLinkMutation(c.config, OpDelete)
	return &MemoryLinkDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MemoryLinkClient) DeleteOne(_m *MemoryLink) *MemoryLinkDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MemoryLinkClient) DeleteOneID(id int64) *MemoryLinkDeleteOne {
	builder := c.Delete().Where(memorylink.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MemoryLinkDeleteOne{builder}
}

// Query returns a query builder for MemoryLink.
func (c *MemoryLinkClient) Query() *MemoryLinkQuery {
	return &MemoryLinkQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMemoryLink},
		inters: c.Interceptors(),
	}
}

// Get returns a MemoryLink entity by its id.
func (c *MemoryLinkClient) Get(ctx context.Context, id int64) (*MemoryLink, error) {
	return c.Query().Where(memorylink.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MemoryLinkClient) GetX(ctx context.Context, id int64) *MemoryLink {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMemoryItem queries the memory_item edge of a MemoryLink.
func (c *MemoryLinkClient) QueryMemoryItem(_m *MemoryLink) *MemoryItemQuery {
	query := (&MemoryItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(memorylink.Table, memorylink.FieldID, id),
			sqlgraph.To(memoryitem.Table, memoryitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, memorylink.MemoryItemTable, memorylink.MemoryItemColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MemoryLinkClient) Hooks() []Hook {
	return c.hooks.MemoryLink
}

// Interceptors returns the client interceptors.
func (c *MemoryLinkClient) Interceptors() []Interceptor {
	return c.inters.MemoryLink
}

func (c *MemoryLinkClient) mutate(ctx context.Context, m *MemoryLinkMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MemoryLinkCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MemoryLinkUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MemoryLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MemoryLinkDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MemoryLink mutation op: %q", m.Op())
	}
}

// ModelDefinitionClient is a client for the ModelDefinition schema.
type ModelDefinitionClient struct {
	config
}

// NewModelDefinitionClient returns a client for the ModelDefinition from the given config.
func NewModelDefinitionClient(c config) *ModelDefinitionClient {
	return &ModelDefinitionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `modeldefinition.Hooks(f(g(h())))`.
func (c *ModelDefinitionClient) Use(hooks ...Hook) {
	c.hooks.ModelDefinition = append(c.hooks.ModelDefinition, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `modeldefinition.Intercept(f(g(h())))`.
func (c *ModelDefinitionClient) Intercept(interceptors ...Interceptor) {
	c.inters.ModelDefinition = append(c.inters.ModelDefinition, interceptors...)
}

// Create returns a builder for creating a ModelDefinition entity.
func (c *ModelDefinitionClient) Create() *ModelDefinitionCreate {
	mutation := newModelDefinitionMutation(c.config, OpCreate)
	return &ModelDefinitionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ModelDefinition entities.
func (c *ModelDefinitionClient) CreateBulk(builders ...*ModelDefinitionCreate) *ModelDefinitionCreateBulk {
	return &ModelDefinitionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ModelDefinitionClient) MapCreateBulk(slice any, setFunc func(*ModelDefinitionCreate, int)) *ModelDefinitionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ModelDefinitionCreateBulk{err: fmt.Errorf("calling to ModelDefinitionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ModelDefinitionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ModelDefinitionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ModelDefinition.
func (c *ModelDefinitionClient) Update() *ModelDefinitionUpdate {
	mutation := newModelDefinitionMutation(c.config, OpUpdate)
	return &ModelDefinitionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ModelDefinitionClient) UpdateOne(_m *ModelDefinition) *ModelDefinitionUpdateOne {
	mutation := newModelDefinitionMutation(c.config, OpUpdateOne, withModelDefinition(_m))
	return &ModelDefinitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ModelDefinitionClient) UpdateOneID(id int64) *ModelDefinitionUpdateOne {
	mutation := newModelDefinitionMutation(c.config, OpUpdateOne, withModelDefinitionID(id))
	return &ModelDefinitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ModelDefinition.
func (c *ModelDefinitionClient) Delete() *ModelDefinitionDelete {
	mutation := newModelDefinitionMutation(c.config, OpDelete)
	return &ModelDefinitionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ModelDefinitionClient) DeleteOne(_m *ModelDefinition) *ModelDefinitionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ModelDefinitionClient) DeleteOneID(id int64) *ModelDefinitionDeleteOne {
	builder := c.Delete().Where(modeldefinition.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ModelDefinitionDeleteOne{builder}
}

// Query returns a query builder for ModelDefinition.
func (c *ModelDefinitionClient) Query() *ModelDefinitionQuery {
	return &ModelDefinitionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeModelDefinition},
		inters: c.Interceptors(),
	}
}

// Get returns a ModelDefinition entity by its id.
func (c *ModelDefinitionClient) Get(ctx context.Context, id int64) (*ModelDefinition, error) {
	return c.Query().Where(modeldefinition.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ModelDefinitionClient) GetX(ctx context.Context, id int64) *ModelDefinition {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMetrics queries the metrics edge of a ModelDefinition.
func (c *ModelDefinitionClient) QueryMetrics(_m *ModelDefinition) *ModelExecutionMetricQuery {
	query := (&ModelExecutionMetricClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(modeldefinition.Table, modeldefinition.FieldID, id),
			sqlgraph.To(modelexecutionmetric.Table, modelexecutionmetric.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, modeldefinition.MetricsTable, modeldefinition.MetricsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ModelDefinitionClient) Hooks() []Hook {
	return c.hooks.ModelDefinition
}

// Interceptors returns the client interceptors.
func (c *ModelDefinitionClient) Interceptors() []Interceptor {
	return c.inters.ModelDefinition
}

func (c *ModelDefinitionClient) mutate(ctx context.Context, m *ModelDefinitionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ModelDefinitionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ModelDefinitionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ModelDefinitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ModelDefinitionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ModelDefinition mutation op: %q", m.Op())
	}
}

// ModelExecutionMetricClient is a client for the ModelExecutionMetric schema.
type ModelExecutionMetricClient struct {
	config
}

// NewModelExecutionMetricClient returns a client for the ModelExecutionMetric from the given config.
func NewModelExecutionMetricClient(c config) *ModelExecutionMetricClient {
	return &ModelExecutionMetricClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `modelexecutionmetric.Hooks(f(g(h())))`.
func (c *ModelExecutionMetricClient) Use(hooks ...Hook) {
	c.hooks.ModelExecutionMetric = append(c.hooks.ModelExecutionMetric, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `modelexecutionmetric.Intercept(f(g(h())))`.
func (c *ModelExecutionMetricClient) Intercept(interceptors ...Interceptor) {
	c.inters.ModelExecutionMetric = append(c.inters.ModelExecutionMetric, interceptors...)
}

// Create returns a builder for creating a ModelExecutionMetric entity.
func (c *ModelExecutionMetricClient) Create() *ModelExecutionMetricCreate {
	mutation := newModelExecutionMetricMutation(c.config, OpCreate)
	return &ModelExecutionMetricCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ModelExecutionMetric entities.
func (c *ModelExecutionMetricClient) CreateBulk(builders ...*ModelExecutionMetricCreate) *ModelExecutionMetricCreateBulk {
	return &ModelExecutionMetricCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ModelExecutionMetricClient) MapCreateBulk(slice any, setFunc func(*ModelExecutionMetricCreate, int)) *ModelExecutionMetricCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ModelExecutionMetricCreateBulk{err: fmt.Errorf("calling to ModelExecutionMetricClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ModelExecutionMetricCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ModelExecutionMetricCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ModelExecutionMetric.
func (c *ModelExecutionMetricClient) Update() *ModelExecutionMetricUpdate {
	mutation := newModelExecutionMetricMutation(c.config, OpUpdate)
	return &ModelExecutionMetricUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ModelExecutionMetricClient) UpdateOne(_m *ModelExecutionMetric) *ModelExecutionMetricUpdateOne {
	mutation := newModelExecutionMetricMutation(c.config, OpUpdateOne, withModelExecutionMetric(_m))
	return &ModelExecutionMetricUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ModelExecutionMetricClient) UpdateOneID(id int64) *ModelExecutionMetricUpdateOne {
	mutation := newModelExecutionMetricMutation(c.config, OpUpdateOne, withModelExecutionMetricID(id))
	return &ModelExecutionMetricUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ModelExecutionMetric.
func (c *ModelExecutionMetricClient) Delete() *ModelExecutionMetricDelete {
	mutation := newModelExecutionMetricMutation(c.config, OpDelete)
	return &ModelExecutionMetricDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ModelExecutionMetricClient) DeleteOne(_m *ModelExecutionMetric) *ModelExecutionMetricDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ModelExecutionMetricClient) DeleteOneID(id int64) *ModelExecutionMetricDeleteOne {
	builder := c.Delete().Where(modelexecutionmetric.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ModelExecutionMetricDeleteOne{builder}
}

// Query returns a query builder for ModelExecutionMetric.
func (c *ModelExecutionMetricClient) Query() *ModelExecutionMetricQuery {
	return &ModelExecutionMetricQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeModelExecutionMetric},
		inters: c.Interceptors(),
	}
}

// Get returns a ModelExecutionMetric entity by its id.
func (c *ModelExecutionMetricClient) Get(ctx context.Context, id int64) (*ModelExecutionMetric, error) {
	return c.Query().Where(modelexecutionmetric.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ModelExecutionMetricClient) GetX(ctx context.Context, id int64) *ModelExecutionMetric {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a ModelExecutionMetric.
func (c *ModelExecutionMetricClient) QuerySession(_m *ModelExecutionMetric) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(modelexecutionmetric.Table, modelexecutionmetric.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, modelexecutionmetric.SessionTable, modelexecutionmetric.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryNode queries the node edge of a ModelExecutionMetric.
func (c *ModelExecutionMetricClient) QueryNode(_m *ModelExecutionMetric) *InferenceNodeQuery {
	query := (&InferenceNodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(modelexecutionmetric.Table, modelexecutionmetric.FieldID, id),
			sqlgraph.To(inferencenode.Table, inferencenode.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, modelexecutionmetric.NodeTable, modelexecutionmetric.NodeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryModel queries the model edge of a ModelExecutionMetric.
func (c *ModelExecutionMetricClient) QueryModel(_m *ModelExecutionMetric) *ModelDefinitionQuery {
	query := (&ModelDefinitionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(modelexecutionmetric.Table, modelexecutionmetric.FieldID, id),
			sqlgraph.To(modeldefinition.Table, modeldefinition.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, modelexecutionmetric.ModelTable, modelexecutionmetric.ModelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ModelExecutionMetricClient) Hooks() []Hook {
	return c.hooks.ModelExecutionMetric
}

// Interceptors returns the client interceptors.
func (c *ModelExecutionMetricClient) Interceptors() []Interceptor {
	return c.inters.ModelExecutionMetric
}

func (c *ModelExecutionMetricClient) mutate(ctx context.Context, m *ModelExecutionMetricMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ModelExecutionMetricCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ModelExecutionMetricUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ModelExecutionMetricUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ModelExecutionMetricDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ModelExecutionMetric mutation op: %q", m.Op())
	}
}

// PromptClient is a client for the Prompt schema.
type PromptClient struct {
	config
}

// NewPromptClient returns a client for the Prompt from the given config.
func NewPromptClient(c config) *PromptClient {
	return &PromptClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `prompt.Hooks(f(g(h())))`.
func (c *PromptClient) Use(hooks ...Hook) {
	c.hooks.Prompt = append(c.hooks.Prompt, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `prompt.Intercept(f(g(h())))`.
func (c *PromptClient) Intercept(interceptors ...Interceptor) {
	c.inters.Prompt = append(c.inters.Prompt, interceptors...)
}

// Create returns a builder for creating a Prompt entity.
func (c *PromptClient) Create() *PromptCreate {
	mutation := newPromptMutation(c.config, OpCreate)
	return &PromptCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Prompt entities.
func (c *PromptClient) CreateBulk(builders ...*PromptCreate) *PromptCreateBulk {
	return &PromptCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PromptClient) MapCreateBulk(slice any, setFunc func(*PromptCreate, int)) *PromptCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PromptCreateBulk{err: fmt.Errorf("calling to PromptClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PromptCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PromptCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Prompt.
func (c *PromptClient) Update() *PromptUpdate {
	mutation := newPromptMutation(c.config, OpUpdate)
	return &PromptUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PromptClient) UpdateOne(_m *Prompt) *PromptUpdateOne {
	mutation := newPromptMutation(c.config, OpUpdateOne, withPrompt(_m))
	return &PromptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PromptClient) UpdateOneID(id int64) *PromptUpdateOne {
	mutation := newPromptMutation(c.config, OpUpdateOne, withPromptID(id))
	return &PromptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Prompt.
func (c *PromptClient) Delete() *PromptDelete {
	mutation := newPromptMutation(c.config, OpDelete)
	return &PromptDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PromptClient) DeleteOne(_m *Prompt) *PromptDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PromptClient) DeleteOneID(id int64) *PromptDeleteOne {
	builder := c.Delete().Where(prompt.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PromptDeleteOne{builder}
}

// Query returns a query builder for Prompt.
func (c *PromptClient) Query() *PromptQuery {
	return &PromptQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePrompt},
		inters: c.Interceptors(),
	}
}

// Get returns a Prompt entity by its id.
func (c *PromptClient) Get(ctx context.Context, id int64) (*Prompt, error) {
	return c.Query().Where(prompt.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PromptClient) GetX(ctx context.Context, id int64) *Prompt {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PromptClient) Hooks() []Hook {
	return c.hooks.Prompt
}

// Interceptors returns the client interceptors.
func (c *PromptClient) Interceptors() []Interceptor {
	return c.inters.Prompt
}

func (c *PromptClient) mutate(ctx context.Context, m *PromptMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PromptCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PromptUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PromptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PromptDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Prompt mutation op: %q", m.Op())
	}
}

// ResponseClient is a client for the Response schema.
type ResponseClient struct {
	config
}

// NewResponseClient returns a client for the Response from the given config.
func NewResponseClient(c config) *ResponseClient {
	return &ResponseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `response.Hooks(f(g(h())))`.
func (c *ResponseClient) Use(hooks ...Hook) {
	c.hooks.Response = append(c.hooks.Response, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `response.Intercept(f(g(h())))`.
func (c *ResponseClient) Intercept(interceptors ...Interceptor) {
	c.inters.Response = append(c.inters.Response, interceptors...)
}

// Create returns a builder for creating a Response entity.
func (c *ResponseClient) Create() *ResponseCreate {
	mutation := newResponseMutation(c.config, OpCreate)
	return &ResponseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Response entities.
func (c *ResponseClient) CreateBulk(builders ...*ResponseCreate) *ResponseCreateBulk {
	return &ResponseCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ResponseClient) MapCreateBulk(slice any, setFunc func(*ResponseCreate, int)) *ResponseCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ResponseCreateBulk{err: fmt.Errorf("calling to ResponseClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ResponseCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ResponseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Response.
func (c *ResponseClient) Update() *ResponseUpdate {
	mutation := newResponseMutation(c.config, OpUpdate)
	return &ResponseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ResponseClient) UpdateOne(_m *Response) *ResponseUpdateOne {
	mutation := newResponseMutation(c.config, OpUpdateOne, withResponse(_m))
	return &ResponseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ResponseClient) UpdateOneID(id int64) *ResponseUpdateOne {
	mutation := newResponseMutation(c.config, OpUpdateOne, withResponseID(id))
	return &ResponseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Response.
func (c *ResponseClient) Delete() *ResponseDelete {
	mutation := newResponseMutation(c.config, OpDelete)
	return &ResponseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ResponseClient) DeleteOne(_m *Response) *ResponseDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ResponseClient) DeleteOneID(id int64) *ResponseDeleteOne {
	builder := c.Delete().Where(response.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ResponseDeleteOne{builder}
}

// Query returns a query builder for Response.
func (c *ResponseClient) Query() *ResponseQuery {
	return &ResponseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeResponse},
		inters: c.Interceptors(),
	}
}

// Get returns a Response entity by its id.
func (c *ResponseClient) Get(ctx context.Context, id int64) (*Response, error) {
	return c.Query().Where(response.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ResponseClient) GetX(ctx context.Context, id int64) *Response {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ResponseClient) Hooks() []Hook {
	return c.hooks.Response
}

// Interceptors returns the client interceptors.
func (c *ResponseClient) Interceptors() []Interceptor {
	return c.inters.Response
}

func (c *ResponseClient) mutate(ctx context.Context, m *ResponseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ResponseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ResponseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ResponseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ResponseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Response mutation op: %q", m.Op())
	}
}

// RetrievalLogClient is a client for the RetrievalLog schema.
type RetrievalLogClient struct {
	config
}

// NewRetrievalLogClient returns a client for the RetrievalLog from the given config.
func NewRetrievalLogClient(c config) *RetrievalLogClient {
	return &RetrievalLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `retrievallog.Hooks(f(g(h())))`.
func (c *RetrievalLogClient) Use(hooks ...Hook) {
	c.hooks.RetrievalLog = append(c.hooks.RetrievalLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `retrievallog.Intercept(f(g(h())))`.
func (c *RetrievalLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.RetrievalLog = append(c.inters.RetrievalLog, interceptors...)
}

// Create returns a builder for creating a RetrievalLog entity.
func (c *RetrievalLogClient) Create() *RetrievalLogCreate {
	mutation := newRetrievalLogMutation(c.config, OpCreate)
	return &RetrievalLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RetrievalLog entities.
func (c *RetrievalLogClient) CreateBulk(builders ...*RetrievalLogCreate) *RetrievalLogCreateBulk {
	return &RetrievalLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RetrievalLogClient) MapCreateBulk(slice any, setFunc func(*RetrievalLogCreate, int)) *RetrievalLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RetrievalLogCreateBulk{err: fmt.Errorf("calling to RetrievalLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RetrievalLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RetrievalLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RetrievalLog.
func (c *RetrievalLogClient) Update() *RetrievalLogUpdate {
	mutation := newRetrievalLogMutation(c.config, OpUpdate)
	return &RetrievalLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RetrievalLogClient) UpdateOne(_m *RetrievalLog) *RetrievalLogUpdateOne {
	mutation := newRetrievalLogMutation(c.config, OpUpdateOne, withRetrievalLog(_m))
	return &RetrievalLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RetrievalLogClient) UpdateOneID(id int64) *RetrievalLogUpdateOne {
	mutation := newRetrievalLogMutation(c.config, OpUpdateOne, withRetrievalLogID(id))
	return &RetrievalLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RetrievalLog.
func (c *RetrievalLogClient) Delete() *RetrievalLogDelete {
	mutation := newRetrievalLogMutation(c.config, OpDelete)
	return &RetrievalLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RetrievalLogClient) DeleteOne(_m *RetrievalLog) *RetrievalLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RetrievalLogClient) DeleteOneID(id int64) *RetrievalLogDeleteOne {
	builder := c.Delete().Where(retrievallog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RetrievalLogDeleteOne{builder}
}

// Query returns a query builder for RetrievalLog.
func (c *RetrievalLogClient) Query() *RetrievalLogQuery {
	return &RetrievalLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRetrievalLog},
		inters: c.Interceptors(),
	}
}

// Get returns a RetrievalLog entity by its id.
func (c *RetrievalLogClient) Get(ctx context.Context, id int64) (*RetrievalLog, error) {
	return c.Query().Where(retrievallog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RetrievalLogClient) GetX(ctx context.Context, id int64) *RetrievalLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a RetrievalLog.
func (c *RetrievalLogClient) QuerySession(_m *RetrievalLog) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(retrievallog.Table, retrievallog.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, retrievallog.SessionTable, retrievallog.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RetrievalLogClient) Hooks() []Hook {
	return c.hooks.RetrievalLog
}

// Interceptors returns the client interceptors.
func (c *RetrievalLogClient) Interceptors() []Interceptor {
	return c.inters.RetrievalLog
}

func (c *RetrievalLogClient) mutate(ctx context.Context, m *RetrievalLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RetrievalLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RetrievalLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RetrievalLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RetrievalLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RetrievalLog mutation op: %q", m.Op())
	}
}

// SessionClient is a client for the Session schema.
type SessionClient struct {
	config
}

// NewSessionClient returns a client for the Session from the given config.
func NewSessionClient(c config) *SessionClient {
	return &SessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `session.Hooks(f(g(h())))`.
func (c *SessionClient) Use(hooks ...Hook) {
	c.hooks.Session = append(c.hooks.Session, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `session.Intercept(f(g(h())))`.
func (c *SessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Session = append(c.inters.Session, interceptors...)
}

// Create returns a builder for creating a Session entity.
func (c *SessionClient) Create() *SessionCreate {
	mutation := newSessionMutation(c.config, OpCreate)
	return &SessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Session entities.
func (c *SessionClient) CreateBulk(builders ...*SessionCreate) *SessionCreateBulk {
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SessionClient) MapCreateBulk(slice any, setFunc func(*SessionCreate, int)) *SessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SessionCreateBulk{err: fmt.Errorf("calling to SessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Session.
func (c *SessionClient) Update() *SessionUpdate {
	mutation := newSessionMutation(c.config, OpUpdate)
	return &SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SessionClient) UpdateOne(_m *Session) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSession(_m))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SessionClient) UpdateOneID(id int64) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSessionID(id))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Session.
func (c *SessionClient) Delete() *SessionDelete {
	mutation := newSessionMutation(c.config, OpDelete)
	return &SessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SessionClient) DeleteOne(_m *Session) *SessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SessionClient) DeleteOneID(id int64) *SessionDeleteOne {
	builder := c.Delete().Where(session.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SessionDeleteOne{builder}
}

// Query returns a query builder for Session.
func (c *SessionClient) Query() *SessionQuery {
	return &SessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSession},
		inters: c.Interceptors(),
	}
}

// Get returns a Session entity by its id.
func (c *SessionClient) Get(ctx context.Context, id int64) (*Session, error) {
	return c.Query().Where(session.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SessionClient) GetX(ctx context.Context, id int64) *Session {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTags queries the tags edge of a Session.
func (c *SessionClient) QueryTags(_m *Session) *TagQuery {
	query := (&TagClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, session.TagsTable, session.TagsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMetrics queries the metrics edge of a Session.
func (c *SessionClient) QueryMetrics(_m *Session) *ModelExecutionMetricQuery {
	query := (&ModelExecutionMetricClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(modelexecutionmetric.Table, modelexecutionmetric.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.MetricsTable, session.MetricsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRetrievalLogs queries the retrieval_logs edge of a Session.
func (c *SessionClient) QueryRetrievalLogs(_m *Session) *RetrievalLogQuery {
	query := (&RetrievalLogClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(retrievallog.Table, retrievallog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.RetrievalLogsTable, session.RetrievalLogsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMemoryEvents queries the memory_events edge of a Session.
func (c *SessionClient) QueryMemoryEvents(_m *Session) *MemoryEventQuery {
	query := (&MemoryEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(memoryevent.Table, memoryevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.MemoryEventsTable, session.MemoryEventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMemoryItems queries the memory_items edge of a Session.
func (c *SessionClient) QueryMemoryItems(_m *Session) *MemoryItemQuery {
	query := (&MemoryItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(memoryitem.Table, memoryitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.MemoryItemsTable, session.MemoryItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SessionClient) Hooks() []Hook {
	return c.hooks.Session
}

// Interceptors returns the client interceptors.
func (c *SessionClient) Interceptors() []Interceptor {
	return c.inters.Session
}

func (c *SessionClient) mutate(ctx context.Context, m *SessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Session mutation op: %q", m.Op())
	}
}

// TagClient is a client for the Tag schema.
type TagClient struct {
	config
}

// NewTagClient returns a client for the Tag from the given config.
func NewTagClient(c config) *TagClient {
	return &TagClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tag.Hooks(f(g(h())))`.
func (c *TagClient) Use(hooks ...Hook) {
	c.hooks.Tag = append(c.hooks.Tag, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tag.Intercept(f(g(h())))`.
func (c *TagClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tag = append(c.inters.Tag, interceptors...)
}

// Create returns a builder for creating a Tag entity.
func (c *TagClient) Create() *TagCreate {
	mutation := newTagMutation(c.config, OpCreate)
	return &TagCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tag entities.
func (c *TagClient) CreateBulk(builders ...*TagCreate) *TagCreateBulk {
	return &TagCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TagClient) MapCreateBulk(slice any, setFunc func(*TagCreate, int)) *TagCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TagCreateBulk{err: fmt.Errorf("calling to TagClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TagCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TagCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tag.
func (c *TagClient) Update() *TagUpdate {
	mutation := newTagMutation(c.config, OpUpdate)
	return &TagUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TagClient) UpdateOne(_m *Tag) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTag(_m))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TagClient) UpdateOneID(id int64) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTagID(id))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tag.
func (c *TagClient) Delete() *TagDelete {
	mutation := newTagMutation(c.config, OpDelete)
	return &TagDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TagClient) DeleteOne(_m *Tag) *TagDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TagClient) DeleteOneID(id int64) *TagDeleteOne {
	builder := c.Delete().Where(tag.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TagDeleteOne{builder}
}

// Query returns a query builder for Tag.
func (c *TagClient) Query() *TagQuery {
	return &TagQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTag},
		inters: c.Interceptors(),
	}
}

// Get returns a Tag entity by its id.
func (c *TagClient) Get(ctx context.Context, id int64) (*Tag, error) {
	return c.Query().Where(tag.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TagClient) GetX(ctx context.Context, id int64) *Tag {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySessions queries the sessions edge of a Tag.
func (c *TagClient) QuerySessions(_m *Tag) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tag.SessionsTable, tag.SessionsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryIngestions queries the ingestions edge of a Tag.
func (c *TagClient) QueryIngestions(_m *Tag) *CodeIngestionQuery {
	query := (&CodeIngestionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(codeingestion.Table, codeingestion.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tag.IngestionsTable, tag.IngestionsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEmbeddings queries the embeddings edge of a Tag.
func (c *TagClient) QueryEmbeddings(_m *Tag) *CodeEmbeddingQuery {
	query := (&CodeEmbeddingClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(codeembedding.Table, codeembedding.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tag.EmbeddingsTable, tag.EmbeddingsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TagClient) Hooks() []Hook {
	return c.hooks.Tag
}

// Interceptors returns the client interceptors.
func (c *TagClient) Interceptors() []Interceptor {
	return c.inters.Tag
}

func (c *TagClient) mutate(ctx context.Context, m *TagMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TagCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TagUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TagDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tag mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CodeEmbedding, CodeIngestion, InferenceNode, MemoryEvent, MemoryItem,
		MemoryLink, ModelDefinition, ModelExecutionMetric, Prompt, Response,
		RetrievalLog, Session, Tag []ent.Hook
	}
	inters struct {
		CodeEmbedding, CodeIngestion, InferenceNode, MemoryEvent, MemoryItem,
		MemoryLink, ModelDefinition, ModelExecutionMetric, Prompt, Response,
		RetrievalLog, Session, Tag []ent.Interceptor
	}
)
