// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/codeembedding"
	"app-builds/common/ent/codeingestion"
	"app-builds/common/ent/predicate"
	"app-builds/common/ent/tag"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CodeIngestionQuery is the builder for querying CodeIngestion entities.
type CodeIngestionQuery struct {
	config
	ctx            *QueryContext
	order          []codeingestion.OrderOption
	inters         []Interceptor
	predicates     []predicate.CodeIngestion
	withEmbeddings *CodeEmbeddingQuery
	withTags       *TagQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CodeIngestionQuery builder.
func (_q *CodeIngestionQuery) Where(ps ...predicate.CodeIngestion) *CodeIngestionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CodeIngestionQuery) Limit(limit int) *CodeIngestionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CodeIngestionQuery) Offset(offset int) *CodeIngestionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CodeIngestionQuery) Unique(unique bool) *CodeIngestionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CodeIngestionQuery) Order(o ...codeingestion.OrderOption) *CodeIngestionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEmbeddings chains the current query on the "embeddings" edge.
func (_q *CodeIngestionQuery) QueryEmbeddings() *CodeEmbeddingQuery {
	query := (&CodeEmbeddingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(codeingestion.Table, codeingestion.FieldID, selector),
			sqlgraph.To(codeembedding.Table, codeembedding.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, codeingestion.EmbeddingsTable, codeingestion.EmbeddingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTags chains the current query on the "tags" edge.
func (_q *CodeIngestionQuery) QueryTags() *TagQuery {
	query := (&TagClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(codeingestion.Table, codeingestion.FieldID, selector),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, codeingestion.TagsTable, codeingestion.TagsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CodeIngestion entity from the query.
// Returns a *NotFoundError when no CodeIngestion was found.
func (_q *CodeIngestionQuery) First(ctx context.Context) (*CodeIngestion, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{codeingestion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CodeIngestionQuery) FirstX(ctx context.Context) *CodeIngestion {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CodeIngestion ID from the query.
// Returns a *NotFoundError when no CodeIngestion ID was found.
func (_q *CodeIngestionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{codeingestion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CodeIngestionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CodeIngestion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CodeIngestion entity is found.
// Returns a *NotFoundError when no CodeIngestion entities are found.
func (_q *CodeIngestionQuery) Only(ctx context.Context) (*CodeIngestion, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{codeingestion.Label}
	default:
		return nil, &NotSingularError{codeingestion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CodeIngestionQuery) OnlyX(ctx context.Context) *CodeIngestion {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CodeIngestion ID in the query.
// Returns a *NotSingularError when more than one CodeIngestion ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CodeIngestionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{codeingestion.Label}
	default:
		err = &NotSingularError{codeingestion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CodeIngestionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CodeIngestions.
func (_q *CodeIngestionQuery) All(ctx context.Context) ([]*CodeIngestion, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CodeIngestion, *CodeIngestionQuery]()
	return withInterceptors[[]*CodeIngestion](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CodeIngestionQuery) AllX(ctx context.Context) []*CodeIngestion {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CodeIngestion IDs.
func (_q *CodeIngestionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(codeingestion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CodeIngestionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CodeIngestionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CodeIngestionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CodeIngestionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CodeIngestionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CodeIngestionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CodeIngestionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CodeIngestionQuery) Clone() *CodeIngestionQuery {
	if _q == nil {
		return nil
	}
	return &CodeIngestionQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]codeingestion.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.CodeIngestion{}, _q.predicates...),
		withEmbeddings: _q.withEmbeddings.Clone(),
		withTags:       _q.withTags.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEmbeddings tells the query-builder to eager-load the nodes that are connected to
// the "embeddings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CodeIngestionQuery) WithEmbeddings(opts ...func(*CodeEmbeddingQuery)) *CodeIngestionQuery {
	query := (&CodeEmbeddingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEmbeddings = query
	return _q
}

// WithTags tells the query-builder to eager-load the nodes that are connected to
// the "tags" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CodeIngestionQuery) WithTags(opts ...func(*TagQuery)) *CodeIngestionQuery {
	query := (&TagClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTags = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		S3BucketID string `json:"s3_bucket_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CodeIngestion.Query().
//		GroupBy(codeingestion.FieldS3BucketID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CodeIngestionQuery) GroupBy(field string, fields ...string) *CodeIngestionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CodeIngestionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = codeingestion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		S3BucketID string `json:"s3_bucket_id,omitempty"`
//	}
//
//	client.CodeIngestion.Query().
//		Select(codeingestion.FieldS3BucketID).
//		Scan(ctx, &v)
func (_q *CodeIngestionQuery) Select(fields ...string) *CodeIngestionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CodeIngestionSelect{CodeIngestionQuery: _q}
	sbuild.label = codeingestion.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CodeIngestionSelect configured with the given aggregations.
func (_q *CodeIngestionQuery) Aggregate(fns ...AggregateFunc) *CodeIngestionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CodeIngestionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !codeingestion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CodeIngestionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CodeIngestion, error) {
	var (
		nodes       = []*CodeIngestion{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withEmbeddings != nil,
			_q.withTags != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CodeIngestion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CodeIngestion{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEmbeddings; query != nil {
		if err := _q.loadEmbeddings(ctx, query, nodes,
			func(n *CodeIngestion) { n.Edges.Embeddings = []*CodeEmbedding{} },
			func(n *CodeIngestion, e *CodeEmbedding) { n.Edges.Embeddings = append(n.Edges.Embeddings, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTags; query != nil {
		if err := _q.loadTags(ctx, query, nodes,
			func(n *CodeIngestion) { n.Edges.Tags = []*Tag{} },
			func(n *CodeIngestion, e *Tag) { n.Edges.Tags = append(n.Edges.Tags, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CodeIngestionQuery) loadEmbeddings(ctx context.Context, query *CodeEmbeddingQuery, nodes []*CodeIngestion, init func(*CodeIngestion), assign func(*CodeIngestion, *CodeEmbedding)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*CodeIngestion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(codeembedding.FieldIngestionID)
	}
	query.Where(predicate.CodeEmbedding(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(codeingestion.EmbeddingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.IngestionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ingestion_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CodeIngestionQuery) loadTags(ctx context.Context, query *TagQuery, nodes []*CodeIngestion, init func(*CodeIngestion), assign func(*CodeIngestion, *Tag)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*CodeIngestion)
	nids := make(map[uuid.UUID]map[*CodeIngestion]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(codeingestion.TagsTable)
		s.Join(joinT).On(s.C(tag.FieldID), joinT.C(codeingestion.TagsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(codeingestion.TagsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(codeingestion.TagsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*CodeIngestion]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Tag](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "tags" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (_q *CodeIngestionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CodeIngestionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(codeingestion.Table, codeingestion.Columns, sqlgraph.NewFieldSpec(codeingestion.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codeingestion.FieldID)
		for i := range fields {
			if fields[i] != codeingestion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CodeIngestionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(codeingestion.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = codeingestion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CodeIngestionGroupBy is the group-by builder for CodeIngestion entities.
type CodeIngestionGroupBy struct {
	selector
	build *CodeIngestionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CodeIngestionGroupBy) Aggregate(fns ...AggregateFunc) *CodeIngestionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CodeIngestionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CodeIngestionQuery, *CodeIngestionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CodeIngestionGroupBy) sqlScan(ctx context.Context, root *CodeIngestionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CodeIngestionSelect is the builder for selecting fields of CodeIngestion entities.
type CodeIngestionSelect struct {
	*CodeIngestionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CodeIngestionSelect) Aggregate(fns ...AggregateFunc) *CodeIngestionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CodeIngestionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CodeIngestionQuery, *CodeIngestionSelect](ctx, _s.CodeIngestionQuery, _s, _s.inters, v)
}

func (_s *CodeIngestionSelect) sqlScan(ctx context.Context, root *CodeIngestionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
