// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/codeembedding"
	"app-builds/common/ent/codeingestion"
	"app-builds/common/ent/tag"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodeEmbeddingCreate is the builder for creating a CodeEmbedding entity.
type CodeEmbeddingCreate struct {
	config
	mutation *CodeEmbeddingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIngestionID sets the "ingestion_id" field.
func (_c *CodeEmbeddingCreate) SetIngestionID(v int64) *CodeEmbeddingCreate {
	_c.mutation.SetIngestionID(v)
	return _c
}

// SetNillableIngestionID sets the "ingestion_id" field if the given value is not nil.
func (_c *CodeEmbeddingCreate) SetNillableIngestionID(v *int64) *CodeEmbeddingCreate {
	if v != nil {
		_c.SetIngestionID(*v)
	}
	return _c
}

// SetEmbeddingVector sets the "embedding_vector" field.
func (_c *CodeEmbeddingCreate) SetEmbeddingVector(v []float32) *CodeEmbeddingCreate {
	_c.mutation.SetEmbeddingVector(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *CodeEmbeddingCreate) SetMetadata(v map[string]interface{}) *CodeEmbeddingCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodeEmbeddingCreate) SetCreatedAt(v time.Time) *CodeEmbeddingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodeEmbeddingCreate) SetNillableCreatedAt(v *time.Time) *CodeEmbeddingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CodeEmbeddingCreate) SetID(v int64) *CodeEmbeddingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetIngestion sets the "ingestion" edge to the CodeIngestion entity.
func (_c *CodeEmbeddingCreate) SetIngestion(v *CodeIngestion) *CodeEmbeddingCreate {
	return _c.SetIngestionID(v.ID)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_c *CodeEmbeddingCreate) AddTagIDs(ids ...int64) *CodeEmbeddingCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the Tag entity.
func (_c *CodeEmbeddingCreate) AddTags(v ...*Tag) *CodeEmbeddingCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// Mutation returns the CodeEmbeddingMutation object of the builder.
func (_c *CodeEmbeddingCreate) Mutation() *CodeEmbeddingMutation {
	return _c.mutation
}

// Save creates the CodeEmbedding in the database.
func (_c *CodeEmbeddingCreate) Save(ctx context.Context) (*CodeEmbedding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodeEmbeddingCreate) SaveX(ctx context.Context) *CodeEmbedding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodeEmbeddingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodeEmbeddingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodeEmbeddingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codeembedding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodeEmbeddingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodeEmbedding.created_at"`)}
	}
	return nil
}

func (_c *CodeEmbeddingCreate) sqlSave(ctx context.Context) (*CodeEmbedding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodeEmbeddingCreate) createSpec() (*CodeEmbedding, *sqlgraph.CreateSpec) {
	var (
		_node = &CodeEmbedding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codeembedding.Table, sqlgraph.NewFieldSpec(codeembedding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.EmbeddingVector(); ok {
		_spec.SetField(codeembedding.FieldEmbeddingVector, field.TypeJSON, value)
		_node.EmbeddingVector = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(codeembedding.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codeembedding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.IngestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codeembedding.IngestionTable,
			Columns: []string{codeembedding.IngestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codeingestion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IngestionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   codeembedding.TagsTable,
			Columns: codeembedding.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodeEmbedding.Create().
//		SetIngestionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodeEmbeddingUpsert) {
//			SetIngestionID(v+v).
//		}).
//		Exec(ctx)
func (_c *CodeEmbeddingCreate) OnConflict(opts ...sql.ConflictOption) *CodeEmbeddingUpsertOne {
	_c.conflict = opts
	return &CodeEmbeddingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodeEmbedding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodeEmbeddingCreate) OnConflictColumns(columns ...string) *CodeEmbeddingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodeEmbeddingUpsertOne{
		create: _c,
	}
}

type (
	// CodeEmbeddingUpsertOne is the builder for "upsert"-ing
	//  one CodeEmbedding node.
	CodeEmbeddingUpsertOne struct {
		create *CodeEmbeddingCreate
	}

	// CodeEmbeddingUpsert is the "OnConflict" setter.
	CodeEmbeddingUpsert struct {
		*sql.UpdateSet
	}
)

// SetIngestionID sets the "ingestion_id" field.
func (u *CodeEmbeddingUpsert) SetIngestionID(v int64) *CodeEmbeddingUpsert {
	u.Set(codeembedding.FieldIngestionID, v)
	return u
}

// UpdateIngestionID sets the "ingestion_id" field to the value that was provided on create.
func (u *CodeEmbeddingUpsert) UpdateIngestionID() *CodeEmbeddingUpsert {
	u.SetExcluded(codeembedding.FieldIngestionID)
	return u
}

// ClearIngestionID clears the value of the "ingestion_id" field.
func (u *CodeEmbeddingUpsert) ClearIngestionID() *CodeEmbeddingUpsert {
	u.SetNull(codeembedding.FieldIngestionID)
	return u
}

// SetEmbeddingVector sets the "embedding_vector" field.
func (u *CodeEmbeddingUpsert) SetEmbeddingVector(v []float32) *CodeEmbeddingUpsert {
	u.Set(codeembedding.FieldEmbeddingVector, v)
	return u
}

// UpdateEmbeddingVector sets the "embedding_vector" field to the value that was provided on create.
func (u *CodeEmbeddingUpsert) UpdateEmbeddingVector() *CodeEmbeddingUpsert {
	u.SetExcluded(codeembedding.FieldEmbeddingVector)
	return u
}

// ClearEmbeddingVector clears the value of the "embedding_vector" field.
func (u *CodeEmbeddingUpsert) ClearEmbeddingVector() *CodeEmbeddingUpsert {
	u.SetNull(codeembedding.FieldEmbeddingVector)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *CodeEmbeddingUpsert) SetMetadata(v map[string]interface{}) *CodeEmbeddingUpsert {
	u.Set(codeembedding.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CodeEmbeddingUpsert) UpdateMetadata() *CodeEmbeddingUpsert {
	u.SetExcluded(codeembedding.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *CodeEmbeddingUpsert) ClearMetadata() *CodeEmbeddingUpsert {
	u.SetNull(codeembedding.FieldMetadata)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CodeEmbeddingUpsert) SetCreatedAt(v time.Time) *CodeEmbeddingUpsert {
	u.Set(codeembedding.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CodeEmbeddingUpsert) UpdateCreatedAt() *CodeEmbeddingUpsert {
	u.SetExcluded(codeembedding.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CodeEmbedding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(codeembedding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CodeEmbeddingUpsertOne) UpdateNewValues() *CodeEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(codeembedding.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodeEmbedding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CodeEmbeddingUpsertOne) Ignore() *CodeEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodeEmbeddingUpsertOne) DoNothing() *CodeEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodeEmbeddingCreate.OnConflict
// documentation for more info.
func (u *CodeEmbeddingUpsertOne) Update(set func(*CodeEmbeddingUpsert)) *CodeEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodeEmbeddingUpsert{UpdateSet: update})
	}))
	return u
}

// SetIngestionID sets the "ingestion_id" field.
func (u *CodeEmbeddingUpsertOne) SetIngestionID(v int64) *CodeEmbeddingUpsertOne {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.SetIngestionID(v)
	})
}

// UpdateIngestionID sets the "ingestion_id" field to the value that was provided on create.
func (u *CodeEmbeddingUpsertOne) UpdateIngestionID() *CodeEmbeddingUpsertOne {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.UpdateIngestionID()
	})
}

// ClearIngestionID clears the value of the "ingestion_id" field.
func (u *CodeEmbeddingUpsertOne) ClearIngestionID() *CodeEmbeddingUpsertOne {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.ClearIngestionID()
	})
}

// SetEmbeddingVector sets the "embedding_vector" field.
func (u *CodeEmbeddingUpsertOne) SetEmbeddingVector(v []float32) *CodeEmbeddingUpsertOne {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.SetEmbeddingVector(v)
	})
}

// UpdateEmbeddingVector sets the "embedding_vector" field to the value that was provided on create.
func (u *CodeEmbeddingUpsertOne) UpdateEmbeddingVector() *CodeEmbeddingUpsertOne {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.UpdateEmbeddingVector()
	})
}

// ClearEmbeddingVector clears the value of the "embedding_vector" field.
func (u *CodeEmbeddingUpsertOne) ClearEmbeddingVector() *CodeEmbeddingUpsertOne {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.ClearEmbeddingVector()
	})
}

// SetMetadata sets the "metadata" field.
func (u *CodeEmbeddingUpsertOne) SetMetadata(v map[string]interface{}) *CodeEmbeddingUpsertOne {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CodeEmbeddingUpsertOne) UpdateMetadata() *CodeEmbeddingUpsertOne {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *CodeEmbeddingUpsertOne) ClearMetadata() *CodeEmbeddingUpsertOne {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.ClearMetadata()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CodeEmbeddingUpsertOne) SetCreatedAt(v time.Time) *CodeEmbeddingUpsertOne {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CodeEmbeddingUpsertOne) UpdateCreatedAt() *CodeEmbeddingUpsertOne {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *CodeEmbeddingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodeEmbeddingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodeEmbeddingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CodeEmbeddingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CodeEmbeddingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CodeEmbeddingCreateBulk is the builder for creating many CodeEmbedding entities in bulk.
type CodeEmbeddingCreateBulk struct {
	config
	err      error
	builders []*CodeEmbeddingCreate
	conflict []sql.ConflictOption
}

// Save creates the CodeEmbedding entities in the database.
func (_c *CodeEmbeddingCreateBulk) Save(ctx context.Context) ([]*CodeEmbedding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodeEmbedding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodeEmbeddingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodeEmbeddingCreateBulk) SaveX(ctx context.Context) []*CodeEmbedding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodeEmbeddingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodeEmbeddingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodeEmbedding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodeEmbeddingUpsert) {
//			SetIngestionID(v+v).
//		}).
//		Exec(ctx)
func (_c *CodeEmbeddingCreateBulk) OnConflict(opts ...sql.ConflictOption) *CodeEmbeddingUpsertBulk {
	_c.conflict = opts
	return &CodeEmbeddingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodeEmbedding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodeEmbeddingCreateBulk) OnConflictColumns(columns ...string) *CodeEmbeddingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodeEmbeddingUpsertBulk{
		create: _c,
	}
}

// CodeEmbeddingUpsertBulk is the builder for "upsert"-ing
// a bulk of CodeEmbedding nodes.
type CodeEmbeddingUpsertBulk struct {
	create *CodeEmbeddingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CodeEmbedding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(codeembedding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CodeEmbeddingUpsertBulk) UpdateNewValues() *CodeEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(codeembedding.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodeEmbedding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CodeEmbeddingUpsertBulk) Ignore() *CodeEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodeEmbeddingUpsertBulk) DoNothing() *CodeEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodeEmbeddingCreateBulk.OnConflict
// documentation for more info.
func (u *CodeEmbeddingUpsertBulk) Update(set func(*CodeEmbeddingUpsert)) *CodeEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodeEmbeddingUpsert{UpdateSet: update})
	}))
	return u
}

// SetIngestionID sets the "ingestion_id" field.
func (u *CodeEmbeddingUpsertBulk) SetIngestionID(v int64) *CodeEmbeddingUpsertBulk {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.SetIngestionID(v)
	})
}

// UpdateIngestionID sets the "ingestion_id" field to the value that was provided on create.
func (u *CodeEmbeddingUpsertBulk) UpdateIngestionID() *CodeEmbeddingUpsertBulk {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.UpdateIngestionID()
	})
}

// ClearIngestionID clears the value of the "ingestion_id" field.
func (u *CodeEmbeddingUpsertBulk) ClearIngestionID() *CodeEmbeddingUpsertBulk {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.ClearIngestionID()
	})
}

// SetEmbeddingVector sets the "embedding_vector" field.
func (u *CodeEmbeddingUpsertBulk) SetEmbeddingVector(v []float32) *CodeEmbeddingUpsertBulk {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.SetEmbeddingVector(v)
	})
}

// UpdateEmbeddingVector sets the "embedding_vector" field to the value that was provided on create.
func (u *CodeEmbeddingUpsertBulk) UpdateEmbeddingVector() *CodeEmbeddingUpsertBulk {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.UpdateEmbeddingVector()
	})
}

// ClearEmbeddingVector clears the value of the "embedding_vector" field.
func (u *CodeEmbeddingUpsertBulk) ClearEmbeddingVector() *CodeEmbeddingUpsertBulk {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.ClearEmbeddingVector()
	})
}

// SetMetadata sets the "metadata" field.
func (u *CodeEmbeddingUpsertBulk) SetMetadata(v map[string]interface{}) *CodeEmbeddingUpsertBulk {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CodeEmbeddingUpsertBulk) UpdateMetadata() *CodeEmbeddingUpsertBulk {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *CodeEmbeddingUpsertBulk) ClearMetadata() *CodeEmbeddingUpsertBulk {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.ClearMetadata()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CodeEmbeddingUpsertBulk) SetCreatedAt(v time.Time) *CodeEmbeddingUpsertBulk {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CodeEmbeddingUpsertBulk) UpdateCreatedAt() *CodeEmbeddingUpsertBulk {
	return u.Update(func(s *CodeEmbeddingUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *CodeEmbeddingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CodeEmbeddingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodeEmbeddingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodeEmbeddingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
