// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/codeembedding"
	"app-builds/common/ent/codeingestion"
	"app-builds/common/ent/predicate"
	"app-builds/common/ent/tag"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// CodeEmbeddingUpdate is the builder for updating CodeEmbedding entities.
type CodeEmbeddingUpdate struct {
	config
	hooks    []Hook
	mutation *CodeEmbeddingMutation
}

// Where appends a list predicates to the CodeEmbeddingUpdate builder.
func (_u *CodeEmbeddingUpdate) Where(ps ...predicate.CodeEmbedding) *CodeEmbeddingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIngestionID sets the "ingestion_id" field.
func (_u *CodeEmbeddingUpdate) SetIngestionID(v int64) *CodeEmbeddingUpdate {
	_u.mutation.SetIngestionID(v)
	return _u
}

// SetNillableIngestionID sets the "ingestion_id" field if the given value is not nil.
func (_u *CodeEmbeddingUpdate) SetNillableIngestionID(v *int64) *CodeEmbeddingUpdate {
	if v != nil {
		_u.SetIngestionID(*v)
	}
	return _u
}

// ClearIngestionID clears the value of the "ingestion_id" field.
func (_u *CodeEmbeddingUpdate) ClearIngestionID() *CodeEmbeddingUpdate {
	_u.mutation.ClearIngestionID()
	return _u
}

// SetEmbeddingVector sets the "embedding_vector" field.
func (_u *CodeEmbeddingUpdate) SetEmbeddingVector(v []float32) *CodeEmbeddingUpdate {
	_u.mutation.SetEmbeddingVector(v)
	return _u
}

// AppendEmbeddingVector appends value to the "embedding_vector" field.
func (_u *CodeEmbeddingUpdate) AppendEmbeddingVector(v []float32) *CodeEmbeddingUpdate {
	_u.mutation.AppendEmbeddingVector(v)
	return _u
}

// ClearEmbeddingVector clears the value of the "embedding_vector" field.
func (_u *CodeEmbeddingUpdate) ClearEmbeddingVector() *CodeEmbeddingUpdate {
	_u.mutation.ClearEmbeddingVector()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *CodeEmbeddingUpdate) SetMetadata(v map[string]interface{}) *CodeEmbeddingUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *CodeEmbeddingUpdate) ClearMetadata() *CodeEmbeddingUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CodeEmbeddingUpdate) SetCreatedAt(v time.Time) *CodeEmbeddingUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CodeEmbeddingUpdate) SetNillableCreatedAt(v *time.Time) *CodeEmbeddingUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetIngestion sets the "ingestion" edge to the CodeIngestion entity.
func (_u *CodeEmbeddingUpdate) SetIngestion(v *CodeIngestion) *CodeEmbeddingUpdate {
	return _u.SetIngestionID(v.ID)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *CodeEmbeddingUpdate) AddTagIDs(ids ...int64) *CodeEmbeddingUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *CodeEmbeddingUpdate) AddTags(v ...*Tag) *CodeEmbeddingUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the CodeEmbeddingMutation object of the builder.
func (_u *CodeEmbeddingUpdate) Mutation() *CodeEmbeddingMutation {
	return _u.mutation
}

// ClearIngestion clears the "ingestion" edge to the CodeIngestion entity.
func (_u *CodeEmbeddingUpdate) ClearIngestion() *CodeEmbeddingUpdate {
	_u.mutation.ClearIngestion()
	return _u
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *CodeEmbeddingUpdate) ClearTags() *CodeEmbeddingUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *CodeEmbeddingUpdate) RemoveTagIDs(ids ...int64) *CodeEmbeddingUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *CodeEmbeddingUpdate) RemoveTags(v ...*Tag) *CodeEmbeddingUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodeEmbeddingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodeEmbeddingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodeEmbeddingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodeEmbeddingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CodeEmbeddingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(codeembedding.Table, codeembedding.Columns, sqlgraph.NewFieldSpec(codeembedding.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EmbeddingVector(); ok {
		_spec.SetField(codeembedding.FieldEmbeddingVector, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbeddingVector(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, codeembedding.FieldEmbeddingVector, value)
		})
	}
	if _u.mutation.EmbeddingVectorCleared() {
		_spec.ClearField(codeembedding.FieldEmbeddingVector, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(codeembedding.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(codeembedding.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(codeembedding.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.IngestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codeembedding.IngestionTable,
			Columns: []string{codeembedding.IngestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codeingestion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IngestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codeembedding.IngestionTable,
			Columns: []string{codeembedding.IngestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codeingestion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   codeembedding.TagsTable,
			Columns: codeembedding.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   codeembedding.TagsTable,
			Columns: codeembedding.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   codeembedding.TagsTable,
			Columns: codeembedding.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codeembedding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodeEmbeddingUpdateOne is the builder for updating a single CodeEmbedding entity.
type CodeEmbeddingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodeEmbeddingMutation
}

// SetIngestionID sets the "ingestion_id" field.
func (_u *CodeEmbeddingUpdateOne) SetIngestionID(v int64) *CodeEmbeddingUpdateOne {
	_u.mutation.SetIngestionID(v)
	return _u
}

// SetNillableIngestionID sets the "ingestion_id" field if the given value is not nil.
func (_u *CodeEmbeddingUpdateOne) SetNillableIngestionID(v *int64) *CodeEmbeddingUpdateOne {
	if v != nil {
		_u.SetIngestionID(*v)
	}
	return _u
}

// ClearIngestionID clears the value of the "ingestion_id" field.
func (_u *CodeEmbeddingUpdateOne) ClearIngestionID() *CodeEmbeddingUpdateOne {
	_u.mutation.ClearIngestionID()
	return _u
}

// SetEmbeddingVector sets the "embedding_vector" field.
func (_u *CodeEmbeddingUpdateOne) SetEmbeddingVector(v []float32) *CodeEmbeddingUpdateOne {
	_u.mutation.SetEmbeddingVector(v)
	return _u
}

// AppendEmbeddingVector appends value to the "embedding_vector" field.
func (_u *CodeEmbeddingUpdateOne) AppendEmbeddingVector(v []float32) *CodeEmbeddingUpdateOne {
	_u.mutation.AppendEmbeddingVector(v)
	return _u
}

// ClearEmbeddingVector clears the value of the "embedding_vector" field.
func (_u *CodeEmbeddingUpdateOne) ClearEmbeddingVector() *CodeEmbeddingUpdateOne {
	_u.mutation.ClearEmbeddingVector()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *CodeEmbeddingUpdateOne) SetMetadata(v map[string]interface{}) *CodeEmbeddingUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *CodeEmbeddingUpdateOne) ClearMetadata() *CodeEmbeddingUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CodeEmbeddingUpdateOne) SetCreatedAt(v time.Time) *CodeEmbeddingUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CodeEmbeddingUpdateOne) SetNillableCreatedAt(v *time.Time) *CodeEmbeddingUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetIngestion sets the "ingestion" edge to the CodeIngestion entity.
func (_u *CodeEmbeddingUpdateOne) SetIngestion(v *CodeIngestion) *CodeEmbeddingUpdateOne {
	return _u.SetIngestionID(v.ID)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *CodeEmbeddingUpdateOne) AddTagIDs(ids ...int64) *CodeEmbeddingUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *CodeEmbeddingUpdateOne) AddTags(v ...*Tag) *CodeEmbeddingUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the CodeEmbeddingMutation object of the builder.
func (_u *CodeEmbeddingUpdateOne) Mutation() *CodeEmbeddingMutation {
	return _u.mutation
}

// ClearIngestion clears the "ingestion" edge to the CodeIngestion entity.
func (_u *CodeEmbeddingUpdateOne) ClearIngestion() *CodeEmbeddingUpdateOne {
	_u.mutation.ClearIngestion()
	return _u
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *CodeEmbeddingUpdateOne) ClearTags() *CodeEmbeddingUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *CodeEmbeddingUpdateOne) RemoveTagIDs(ids ...int64) *CodeEmbeddingUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *CodeEmbeddingUpdateOne) RemoveTags(v ...*Tag) *CodeEmbeddingUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the CodeEmbeddingUpdate builder.
func (_u *CodeEmbeddingUpdateOne) Where(ps ...predicate.CodeEmbedding) *CodeEmbeddingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodeEmbeddingUpdateOne) Select(field string, fields ...string) *CodeEmbeddingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodeEmbedding entity.
func (_u *CodeEmbeddingUpdateOne) Save(ctx context.Context) (*CodeEmbedding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodeEmbeddingUpdateOne) SaveX(ctx context.Context) *CodeEmbedding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodeEmbeddingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodeEmbeddingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CodeEmbeddingUpdateOne) sqlSave(ctx context.Context) (_node *CodeEmbedding, err error) {
	_spec := sqlgraph.NewUpdateSpec(codeembedding.Table, codeembedding.Columns, sqlgraph.NewFieldSpec(codeembedding.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodeEmbedding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codeembedding.FieldID)
		for _, f := range fields {
			if !codeembedding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codeembedding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EmbeddingVector(); ok {
		_spec.SetField(codeembedding.FieldEmbeddingVector, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbeddingVector(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, codeembedding.FieldEmbeddingVector, value)
		})
	}
	if _u.mutation.EmbeddingVectorCleared() {
		_spec.ClearField(codeembedding.FieldEmbeddingVector, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(codeembedding.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(codeembedding.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(codeembedding.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.IngestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codeembedding.IngestionTable,
			Columns: []string{codeembedding.IngestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codeingestion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IngestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codeembedding.IngestionTable,
			Columns: []string{codeembedding.IngestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codeingestion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   codeembedding.TagsTable,
			Columns: codeembedding.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   codeembedding.TagsTable,
			Columns: codeembedding.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   codeembedding.TagsTable,
			Columns: codeembedding.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CodeEmbedding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codeembedding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
