// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/memorylink"
	"app-builds/common/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemoryLinkDelete is the builder for deleting a MemoryLink entity.
type MemoryLinkDelete struct {
	config
	hooks    []Hook
	mutation *MemoryLinkMutation
}

// Where appends a list predicates to the MemoryLinkDelete builder.
func (_d *MemoryLinkDelete) Where(ps ...predicate.MemoryLink) *MemoryLinkDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MemoryLinkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemoryLinkDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MemoryLinkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(memorylink.Table, sqlgraph.NewFieldSpec(memorylink.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MemoryLinkDeleteOne is the builder for deleting a single MemoryLink entity.
type MemoryLinkDeleteOne struct {
	_d *MemoryLinkDelete
}

// Where appends a list predicates to the MemoryLinkDelete builder.
func (_d *MemoryLinkDeleteOne) Where(ps ...predicate.MemoryLink) *MemoryLinkDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MemoryLinkDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{memorylink.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemoryLinkDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
