// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/memoryevent"
	"app-builds/common/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemoryEventDelete is the builder for deleting a MemoryEvent entity.
type MemoryEventDelete struct {
	config
	hooks    []Hook
	mutation *MemoryEventMutation
}

// Where appends a list predicates to the MemoryEventDelete builder.
func (_d *MemoryEventDelete) Where(ps ...predicate.MemoryEvent) *MemoryEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MemoryEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemoryEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MemoryEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(memoryevent.Table, sqlgraph.NewFieldSpec(memoryevent.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MemoryEventDeleteOne is the builder for deleting a single MemoryEvent entity.
type MemoryEventDeleteOne struct {
	_d *MemoryEventDelete
}

// Where appends a list predicates to the MemoryEventDelete builder.
func (_d *MemoryEventDeleteOne) Where(ps ...predicate.MemoryEvent) *MemoryEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MemoryEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{memoryevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemoryEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
