// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/memoryevent"
	"app-builds/common/ent/memoryitem"
	"app-builds/common/ent/session"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemoryEventCreate is the builder for creating a MemoryEvent entity.
type MemoryEventCreate struct {
	config
	mutation *MemoryEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMemoryItemID sets the "memory_item_id" field.
func (_c *MemoryEventCreate) SetMemoryItemID(v int64) *MemoryEventCreate {
	_c.mutation.SetMemoryItemID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *MemoryEventCreate) SetSessionID(v int64) *MemoryEventCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *MemoryEventCreate) SetNillableSessionID(v *int64) *MemoryEventCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *MemoryEventCreate) SetEventType(v string) *MemoryEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetEventData sets the "event_data" field.
func (_c *MemoryEventCreate) SetEventData(v map[string]interface{}) *MemoryEventCreate {
	_c.mutation.SetEventData(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MemoryEventCreate) SetCreatedAt(v time.Time) *MemoryEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MemoryEventCreate) SetNillableCreatedAt(v *time.Time) *MemoryEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MemoryEventCreate) SetID(v int64) *MemoryEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSession sets the "session" edge to the Session entity.
func (_c *MemoryEventCreate) SetSession(v *Session) *MemoryEventCreate {
	return _c.SetSessionID(v.ID)
}

// SetMemoryItem sets the "memory_item" edge to the MemoryItem entity.
func (_c *MemoryEventCreate) SetMemoryItem(v *MemoryItem) *MemoryEventCreate {
	return _c.SetMemoryItemID(v.ID)
}

// Mutation returns the MemoryEventMutation object of the builder.
func (_c *MemoryEventCreate) Mutation() *MemoryEventMutation {
	return _c.mutation
}

// Save creates the MemoryEvent in the database.
func (_c *MemoryEventCreate) Save(ctx context.Context) (*MemoryEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemoryEventCreate) SaveX(ctx context.Context) *MemoryEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemoryEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := memoryevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemoryEventCreate) check() error {
	if _, ok := _c.mutation.MemoryItemID(); !ok {
		return &ValidationError{Name: "memory_item_id", err: errors.New(`ent: missing required field "MemoryEvent.memory_item_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "MemoryEvent.event_type"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MemoryEvent.created_at"`)}
	}
	if len(_c.mutation.MemoryItemIDs()) == 0 {
		return &ValidationError{Name: "memory_item", err: errors.New(`ent: missing required edge "MemoryEvent.memory_item"`)}
	}
	return nil
}

func (_c *MemoryEventCreate) sqlSave(ctx context.Context) (*MemoryEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemoryEventCreate) createSpec() (*MemoryEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &MemoryEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memoryevent.Table, sqlgraph.NewFieldSpec(memoryevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(memoryevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.EventData(); ok {
		_spec.SetField(memoryevent.FieldEventData, field.TypeJSON, value)
		_node.EventData = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(memoryevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memoryevent.SessionTable,
			Columns: []string{memoryevent.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MemoryItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memoryevent.MemoryItemTable,
			Columns: []string{memoryevent.MemoryItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memoryitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MemoryItemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MemoryEvent.Create().
//		SetMemoryItemID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MemoryEventUpsert) {
//			SetMemoryItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *MemoryEventCreate) OnConflict(opts ...sql.ConflictOption) *MemoryEventUpsertOne {
	_c.conflict = opts
	return &MemoryEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MemoryEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MemoryEventCreate) OnConflictColumns(columns ...string) *MemoryEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MemoryEventUpsertOne{
		create: _c,
	}
}

type (
	// MemoryEventUpsertOne is the builder for "upsert"-ing
	//  one MemoryEvent node.
	MemoryEventUpsertOne struct {
		create *MemoryEventCreate
	}

	// MemoryEventUpsert is the "OnConflict" setter.
	MemoryEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetMemoryItemID sets the "memory_item_id" field.
func (u *MemoryEventUpsert) SetMemoryItemID(v int64) *MemoryEventUpsert {
	u.Set(memoryevent.FieldMemoryItemID, v)
	return u
}

// UpdateMemoryItemID sets the "memory_item_id" field to the value that was provided on create.
func (u *MemoryEventUpsert) UpdateMemoryItemID() *MemoryEventUpsert {
	u.SetExcluded(memoryevent.FieldMemoryItemID)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *MemoryEventUpsert) SetSessionID(v int64) *MemoryEventUpsert {
	u.Set(memoryevent.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *MemoryEventUpsert) UpdateSessionID() *MemoryEventUpsert {
	u.SetExcluded(memoryevent.FieldSessionID)
	return u
}

// ClearSessionID clears the value of the "session_id" field.
func (u *MemoryEventUpsert) ClearSessionID() *MemoryEventUpsert {
	u.SetNull(memoryevent.FieldSessionID)
	return u
}

// SetEventType sets the "event_type" field.
func (u *MemoryEventUpsert) SetEventType(v string) *MemoryEventUpsert {
	u.Set(memoryevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *MemoryEventUpsert) UpdateEventType() *MemoryEventUpsert {
	u.SetExcluded(memoryevent.FieldEventType)
	return u
}

// SetEventData sets the "event_data" field.
func (u *MemoryEventUpsert) SetEventData(v map[string]interface{}) *MemoryEventUpsert {
	u.Set(memoryevent.FieldEventData, v)
	return u
}

// UpdateEventData sets the "event_data" field to the value that was provided on create.
func (u *MemoryEventUpsert) UpdateEventData() *MemoryEventUpsert {
	u.SetExcluded(memoryevent.FieldEventData)
	return u
}

// ClearEventData clears the value of the "event_data" field.
func (u *MemoryEventUpsert) ClearEventData() *MemoryEventUpsert {
	u.SetNull(memoryevent.FieldEventData)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MemoryEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(memoryevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MemoryEventUpsertOne) UpdateNewValues() *MemoryEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(memoryevent.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(memoryevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MemoryEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MemoryEventUpsertOne) Ignore() *MemoryEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MemoryEventUpsertOne) DoNothing() *MemoryEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MemoryEventCreate.OnConflict
// documentation for more info.
func (u *MemoryEventUpsertOne) Update(set func(*MemoryEventUpsert)) *MemoryEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MemoryEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetMemoryItemID sets the "memory_item_id" field.
func (u *MemoryEventUpsertOne) SetMemoryItemID(v int64) *MemoryEventUpsertOne {
	return u.Update(func(s *MemoryEventUpsert) {
		s.SetMemoryItemID(v)
	})
}

// UpdateMemoryItemID sets the "memory_item_id" field to the value that was provided on create.
func (u *MemoryEventUpsertOne) UpdateMemoryItemID() *MemoryEventUpsertOne {
	return u.Update(func(s *MemoryEventUpsert) {
		s.UpdateMemoryItemID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *MemoryEventUpsertOne) SetSessionID(v int64) *MemoryEventUpsertOne {
	return u.Update(func(s *MemoryEventUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *MemoryEventUpsertOne) UpdateSessionID() *MemoryEventUpsertOne {
	return u.Update(func(s *MemoryEventUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *MemoryEventUpsertOne) ClearSessionID() *MemoryEventUpsertOne {
	return u.Update(func(s *MemoryEventUpsert) {
		s.ClearSessionID()
	})
}

// SetEventType sets the "event_type" field.
func (u *MemoryEventUpsertOne) SetEventType(v string) *MemoryEventUpsertOne {
	return u.Update(func(s *MemoryEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *MemoryEventUpsertOne) UpdateEventType() *MemoryEventUpsertOne {
	return u.Update(func(s *MemoryEventUpsert) {
		s.UpdateEventType()
	})
}

// SetEventData sets the "event_data" field.
func (u *MemoryEventUpsertOne) SetEventData(v map[string]interface{}) *MemoryEventUpsertOne {
	return u.Update(func(s *MemoryEventUpsert) {
		s.SetEventData(v)
	})
}

// UpdateEventData sets the "event_data" field to the value that was provided on create.
func (u *MemoryEventUpsertOne) UpdateEventData() *MemoryEventUpsertOne {
	return u.Update(func(s *MemoryEventUpsert) {
		s.UpdateEventData()
	})
}

// ClearEventData clears the value of the "event_data" field.
func (u *MemoryEventUpsertOne) ClearEventData() *MemoryEventUpsertOne {
	return u.Update(func(s *MemoryEventUpsert) {
		s.ClearEventData()
	})
}

// Exec executes the query.
func (u *MemoryEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MemoryEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MemoryEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MemoryEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MemoryEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MemoryEventCreateBulk is the builder for creating many MemoryEvent entities in bulk.
type MemoryEventCreateBulk struct {
	config
	err      error
	builders []*MemoryEventCreate
	conflict []sql.ConflictOption
}

// Save creates the MemoryEvent entities in the database.
func (_c *MemoryEventCreateBulk) Save(ctx context.Context) ([]*MemoryEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemoryEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemoryEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemoryEventCreateBulk) SaveX(ctx context.Context) []*MemoryEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MemoryEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MemoryEventUpsert) {
//			SetMemoryItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *MemoryEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *MemoryEventUpsertBulk {
	_c.conflict = opts
	return &MemoryEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MemoryEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MemoryEventCreateBulk) OnConflictColumns(columns ...string) *MemoryEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MemoryEventUpsertBulk{
		create: _c,
	}
}

// MemoryEventUpsertBulk is the builder for "upsert"-ing
// a bulk of MemoryEvent nodes.
type MemoryEventUpsertBulk struct {
	create *MemoryEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MemoryEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(memoryevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MemoryEventUpsertBulk) UpdateNewValues() *MemoryEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(memoryevent.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(memoryevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MemoryEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MemoryEventUpsertBulk) Ignore() *MemoryEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MemoryEventUpsertBulk) DoNothing() *MemoryEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MemoryEventCreateBulk.OnConflict
// documentation for more info.
func (u *MemoryEventUpsertBulk) Update(set func(*MemoryEventUpsert)) *MemoryEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MemoryEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetMemoryItemID sets the "memory_item_id" field.
func (u *MemoryEventUpsertBulk) SetMemoryItemID(v int64) *MemoryEventUpsertBulk {
	return u.Update(func(s *MemoryEventUpsert) {
		s.SetMemoryItemID(v)
	})
}

// UpdateMemoryItemID sets the "memory_item_id" field to the value that was provided on create.
func (u *MemoryEventUpsertBulk) UpdateMemoryItemID() *MemoryEventUpsertBulk {
	return u.Update(func(s *MemoryEventUpsert) {
		s.UpdateMemoryItemID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *MemoryEventUpsertBulk) SetSessionID(v int64) *MemoryEventUpsertBulk {
	return u.Update(func(s *MemoryEventUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *MemoryEventUpsertBulk) UpdateSessionID() *MemoryEventUpsertBulk {
	return u.Update(func(s *MemoryEventUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *MemoryEventUpsertBulk) ClearSessionID() *MemoryEventUpsertBulk {
	return u.Update(func(s *MemoryEventUpsert) {
		s.ClearSessionID()
	})
}

// SetEventType sets the "event_type" field.
func (u *MemoryEventUpsertBulk) SetEventType(v string) *MemoryEventUpsertBulk {
	return u.Update(func(s *MemoryEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *MemoryEventUpsertBulk) UpdateEventType() *MemoryEventUpsertBulk {
	return u.Update(func(s *MemoryEventUpsert) {
		s.UpdateEventType()
	})
}

// SetEventData sets the "event_data" field.
func (u *MemoryEventUpsertBulk) SetEventData(v map[string]interface{}) *MemoryEventUpsertBulk {
	return u.Update(func(s *MemoryEventUpsert) {
		s.SetEventData(v)
	})
}

// UpdateEventData sets the "event_data" field to the value that was provided on create.
func (u *MemoryEventUpsertBulk) UpdateEventData() *MemoryEventUpsertBulk {
	return u.Update(func(s *MemoryEventUpsert) {
		s.UpdateEventData()
	})
}

// ClearEventData clears the value of the "event_data" field.
func (u *MemoryEventUpsertBulk) ClearEventData() *MemoryEventUpsertBulk {
	return u.Update(func(s *MemoryEventUpsert) {
		s.ClearEventData()
	})
}

// Exec executes the query.
func (u *MemoryEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MemoryEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MemoryEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MemoryEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
