// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/memoryevent"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MemoryEventCreate is the builder for creating a MemoryEvent entity.
type MemoryEventCreate struct {
	config
	mutation *MemoryEventMutation
	hooks    []Hook
}

// SetMemoryItemID sets the "memory_item_id" field.
func (_c *MemoryEventCreate) SetMemoryItemID(v uuid.UUID) *MemoryEventCreate {
	_c.mutation.SetMemoryItemID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *MemoryEventCreate) SetEventType(v string) *MemoryEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetEventData sets the "event_data" field.
func (_c *MemoryEventCreate) SetEventData(v map[string]interface{}) *MemoryEventCreate {
	_c.mutation.SetEventData(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MemoryEventCreate) SetCreatedAt(v time.Time) *MemoryEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MemoryEventCreate) SetNillableCreatedAt(v *time.Time) *MemoryEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MemoryEventCreate) SetID(v uuid.UUID) *MemoryEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MemoryEventCreate) SetNillableID(v *uuid.UUID) *MemoryEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MemoryEventMutation object of the builder.
func (_c *MemoryEventCreate) Mutation() *MemoryEventMutation {
	return _c.mutation
}

// Save creates the MemoryEvent in the database.
func (_c *MemoryEventCreate) Save(ctx context.Context) (*MemoryEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemoryEventCreate) SaveX(ctx context.Context) *MemoryEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemoryEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := memoryevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := memoryevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemoryEventCreate) check() error {
	if _, ok := _c.mutation.MemoryItemID(); !ok {
		return &ValidationError{Name: "memory_item_id", err: errors.New(`ent: missing required field "MemoryEvent.memory_item_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "MemoryEvent.event_type"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MemoryEvent.created_at"`)}
	}
	return nil
}

func (_c *MemoryEventCreate) sqlSave(ctx context.Context) (*MemoryEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemoryEventCreate) createSpec() (*MemoryEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &MemoryEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memoryevent.Table, sqlgraph.NewFieldSpec(memoryevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.MemoryItemID(); ok {
		_spec.SetField(memoryevent.FieldMemoryItemID, field.TypeUUID, value)
		_node.MemoryItemID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(memoryevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.EventData(); ok {
		_spec.SetField(memoryevent.FieldEventData, field.TypeJSON, value)
		_node.EventData = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(memoryevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// MemoryEventCreateBulk is the builder for creating many MemoryEvent entities in bulk.
type MemoryEventCreateBulk struct {
	config
	err      error
	builders []*MemoryEventCreate
}

// Save creates the MemoryEvent entities in the database.
func (_c *MemoryEventCreateBulk) Save(ctx context.Context) ([]*MemoryEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemoryEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemoryEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemoryEventCreateBulk) SaveX(ctx context.Context) []*MemoryEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
