// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/memoryevent"
	"app-builds/common/ent/memoryitem"
	"app-builds/common/ent/memorylink"
	"app-builds/common/ent/predicate"
	"app-builds/common/ent/session"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MemoryItemUpdate is the builder for updating MemoryItem entities.
type MemoryItemUpdate struct {
	config
	hooks    []Hook
	mutation *MemoryItemMutation
}

// Where appends a list predicates to the MemoryItemUpdate builder.
func (_u *MemoryItemUpdate) Where(ps ...predicate.MemoryItem) *MemoryItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *MemoryItemUpdate) SetProjectID(v int64) *MemoryItemUpdate {
	_u.mutation.ResetProjectID()
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillableProjectID(v *int64) *MemoryItemUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// AddProjectID adds value to the "project_id" field.
func (_u *MemoryItemUpdate) AddProjectID(v int64) *MemoryItemUpdate {
	_u.mutation.AddProjectID(v)
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *MemoryItemUpdate) ClearProjectID() *MemoryItemUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MemoryItemUpdate) SetSessionID(v int64) *MemoryItemUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillableSessionID(v *int64) *MemoryItemUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *MemoryItemUpdate) ClearSessionID() *MemoryItemUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MemoryItemUpdate) SetUserID(v uuid.UUID) *MemoryItemUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillableUserID(v *uuid.UUID) *MemoryItemUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *MemoryItemUpdate) ClearUserID() *MemoryItemUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetMemoryType sets the "memory_type" field.
func (_u *MemoryItemUpdate) SetMemoryType(v string) *MemoryItemUpdate {
	_u.mutation.SetMemoryType(v)
	return _u
}

// SetNillableMemoryType sets the "memory_type" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillableMemoryType(v *string) *MemoryItemUpdate {
	if v != nil {
		_u.SetMemoryType(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *MemoryItemUpdate) SetSummary(v string) *MemoryItemUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillableSummary(v *string) *MemoryItemUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MemoryItemUpdate) SetContent(v string) *MemoryItemUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillableContent(v *string) *MemoryItemUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *MemoryItemUpdate) ClearContent() *MemoryItemUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetSalience sets the "salience" field.
func (_u *MemoryItemUpdate) SetSalience(v float64) *MemoryItemUpdate {
	_u.mutation.ResetSalience()
	_u.mutation.SetSalience(v)
	return _u
}

// SetNillableSalience sets the "salience" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillableSalience(v *float64) *MemoryItemUpdate {
	if v != nil {
		_u.SetSalience(*v)
	}
	return _u
}

// AddSalience adds value to the "salience" field.
func (_u *MemoryItemUpdate) AddSalience(v float64) *MemoryItemUpdate {
	_u.mutation.AddSalience(v)
	return _u
}

// SetRetentionScore sets the "retention_score" field.
func (_u *MemoryItemUpdate) SetRetentionScore(v float64) *MemoryItemUpdate {
	_u.mutation.ResetRetentionScore()
	_u.mutation.SetRetentionScore(v)
	return _u
}

// SetNillableRetentionScore sets the "retention_score" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillableRetentionScore(v *float64) *MemoryItemUpdate {
	if v != nil {
		_u.SetRetentionScore(*v)
	}
	return _u
}

// AddRetentionScore adds value to the "retention_score" field.
func (_u *MemoryItemUpdate) AddRetentionScore(v float64) *MemoryItemUpdate {
	_u.mutation.AddRetentionScore(v)
	return _u
}

// SetDecayState sets the "decay_state" field.
func (_u *MemoryItemUpdate) SetDecayState(v map[string]interface{}) *MemoryItemUpdate {
	_u.mutation.SetDecayState(v)
	return _u
}

// ClearDecayState clears the value of the "decay_state" field.
func (_u *MemoryItemUpdate) ClearDecayState() *MemoryItemUpdate {
	_u.mutation.ClearDecayState()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MemoryItemUpdate) SetStatus(v string) *MemoryItemUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillableStatus(v *string) *MemoryItemUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *MemoryItemUpdate) SetPinned(v bool) *MemoryItemUpdate {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillablePinned(v *bool) *MemoryItemUpdate {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MemoryItemUpdate) SetExpiresAt(v time.Time) *MemoryItemUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillableExpiresAt(v *time.Time) *MemoryItemUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MemoryItemUpdate) ClearExpiresAt() *MemoryItemUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MemoryItemUpdate) SetMetadata(v map[string]interface{}) *MemoryItemUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MemoryItemUpdate) ClearMetadata() *MemoryItemUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MemoryItemUpdate) SetCreatedAt(v time.Time) *MemoryItemUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MemoryItemUpdate) SetNillableCreatedAt(v *time.Time) *MemoryItemUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemoryItemUpdate) SetUpdatedAt(v time.Time) *MemoryItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *MemoryItemUpdate) SetSession(v *Session) *MemoryItemUpdate {
	return _u.SetSessionID(v.ID)
}

// AddLinkIDs adds the "links" edge to the MemoryLink entity by IDs.
func (_u *MemoryItemUpdate) AddLinkIDs(ids ...int64) *MemoryItemUpdate {
	_u.mutation.AddLinkIDs(ids...)
	return _u
}

// AddLinks adds the "links" edges to the MemoryLink entity.
func (_u *MemoryItemUpdate) AddLinks(v ...*MemoryLink) *MemoryItemUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkIDs(ids...)
}

// AddEventIDs adds the "events" edge to the MemoryEvent entity by IDs.
func (_u *MemoryItemUpdate) AddEventIDs(ids ...int64) *MemoryItemUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the MemoryEvent entity.
func (_u *MemoryItemUpdate) AddEvents(v ...*MemoryEvent) *MemoryItemUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the MemoryItemMutation object of the builder.
func (_u *MemoryItemUpdate) Mutation() *MemoryItemMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *MemoryItemUpdate) ClearSession() *MemoryItemUpdate {
	_u.mutation.ClearSession()
	return _u
}

// ClearLinks clears all "links" edges to the MemoryLink entity.
func (_u *MemoryItemUpdate) ClearLinks() *MemoryItemUpdate {
	_u.mutation.ClearLinks()
	return _u
}

// RemoveLinkIDs removes the "links" edge to MemoryLink entities by IDs.
func (_u *MemoryItemUpdate) RemoveLinkIDs(ids ...int64) *MemoryItemUpdate {
	_u.mutation.RemoveLinkIDs(ids...)
	return _u
}

// RemoveLinks removes "links" edges to MemoryLink entities.
func (_u *MemoryItemUpdate) RemoveLinks(v ...*MemoryLink) *MemoryItemUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkIDs(ids...)
}

// ClearEvents clears all "events" edges to the MemoryEvent entity.
func (_u *MemoryItemUpdate) ClearEvents() *MemoryItemUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to MemoryEvent entities by IDs.
func (_u *MemoryItemUpdate) RemoveEventIDs(ids ...int64) *MemoryItemUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to MemoryEvent entities.
func (_u *MemoryItemUpdate) RemoveEvents(v ...*MemoryEvent) *MemoryItemUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemoryItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemoryItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoryItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memoryitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *MemoryItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(memoryitem.Table, memoryitem.Columns, sqlgraph.NewFieldSpec(memoryitem.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(memoryitem.FieldProjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProjectID(); ok {
		_spec.AddField(memoryitem.FieldProjectID, field.TypeInt64, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(memoryitem.FieldProjectID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(memoryitem.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(memoryitem.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.MemoryType(); ok {
		_spec.SetField(memoryitem.FieldMemoryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(memoryitem.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(memoryitem.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(memoryitem.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Salience(); ok {
		_spec.SetField(memoryitem.FieldSalience, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSalience(); ok {
		_spec.AddField(memoryitem.FieldSalience, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RetentionScore(); ok {
		_spec.SetField(memoryitem.FieldRetentionScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRetentionScore(); ok {
		_spec.AddField(memoryitem.FieldRetentionScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DecayState(); ok {
		_spec.SetField(memoryitem.FieldDecayState, field.TypeJSON, value)
	}
	if _u.mutation.DecayStateCleared() {
		_spec.ClearField(memoryitem.FieldDecayState, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(memoryitem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(memoryitem.FieldPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(memoryitem.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(memoryitem.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(memoryitem.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(memoryitem.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(memoryitem.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memoryitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memoryitem.SessionTable,
			Columns: []string{memoryitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memoryitem.SessionTable,
			Columns: []string{memoryitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.LinksTable,
			Columns: []string{memoryitem.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorylink.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinksIDs(); len(nodes) > 0 && !_u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.LinksTable,
			Columns: []string{memoryitem.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorylink.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.LinksTable,
			Columns: []string{memoryitem.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorylink.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.EventsTable,
			Columns: []string{memoryitem.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memoryevent.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.EventsTable,
			Columns: []string{memoryitem.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memoryevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.EventsTable,
			Columns: []string{memoryitem.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memoryevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memoryitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemoryItemUpdateOne is the builder for updating a single MemoryItem entity.
type MemoryItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemoryItemMutation
}

// SetProjectID sets the "project_id" field.
func (_u *MemoryItemUpdateOne) SetProjectID(v int64) *MemoryItemUpdateOne {
	_u.mutation.ResetProjectID()
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillableProjectID(v *int64) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// AddProjectID adds value to the "project_id" field.
func (_u *MemoryItemUpdateOne) AddProjectID(v int64) *MemoryItemUpdateOne {
	_u.mutation.AddProjectID(v)
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *MemoryItemUpdateOne) ClearProjectID() *MemoryItemUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MemoryItemUpdateOne) SetSessionID(v int64) *MemoryItemUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillableSessionID(v *int64) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *MemoryItemUpdateOne) ClearSessionID() *MemoryItemUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MemoryItemUpdateOne) SetUserID(v uuid.UUID) *MemoryItemUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillableUserID(v *uuid.UUID) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *MemoryItemUpdateOne) ClearUserID() *MemoryItemUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetMemoryType sets the "memory_type" field.
func (_u *MemoryItemUpdateOne) SetMemoryType(v string) *MemoryItemUpdateOne {
	_u.mutation.SetMemoryType(v)
	return _u
}

// SetNillableMemoryType sets the "memory_type" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillableMemoryType(v *string) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetMemoryType(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *MemoryItemUpdateOne) SetSummary(v string) *MemoryItemUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillableSummary(v *string) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MemoryItemUpdateOne) SetContent(v string) *MemoryItemUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillableContent(v *string) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *MemoryItemUpdateOne) ClearContent() *MemoryItemUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetSalience sets the "salience" field.
func (_u *MemoryItemUpdateOne) SetSalience(v float64) *MemoryItemUpdateOne {
	_u.mutation.ResetSalience()
	_u.mutation.SetSalience(v)
	return _u
}

// SetNillableSalience sets the "salience" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillableSalience(v *float64) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetSalience(*v)
	}
	return _u
}

// AddSalience adds value to the "salience" field.
func (_u *MemoryItemUpdateOne) AddSalience(v float64) *MemoryItemUpdateOne {
	_u.mutation.AddSalience(v)
	return _u
}

// SetRetentionScore sets the "retention_score" field.
func (_u *MemoryItemUpdateOne) SetRetentionScore(v float64) *MemoryItemUpdateOne {
	_u.mutation.ResetRetentionScore()
	_u.mutation.SetRetentionScore(v)
	return _u
}

// SetNillableRetentionScore sets the "retention_score" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillableRetentionScore(v *float64) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetRetentionScore(*v)
	}
	return _u
}

// AddRetentionScore adds value to the "retention_score" field.
func (_u *MemoryItemUpdateOne) AddRetentionScore(v float64) *MemoryItemUpdateOne {
	_u.mutation.AddRetentionScore(v)
	return _u
}

// SetDecayState sets the "decay_state" field.
func (_u *MemoryItemUpdateOne) SetDecayState(v map[string]interface{}) *MemoryItemUpdateOne {
	_u.mutation.SetDecayState(v)
	return _u
}

// ClearDecayState clears the value of the "decay_state" field.
func (_u *MemoryItemUpdateOne) ClearDecayState() *MemoryItemUpdateOne {
	_u.mutation.ClearDecayState()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MemoryItemUpdateOne) SetStatus(v string) *MemoryItemUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillableStatus(v *string) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *MemoryItemUpdateOne) SetPinned(v bool) *MemoryItemUpdateOne {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillablePinned(v *bool) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MemoryItemUpdateOne) SetExpiresAt(v time.Time) *MemoryItemUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillableExpiresAt(v *time.Time) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MemoryItemUpdateOne) ClearExpiresAt() *MemoryItemUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MemoryItemUpdateOne) SetMetadata(v map[string]interface{}) *MemoryItemUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MemoryItemUpdateOne) ClearMetadata() *MemoryItemUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MemoryItemUpdateOne) SetCreatedAt(v time.Time) *MemoryItemUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MemoryItemUpdateOne) SetNillableCreatedAt(v *time.Time) *MemoryItemUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemoryItemUpdateOne) SetUpdatedAt(v time.Time) *MemoryItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *MemoryItemUpdateOne) SetSession(v *Session) *MemoryItemUpdateOne {
	return _u.SetSessionID(v.ID)
}

// AddLinkIDs adds the "links" edge to the MemoryLink entity by IDs.
func (_u *MemoryItemUpdateOne) AddLinkIDs(ids ...int64) *MemoryItemUpdateOne {
	_u.mutation.AddLinkIDs(ids...)
	return _u
}

// AddLinks adds the "links" edges to the MemoryLink entity.
func (_u *MemoryItemUpdateOne) AddLinks(v ...*MemoryLink) *MemoryItemUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkIDs(ids...)
}

// AddEventIDs adds the "events" edge to the MemoryEvent entity by IDs.
func (_u *MemoryItemUpdateOne) AddEventIDs(ids ...int64) *MemoryItemUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the MemoryEvent entity.
func (_u *MemoryItemUpdateOne) AddEvents(v ...*MemoryEvent) *MemoryItemUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the MemoryItemMutation object of the builder.
func (_u *MemoryItemUpdateOne) Mutation() *MemoryItemMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *MemoryItemUpdateOne) ClearSession() *MemoryItemUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// ClearLinks clears all "links" edges to the MemoryLink entity.
func (_u *MemoryItemUpdateOne) ClearLinks() *MemoryItemUpdateOne {
	_u.mutation.ClearLinks()
	return _u
}

// RemoveLinkIDs removes the "links" edge to MemoryLink entities by IDs.
func (_u *MemoryItemUpdateOne) RemoveLinkIDs(ids ...int64) *MemoryItemUpdateOne {
	_u.mutation.RemoveLinkIDs(ids...)
	return _u
}

// RemoveLinks removes "links" edges to MemoryLink entities.
func (_u *MemoryItemUpdateOne) RemoveLinks(v ...*MemoryLink) *MemoryItemUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkIDs(ids...)
}

// ClearEvents clears all "events" edges to the MemoryEvent entity.
func (_u *MemoryItemUpdateOne) ClearEvents() *MemoryItemUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to MemoryEvent entities by IDs.
func (_u *MemoryItemUpdateOne) RemoveEventIDs(ids ...int64) *MemoryItemUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to MemoryEvent entities.
func (_u *MemoryItemUpdateOne) RemoveEvents(v ...*MemoryEvent) *MemoryItemUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the MemoryItemUpdate builder.
func (_u *MemoryItemUpdateOne) Where(ps ...predicate.MemoryItem) *MemoryItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemoryItemUpdateOne) Select(field string, fields ...string) *MemoryItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemoryItem entity.
func (_u *MemoryItemUpdateOne) Save(ctx context.Context) (*MemoryItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryItemUpdateOne) SaveX(ctx context.Context) *MemoryItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemoryItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoryItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memoryitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *MemoryItemUpdateOne) sqlSave(ctx context.Context) (_node *MemoryItem, err error) {
	_spec := sqlgraph.NewUpdateSpec(memoryitem.Table, memoryitem.Columns, sqlgraph.NewFieldSpec(memoryitem.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemoryItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memoryitem.FieldID)
		for _, f := range fields {
			if !memoryitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memoryitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(memoryitem.FieldProjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProjectID(); ok {
		_spec.AddField(memoryitem.FieldProjectID, field.TypeInt64, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(memoryitem.FieldProjectID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(memoryitem.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(memoryitem.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.MemoryType(); ok {
		_spec.SetField(memoryitem.FieldMemoryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(memoryitem.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(memoryitem.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(memoryitem.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Salience(); ok {
		_spec.SetField(memoryitem.FieldSalience, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSalience(); ok {
		_spec.AddField(memoryitem.FieldSalience, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RetentionScore(); ok {
		_spec.SetField(memoryitem.FieldRetentionScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRetentionScore(); ok {
		_spec.AddField(memoryitem.FieldRetentionScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DecayState(); ok {
		_spec.SetField(memoryitem.FieldDecayState, field.TypeJSON, value)
	}
	if _u.mutation.DecayStateCleared() {
		_spec.ClearField(memoryitem.FieldDecayState, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(memoryitem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(memoryitem.FieldPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(memoryitem.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(memoryitem.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(memoryitem.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(memoryitem.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(memoryitem.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memoryitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memoryitem.SessionTable,
			Columns: []string{memoryitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memoryitem.SessionTable,
			Columns: []string{memoryitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.LinksTable,
			Columns: []string{memoryitem.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorylink.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinksIDs(); len(nodes) > 0 && !_u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.LinksTable,
			Columns: []string{memoryitem.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorylink.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.LinksTable,
			Columns: []string{memoryitem.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorylink.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.EventsTable,
			Columns: []string{memoryitem.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memoryevent.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.EventsTable,
			Columns: []string{memoryitem.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memoryevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memoryitem.EventsTable,
			Columns: []string{memoryitem.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memoryevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MemoryItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memoryitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
