// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/common/ent/tag"
	"app-builds/common/ent/tagembeddingcoverage"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TagEmbeddingCoverage is the model entity for the TagEmbeddingCoverage schema.
type TagEmbeddingCoverage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TagID holds the value of the "tag_id" field.
	TagID int64 `json:"tag_id,omitempty"`
	// EmbeddingModel holds the value of the "embedding_model" field.
	EmbeddingModel string `json:"embedding_model,omitempty"`
	// VectorDims holds the value of the "vector_dims" field.
	VectorDims int `json:"vector_dims,omitempty"`
	// VectorCount holds the value of the "vector_count" field.
	VectorCount int64 `json:"vector_count,omitempty"`
	// FileCount holds the value of the "file_count" field.
	FileCount int `json:"file_count,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LastEmbeddedAt holds the value of the "last_embedded_at" field.
	LastEmbeddedAt *time.Time `json:"last_embedded_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TagEmbeddingCoverageQuery when eager-loading is set.
	Edges        TagEmbeddingCoverageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TagEmbeddingCoverageEdges holds the relations/edges for other nodes in the graph.
type TagEmbeddingCoverageEdges struct {
	// Tag holds the value of the tag edge.
	Tag *Tag `json:"tag,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TagOrErr returns the Tag value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TagEmbeddingCoverageEdges) TagOrErr() (*Tag, error) {
	if e.Tag != nil {
		return e.Tag, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tag.Label}
	}
	return nil, &NotLoadedError{edge: "tag"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TagEmbeddingCoverage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tagembeddingcoverage.FieldID, tagembeddingcoverage.FieldTagID, tagembeddingcoverage.FieldVectorDims, tagembeddingcoverage.FieldVectorCount, tagembeddingcoverage.FieldFileCount:
			values[i] = new(sql.NullInt64)
		case tagembeddingcoverage.FieldEmbeddingModel, tagembeddingcoverage.FieldStatus:
			values[i] = new(sql.NullString)
		case tagembeddingcoverage.FieldLastEmbeddedAt, tagembeddingcoverage.FieldCreatedAt, tagembeddingcoverage.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TagEmbeddingCoverage fields.
func (_m *TagEmbeddingCoverage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tagembeddingcoverage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case tagembeddingcoverage.FieldTagID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tag_id", values[i])
			} else if value.Valid {
				_m.TagID = value.Int64
			}
		case tagembeddingcoverage.FieldEmbeddingModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field embedding_model", values[i])
			} else if value.Valid {
				_m.EmbeddingModel = value.String
			}
		case tagembeddingcoverage.FieldVectorDims:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field vector_dims", values[i])
			} else if value.Valid {
				_m.VectorDims = int(value.Int64)
			}
		case tagembeddingcoverage.FieldVectorCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field vector_count", values[i])
			} else if value.Valid {
				_m.VectorCount = value.Int64
			}
		case tagembeddingcoverage.FieldFileCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_count", values[i])
			} else if value.Valid {
				_m.FileCount = int(value.Int64)
			}
		case tagembeddingcoverage.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case tagembeddingcoverage.FieldLastEmbeddedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_embedded_at", values[i])
			} else if value.Valid {
				_m.LastEmbeddedAt = new(time.Time)
				*_m.LastEmbeddedAt = value.Time
			}
		case tagembeddingcoverage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tagembeddingcoverage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TagEmbeddingCoverage.
// This includes values selected through modifiers, order, etc.
func (_m *TagEmbeddingCoverage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTag queries the "tag" edge of the TagEmbeddingCoverage entity.
func (_m *TagEmbeddingCoverage) QueryTag() *TagQuery {
	return NewTagEmbeddingCoverageClient(_m.config).QueryTag(_m)
}

// Update returns a builder for updating this TagEmbeddingCoverage.
// Note that you need to call TagEmbeddingCoverage.Unwrap() before calling this method if this TagEmbeddingCoverage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TagEmbeddingCoverage) Update() *TagEmbeddingCoverageUpdateOne {
	return NewTagEmbeddingCoverageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TagEmbeddingCoverage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TagEmbeddingCoverage) Unwrap() *TagEmbeddingCoverage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TagEmbeddingCoverage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TagEmbeddingCoverage) String() string {
	var builder strings.Builder
	builder.WriteString("TagEmbeddingCoverage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tag_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TagID))
	builder.WriteString(", ")
	builder.WriteString("embedding_model=")
	builder.WriteString(_m.EmbeddingModel)
	builder.WriteString(", ")
	builder.WriteString("vector_dims=")
	builder.WriteString(fmt.Sprintf("%v", _m.VectorDims))
	builder.WriteString(", ")
	builder.WriteString("vector_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.VectorCount))
	builder.WriteString(", ")
	builder.WriteString("file_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileCount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LastEmbeddedAt; v != nil {
		builder.WriteString("last_embedded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TagEmbeddingCoverages is a parsable slice of TagEmbeddingCoverage.
type TagEmbeddingCoverages []*TagEmbeddingCoverage
