// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app-builds/db-adapter/internal/ent/predicate"
	"app-builds/db-adapter/internal/ent/session"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *SessionUpdate) SetProjectID(v uuid.UUID) *SessionUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableProjectID(v *uuid.UUID) *SessionUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *SessionUpdate) ClearProjectID() *SessionUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetName sets the "name" field.
func (_u *SessionUpdate) SetName(v string) *SessionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableName(v *string) *SessionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *SessionUpdate) ClearName() *SessionUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SessionUpdate) SetDescription(v string) *SessionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableDescription(v *string) *SessionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SessionUpdate) ClearDescription() *SessionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SessionUpdate) SetMetadata(v map[string]interface{}) *SessionUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SessionUpdate) ClearMetadata() *SessionUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdate) SetUserID(v uuid.UUID) *SessionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableUserID(v *uuid.UUID) *SessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *SessionUpdate) ClearUserID() *SessionUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SessionUpdate) SetCreatedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCreatedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetLastActiveAt sets the "last_active_at" field.
func (_u *SessionUpdate) SetLastActiveAt(v time.Time) *SessionUpdate {
	_u.mutation.SetLastActiveAt(v)
	return _u
}

// SetNillableLastActiveAt sets the "last_active_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableLastActiveAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetLastActiveAt(*v)
	}
	return _u
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(session.FieldProjectID, field.TypeUUID, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(session.FieldProjectID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(session.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(session.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(session.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(session.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(session.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(session.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(session.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(session.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(session.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastActiveAt(); ok {
		_spec.SetField(session.FieldLastActiveAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetProjectID sets the "project_id" field.
func (_u *SessionUpdateOne) SetProjectID(v uuid.UUID) *SessionUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableProjectID(v *uuid.UUID) *SessionUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *SessionUpdateOne) ClearProjectID() *SessionUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetName sets the "name" field.
func (_u *SessionUpdateOne) SetName(v string) *SessionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableName(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *SessionUpdateOne) ClearName() *SessionUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SessionUpdateOne) SetDescription(v string) *SessionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableDescription(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SessionUpdateOne) ClearDescription() *SessionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SessionUpdateOne) SetMetadata(v map[string]interface{}) *SessionUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SessionUpdateOne) ClearMetadata() *SessionUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdateOne) SetUserID(v uuid.UUID) *SessionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableUserID(v *uuid.UUID) *SessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *SessionUpdateOne) ClearUserID() *SessionUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SessionUpdateOne) SetCreatedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCreatedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetLastActiveAt sets the "last_active_at" field.
func (_u *SessionUpdateOne) SetLastActiveAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetLastActiveAt(v)
	return _u
}

// SetNillableLastActiveAt sets the "last_active_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableLastActiveAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetLastActiveAt(*v)
	}
	return _u
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(session.FieldProjectID, field.TypeUUID, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(session.FieldProjectID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(session.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(session.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(session.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(session.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(session.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(session.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(session.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(session.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(session.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastActiveAt(); ok {
		_spec.SetField(session.FieldLastActiveAt, field.TypeTime, value)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
