apiVersion: batch/v1
kind: Job
metadata:
  name: check-lsmod
  namespace: rook-ceph
spec:
  template:
    spec:
      hostPID: true
      containers:
      - name: check-lsmod
        image: 10.0.0.1:5000/docker.io/library/busybox
        securityContext:
          privileged: true
        command: ["lsmod"]
      restartPolicy: Never
  backoffLimit: 0
