apiVersion: batch/v1
kind: Job
metadata:
  name: check-lsmod
  namespace: rook-ceph
spec:
  template:
    spec:
      hostPID: true
      containers:
      - name: check-lsmod
        image: hierophant.hierocracy.home:5000/busybox:1.37.0
        securityContext:
          privileged: true
        command: ["lsmod"]
      restartPolicy: Never
  backoffLimit: 0
