apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: monitoring
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            tls:
              cert_file: /etc/otel/tls/tls.crt
              key_file: /etc/otel/tls/tls.key
          http:
            endpoint: 0.0.0.0:4318
            tls:
              cert_file: /etc/otel/tls/tls.crt
              key_file: /etc/otel/tls/tls.key

    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      probabilistic_sampler:
        sampling_percentage: 15.0

    exporters:
      otlphttp/loki:
        endpoint: https://loki-gateway.monitoring.svc.cluster.local/otlp
        tls:
          ca_file: /etc/ssl/certs/ca.crt
      otlp/tempo:
        endpoint: tempo.monitoring.svc.cluster.local:4317
        tls:
          insecure: false
          ca_file: /etc/ssl/certs/ca.crt
      otlphttp/mimir:
        endpoint: https://mimir-gateway.monitoring.svc.cluster.local/otlp
        tls:
          ca_file: /etc/ssl/certs/ca.crt
      debug:
        verbosity: basic

    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ memory_limiter, probabilistic_sampler, batch ]
          exporters: [ otlp/tempo, debug ]
        metrics:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch ]
          exporters: [ otlphttp/mimir, debug ]
        logs:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch ]
          exporters: [ otlphttp/loki, debug ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      nodeSelector:
        role: storage-node
      containers:
      - name: otel-collector
        image: registry.container-registry.svc.cluster.local:5000/otel/opentelemetry-collector-contrib:0.147.0
        args:
        - "--config=/etc/otel-collector-config.yaml"
        env:
        - name: SSL_CERT_FILE
          value: /etc/ssl/certs/ca.crt
        volumeMounts:
        - name: config
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
        - name: registry-ca
          mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt
        - name: otel-tls
          mountPath: /etc/otel/tls
        ports:
        - containerPort: 4317 # gRPC
        - containerPort: 4318 # HTTP
      volumes:
      - name: config
        configMap:
          name: otel-collector-conf
      - name: registry-ca
        configMap:
          name: registry-ca-cm
      - name: otel-tls
        secret:
          secretName: otel-collector-tls
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  selector:
    app: otel-collector
