// Code generated by ent, DO NOT EDIT.

package memorylink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the memorylink type in the database.
	Label = "memory_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMemoryItemID holds the string denoting the memory_item_id field in the database.
	FieldMemoryItemID = "memory_item_id"
	// FieldSourceMessageIds holds the string denoting the source_message_ids field in the database.
	FieldSourceMessageIds = "source_message_ids"
	// FieldIngestionIds holds the string denoting the ingestion_ids field in the database.
	FieldIngestionIds = "ingestion_ids"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeMemoryItem holds the string denoting the memory_item edge name in mutations.
	EdgeMemoryItem = "memory_item"
	// Table holds the table name of the memorylink in the database.
	Table = "memory_links"
	// MemoryItemTable is the table that holds the memory_item relation/edge.
	MemoryItemTable = "memory_links"
	// MemoryItemInverseTable is the table name for the MemoryItem entity.
	// It exists in this package in order to avoid circular dependency with the "memoryitem" package.
	MemoryItemInverseTable = "memory_items"
	// MemoryItemColumn is the table column denoting the memory_item relation/edge.
	MemoryItemColumn = "memory_item_id"
)

// Columns holds all SQL columns for memorylink fields.
var Columns = []string{
	FieldID,
	FieldMemoryItemID,
	FieldSourceMessageIds,
	FieldIngestionIds,
	FieldTags,
	FieldMetadata,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "memory_links"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"memory_item_links",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the MemoryLink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMemoryItemID orders the results by the memory_item_id field.
func ByMemoryItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemoryItemID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByMemoryItemField orders the results by memory_item field.
func ByMemoryItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMemoryItemStep(), sql.OrderByField(field, opts...))
	}
}
func newMemoryItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MemoryItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, MemoryItemTable, MemoryItemColumn),
	)
}
