// Code generated by ent, DO NOT EDIT.

package memorylink

import (
	"app-builds/common/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldLTE(FieldID, id))
}

// MemoryItemID applies equality check predicate on the "memory_item_id" field. It's identical to MemoryItemIDEQ.
func MemoryItemID(v int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldEQ(FieldMemoryItemID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldEQ(FieldCreatedAt, v))
}

// MemoryItemIDEQ applies the EQ predicate on the "memory_item_id" field.
func MemoryItemIDEQ(v int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldEQ(FieldMemoryItemID, v))
}

// MemoryItemIDNEQ applies the NEQ predicate on the "memory_item_id" field.
func MemoryItemIDNEQ(v int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldNEQ(FieldMemoryItemID, v))
}

// MemoryItemIDIn applies the In predicate on the "memory_item_id" field.
func MemoryItemIDIn(vs ...int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldIn(FieldMemoryItemID, vs...))
}

// MemoryItemIDNotIn applies the NotIn predicate on the "memory_item_id" field.
func MemoryItemIDNotIn(vs ...int64) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldNotIn(FieldMemoryItemID, vs...))
}

// SourceMessageIdsIsNil applies the IsNil predicate on the "source_message_ids" field.
func SourceMessageIdsIsNil() predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldIsNull(FieldSourceMessageIds))
}

// SourceMessageIdsNotNil applies the NotNil predicate on the "source_message_ids" field.
func SourceMessageIdsNotNil() predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldNotNull(FieldSourceMessageIds))
}

// IngestionIdsIsNil applies the IsNil predicate on the "ingestion_ids" field.
func IngestionIdsIsNil() predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldIsNull(FieldIngestionIds))
}

// IngestionIdsNotNil applies the NotNil predicate on the "ingestion_ids" field.
func IngestionIdsNotNil() predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldNotNull(FieldIngestionIds))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldNotNull(FieldTags))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MemoryLink {
	return predicate.MemoryLink(sql.FieldLTE(FieldCreatedAt, v))
}

// HasMemoryItem applies the HasEdge predicate on the "memory_item" edge.
func HasMemoryItem() predicate.MemoryLink {
	return predicate.MemoryLink(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MemoryItemTable, MemoryItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemoryItemWith applies the HasEdge predicate on the "memory_item" edge with a given conditions (other predicates).
func HasMemoryItemWith(preds ...predicate.MemoryItem) predicate.MemoryLink {
	return predicate.MemoryLink(func(s *sql.Selector) {
		step := newMemoryItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemoryLink) predicate.MemoryLink {
	return predicate.MemoryLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemoryLink) predicate.MemoryLink {
	return predicate.MemoryLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemoryLink) predicate.MemoryLink {
	return predicate.MemoryLink(sql.NotPredicates(p))
}
